'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Cloud, Copy, Download, FileCheck2, FileUp, Link2, MapPinned, RefreshCw, ShieldCheck, UserCheck } from 'lucide-react';
import { getBrowserClient } from '../../../../lib/supabase';

const STORAGE_KEY='aridon-ag-field-passport-v2';
const card:React.CSSProperties={background:'#fff',border:'1px solid #d7e0d3',borderRadius:18,padding:20};
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',padding:'10px 11px',border:'1px solid #ccd8c8',borderRadius:9,background:'#fff',fontSize:14};

type Point={lat:number;lng:number};
type LocalField=Record<string,any>;
type CloudPassport={id:string;field_id?:string|null;farm_name?:string|null;crop?:string|null;harvest_year?:number|null;record_data?:LocalField;boundary_geojson?:any;readiness?:{z45?:number;iscc?:number;carb?:number};status?:string;updated_at?:string};
type FileLink={id:string;passport_id:string;customer_file_id:string;evidence_type?:string;label?:string|null;shared?:boolean;customer_files?:{id:string;filename:string;mime_type?:string;size_bytes?:number;status?:string;created_at?:string}|null};
type ShareRow={id:string;passport_id:string;role:string;permissions?:Record<string,boolean>;expires_at:string;revoked_at?:string|null;created_at?:string;last_accessed_at?:string|null};
type ReviewRow={id:string;passport_id:string;reviewer_name?:string|null;organization?:string|null;review_status:string;notes?:string|null;requested_items?:string[]|null;created_at:string};
type CloudData={passports:CloudPassport[];files:FileLink[];shares:ShareRow[];reviews:ReviewRow[]};

function blankField():LocalField{return{id:'local-new',fieldId:'FIELD-001',farm:'',producer:'',countyState:'',crop:'Corn',acres:0,harvestYear:new Date().getFullYear(),landUseHistory:'',actualYield:0,benchmarkYield:0,syntheticN:0,nitrificationInhibitor:false,manure:'None',tillage:'Conventional',coverCrop:'None',nutrientPlan:false,nutrientRecords:false,gisBoundary:false,selfDeclaration:false,traceability:false,sustainabilityAttestation:false,waterSource:'Irrigation district',annualAllocationAf:0,expectedNeedAf:0,pumpingCostPerAf:0,waterQualityRisk:2,infrastructureRisk:2,premiumPerUnit:0,waterSavingsPerAcre:0,inputSavingsPerAcre:0,evidence:{yield:false,nitrogen:false,nutrient:false,land:false,gis:false,traceability:false,water:false,attestation:false}}}
function pct(done:boolean[]){return Math.round(done.filter(Boolean).length/Math.max(1,done.length)*100)}
function readiness(field:LocalField){const e=field.evidence||{};const base=[field.fieldId,field.farm,field.producer,field.countyState,field.crop,Number(field.acres)>0,field.harvestYear,field.landUseHistory].map(Boolean);return{z45:pct([...base,Number(field.actualYield)>0,Number(field.benchmarkYield)>0,Number(field.syntheticN)>=0,field.tillage,field.coverCrop,field.nutrientPlan,field.nutrientRecords,e.yield,e.nitrogen,e.nutrient].map(Boolean)),iscc:pct([...base,field.traceability,field.selfDeclaration,e.land,e.traceability].map(Boolean)),carb:pct([...base,field.gisBoundary,field.traceability,field.sustainabilityAttestation,e.gis,e.traceability,e.attestation].map(Boolean))}}
function geojson(points:Point[]){if(points.length<3)return null;return{type:'Polygon',coordinates:[[...points.map(p=>[p.lng,p.lat]),[points[0].lng,points[0].lat]]]}}
function pointsFromGeo(value:any):Point[]{const raw=value?.type==='Polygon'?value?.coordinates?.[0]:value?.type==='MultiPolygon'?value?.coordinates?.[0]?.[0]:null;if(!Array.isArray(raw))return[];const points=raw.map((p:any)=>({lng:Number(p?.[0]),lat:Number(p?.[1])})).filter((p:Point)=>Number.isFinite(p.lng)&&Number.isFinite(p.lat));if(points.length>1&&points[0].lat===points[points.length-1].lat&&points[0].lng===points[points.length-1].lng)points.pop();return points}
function bytes(value?:number){const n=Number(value||0);if(!n)return'';return n<1048576?`${Math.max(1,Math.round(n/1024))} KB`:`${(n/1048576).toFixed(1)} MB`}
function downloadJson(name:string,value:unknown){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}

function BoundaryPreview({points}:{points:Point[]}){if(points.length<3)return <div style={{padding:16,border:'1px dashed #cbd6c7',borderRadius:11,color:'#68756d'}}>Add at least three points to form the field boundary.</div>;const minLng=Math.min(...points.map(p=>p.lng)),maxLng=Math.max(...points.map(p=>p.lng)),minLat=Math.min(...points.map(p=>p.lat)),maxLat=Math.max(...points.map(p=>p.lat)),dx=Math.max(maxLng-minLng,.00001),dy=Math.max(maxLat-minLat,.00001);const polygon=points.map(p=>`${10+((p.lng-minLng)/dx)*280},${190-((p.lat-minLat)/dy)*180}`).join(' ');return <svg viewBox="0 0 300 200" style={{width:'100%',maxHeight:260,background:'#eef4ea',border:'1px solid #d7e0d3',borderRadius:11}}><polygon points={polygon} fill="#b9d8aa" stroke="#356943" strokeWidth="3"/><text x="12" y="20" fontSize="11" fill="#355342">Field boundary · {points.length} points</text></svg>}

export default function FarmPassportCloudPage(){
  const [fields,setFields]=useState<LocalField[]>([]),[selectedLocalId,setSelectedLocalId]=useState('');
  const [accessToken,setAccessToken]=useState(''),[slug,setSlug]=useState(''),[account,setAccount]=useState(''),[authReady,setAuthReady]=useState(false);
  const [cloud,setCloud]=useState<CloudData>({passports:[],files:[],shares:[],reviews:[]}),[cloudPassportId,setCloudPassportId]=useState('');
  const [boundaryPoints,setBoundaryPoints]=useState<Point[]>([]),[lat,setLat]=useState(''),[lng,setLng]=useState('');
  const [evidenceType,setEvidenceType]=useState('supporting_document'),[shareRole,setShareRole]=useState('verifier'),[shareDays,setShareDays]=useState('7'),[shareDocuments,setShareDocuments]=useState(true);
  const [lastShareUrl,setLastShareUrl]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);

  useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);const saved=raw?JSON.parse(raw):[];if(Array.isArray(saved)&&saved.length){setFields(saved);setSelectedLocalId(String(saved[0]?.id||''))}}catch{};let alive=true;const db=getBrowserClient();db.auth.getSession().then(async({data})=>{const token=data.session?.access_token||'';if(!alive)return;if(!token){setAuthReady(true);return}try{const response=await fetch('/api/customer/me',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const result=await response.json().catch(()=>({}));if(response.ok&&result?.tenant?.slug){setAccessToken(token);setSlug(result.tenant.slug);setAccount(result?.tenant?.business_name||result?.user?.first_name||'');await loadCloud(token,result.tenant.slug,alive)}}catch{}if(alive)setAuthReady(true)});return()=>{alive=false}},[]);

  const field=useMemo(()=>fields.find(f=>String(f.id)===selectedLocalId)||fields[0]||blankField(),[fields,selectedLocalId]);
  const ready=useMemo(()=>readiness(field),[field]);
  const currentPassport=useMemo(()=>cloud.passports.find(p=>p.id===cloudPassportId)||null,[cloud.passports,cloudPassportId]);
  const currentFiles=useMemo(()=>cloud.files.filter(f=>f.passport_id===cloudPassportId),[cloud.files,cloudPassportId]);
  const currentShares=useMemo(()=>cloud.shares.filter(s=>s.passport_id===cloudPassportId),[cloud.shares,cloudPassportId]);
  const currentReviews=useMemo(()=>cloud.reviews.filter(r=>r.passport_id===cloudPassportId),[cloud.reviews,cloudPassportId]);

  async function loadCloud(token=accessToken,workspace=slug,alive=true){if(!token||!workspace)return;const response=await fetch(`/api/ag/farm-passport?slug=${encodeURIComponent(workspace)}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Unable to load Farm Passport cloud.');if(alive)setCloud({passports:result.passports||[],files:result.files||[],shares:result.shares||[],reviews:result.reviews||[]})}
  async function post(body:Record<string,unknown>){const response=await fetch('/api/ag/farm-passport',{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({slug,...body})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Farm Passport action failed.');return result}
  async function refresh(){setBusy(true);setMessage('');try{await loadCloud();setMessage('Cloud records refreshed.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to refresh.')}finally{setBusy(false)}}

  function persistLocal(next:LocalField[]){setFields(next);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next))}catch{}}
  function importCloud(passport:CloudPassport){const record={...blankField(),...(passport.record_data||{})};if(!record.id||record.id==='local-new')record.id=`cloud-${passport.id}`;const id=String(record.id);const exists=fields.some(f=>String(f.id)===id);persistLocal(exists?fields.map(f=>String(f.id)===id?record:f):[...fields,record]);setSelectedLocalId(id);setCloudPassportId(passport.id);setBoundaryPoints(pointsFromGeo(passport.boundary_geojson));setLastShareUrl('');setMessage('Cloud record loaded into the on-device field editor. Open Field Passport to change production details.')}
  function chooseCloud(id:string){if(!id){setCloudPassportId('');setBoundaryPoints([]);setLastShareUrl('');return}const p=cloud.passports.find(item=>item.id===id);if(p)importCloud(p)}

  async function saveCloudRecord(){if(!accessToken||!slug)throw new Error('Sign in to save a secure cloud record.');const countyState=String(field.countyState||'');const state=countyState.includes(',')?countyState.split(',').pop()?.trim()||'':'';const result=await post({action:'save',passport:{id:cloudPassportId||undefined,producer:field.producer,farmName:field.farm,fieldId:field.fieldId,state,county:countyState,crop:field.crop,harvestYear:field.harvestYear,recordData:field,boundaryGeoJson:geojson(boundaryPoints),readiness:ready,status:'draft'}});const id=String(result?.passport?.id||cloudPassportId||'');setCloudPassportId(id);await loadCloud();setMessage('Secure cloud record saved.');return id}
  async function saveClick(){setBusy(true);setMessage('');try{await saveCloudRecord()}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}

  function addCoordinate(){const a=Number(lat),b=Number(lng);if(!Number.isFinite(a)||!Number.isFinite(b)||a<-90||a>90||b<-180||b>180){setMessage('Enter a valid latitude and longitude.');return}setBoundaryPoints(v=>[...v,{lat:a,lng:b}]);setLat('');setLng('');setMessage('Boundary point added. Save the cloud record when the polygon is complete.')}
  function addGps(){if(!navigator.geolocation){setMessage('GPS is not available in this browser.');return}setMessage('Reading your GPS position…');navigator.geolocation.getCurrentPosition(p=>{setBoundaryPoints(v=>[...v,{lat:p.coords.latitude,lng:p.coords.longitude}]);setMessage(`GPS point added (±${Math.round(p.coords.accuracy)} m).`)},e=>setMessage(e.message||'Unable to read GPS.'),{enableHighAccuracy:true,timeout:15000,maximumAge:0})}

  async function uploadEvidence(file:File){setBusy(true);setMessage('');try{let passportId=cloudPassportId;if(!passportId)passportId=await saveCloudRecord();if(!passportId)throw new Error('Save the Farm Passport first.');const prepared=await post({action:'prepare_upload',passportId,filename:file.name,mimeType:file.type||'application/octet-stream',sizeBytes:file.size,evidenceType,label:file.name,shared:true});const db=getBrowserClient();const {error}=await db.storage.from('customer-files').uploadToSignedUrl(prepared.path,prepared.token,file,{contentType:file.type||'application/octet-stream'});if(error)throw error;await post({action:'complete_upload',passportId,fileId:prepared.fileId});await loadCloud();setMessage(`${file.name} is stored privately and linked to this Farm Passport.`)}catch(e){setMessage(e instanceof Error?e.message:'Evidence upload failed.')}finally{setBusy(false)}}
  async function openEvidence(fileId:string){setBusy(true);try{const result=await post({action:'download_url',passportId:cloudPassportId,fileId});if(result.url)window.open(result.url,'_blank','noopener,noreferrer')}catch(e){setMessage(e instanceof Error?e.message:'Unable to open evidence.')}finally{setBusy(false)}}

  async function createShare(){setBusy(true);setMessage('');setLastShareUrl('');try{let passportId=cloudPassportId;if(!passportId)passportId=await saveCloudRecord();const result=await post({action:'create_share',passportId,role:shareRole,days:Number(shareDays),permissions:{record:true,review:true,boundary:true,documents:shareDocuments}});setLastShareUrl(result?.share?.url||'');await loadCloud();setMessage(`${shareRole.charAt(0).toUpperCase()+shareRole.slice(1)} access created.`)}catch(e){setMessage(e instanceof Error?e.message:'Unable to create reviewer access.')}finally{setBusy(false)}}
  async function revokeShare(shareId:string){setBusy(true);try{await post({action:'revoke_share',passportId:cloudPassportId,shareId});await loadCloud();setMessage('Temporary access revoked.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to revoke access.')}finally{setBusy(false)}}
  async function copyShare(){if(!lastShareUrl)return;try{await navigator.clipboard.writeText(lastShareUrl);setMessage('Secure review link copied.')}catch{setMessage('Copy was blocked. Press and hold the link to copy it.')}}

  async function exportFramework(framework:'45Z'|'ISCC'|'CARB'){setBusy(true);setMessage('');try{let passportId=cloudPassportId;if(!passportId)passportId=await saveCloudRecord();const result=await post({action:'package',passportId,framework});downloadJson(`aridon-${framework.toLowerCase()}-${String(field.fieldId||'field')}.json`,result.package);setMessage(`${framework} owner-review package prepared.`)}catch(e){setMessage(e instanceof Error?e.message:'Unable to prepare package.')}finally{setBusy(false)}}

  if(!authReady)return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#f4f1e8',fontFamily:'Arial,sans-serif'}}>Checking secure Farm Passport access…</main>;

  return <main style={{minHeight:'100vh',background:'#f4f1e8',color:'#17241c',fontFamily:'Arial,sans-serif',paddingBottom:60}}>
    <header style={{background:'#143d2a',color:'#fff',padding:'16px'}}><div style={{maxWidth:1180,margin:'auto',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:11,color:'#c8e2ac',fontWeight:950,letterSpacing:1}}>ARIDON AG</div><strong style={{fontSize:24}}>Farm Passport Cloud</strong></div><Link href="/ag/farm-passport" style={{color:'#fff',textDecoration:'none',fontWeight:900,display:'inline-flex',gap:6,alignItems:'center'}}><ArrowLeft size={17}/> Field Passport</Link></div></header>

    <section style={{maxWidth:1180,margin:'auto',padding:'26px 16px 16px'}}><div style={{...card,background:'#173f2c',color:'#fff',border:0}}><div style={{display:'flex',gap:8,alignItems:'center',color:'#c8e2ac',fontWeight:950,fontSize:12}}><Cloud size={22}/> OWNER-CONTROLLED COLLABORATION</div><h1 style={{fontSize:'clamp(36px,5vw,58px)',lineHeight:1,margin:'8px 0 10px'}}>Secure the record. Share only the slice they need.</h1><p style={{fontSize:17,lineHeight:1.55,color:'#dce8df',margin:0,maxWidth:850}}>Back up field records, attach receipts and photos, capture the GIS boundary, prepare framework packages, and open a temporary review room for a buyer, verifier or auditor.</p></div></section>

    <section style={{maxWidth:1180,margin:'auto',padding:'0 16px',display:'grid',gap:16}}>
      <div style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:12,fontWeight:950,color:'#356943'}}>SECURE CLOUD RECORD</div><h2 style={{fontSize:27,margin:'5px 0'}}>Local field ↔ private Aridon cloud</h2></div>{accessToken?<span style={{fontSize:12,fontWeight:900,color:'#356943',background:'#eef6e9',padding:'7px 10px',borderRadius:99}}>Signed in{account?` · ${account}`:''}</span>:<Link href="/customer/login?next=/ag/farm-passport/cloud" style={{background:'#143d2a',color:'#fff',padding:'10px 13px',borderRadius:9,textDecoration:'none',fontWeight:900}}>Sign in to cloud</Link>}</div>
        {accessToken&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:9,marginTop:13}}><label style={{fontSize:12,fontWeight:850}}>On-device field<select style={input} value={String(field.id||'')} onChange={e=>setSelectedLocalId(e.target.value)}>{fields.length?fields.map(f=><option key={String(f.id)} value={String(f.id)}>{String(f.fieldId||'Untitled')} · {String(f.crop||'Crop')}</option>):<option value="local-new">New blank field</option>}</select></label><label style={{fontSize:12,fontWeight:850}}>Cloud record<select style={input} value={cloudPassportId} onChange={e=>chooseCloud(e.target.value)}><option value="">Save current field as a new cloud record</option>{cloud.passports.map(p=><option key={p.id} value={p.id}>{p.field_id||'Untitled'} · {p.crop||'Crop'} · {p.harvest_year||'Year'}</option>)}</select></label></div>}
        {accessToken&&<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button onClick={saveClick} disabled={busy} style={{border:0,background:'#356943',color:'#fff',padding:'10px 13px',borderRadius:9,fontWeight:900,cursor:'pointer'}}>{busy?'Working…':cloudPassportId?'Save cloud changes':'Save new cloud record'}</button><button onClick={refresh} disabled={busy} style={{border:'1px solid #aab9a5',background:'#fff',color:'#356943',padding:'10px 12px',borderRadius:9,fontWeight:900,cursor:'pointer'}}><RefreshCw size={16} style={{verticalAlign:'middle',marginRight:5}}/>Refresh</button><Link href="/ag/farm-passport" style={{border:'1px solid #aab9a5',background:'#fff',color:'#356943',padding:'10px 12px',borderRadius:9,fontWeight:900,textDecoration:'none'}}>Edit field details</Link></div>}
        <div style={{marginTop:11,display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8}} className="ready-grid">{([['45Z',ready.z45],['ISCC',ready.iscc],['CARB',ready.carb]] as const).map(([name,value])=><div key={name} style={{padding:10,background:'#f7f8f3',border:'1px solid #e0e5dc',borderRadius:10}}><div style={{fontSize:11,fontWeight:900,color:'#68756d'}}>{name} READINESS</div><strong style={{fontSize:23}}>{value}%</strong></div>)}</div>
        {message&&<div style={{marginTop:10,padding:10,background:'#f6f7f2',borderRadius:9,color:'#526058',fontSize:13}}>{message}</div>}
      </div>

      {accessToken&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:16}}>
        <div style={card}><div style={{display:'flex',gap:8,alignItems:'center',color:'#356943'}}><MapPinned size={22}/><strong style={{fontSize:12}}>GIS FIELD BOUNDARY</strong></div><h2 style={{fontSize:25,margin:'6px 0 11px'}}>Walk it, drive it, or enter known coordinates.</h2><BoundaryPreview points={boundaryPoints}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:9}}><input style={input} inputMode="decimal" placeholder="Latitude" value={lat} onChange={e=>setLat(e.target.value)}/><input style={input} inputMode="decimal" placeholder="Longitude" value={lng} onChange={e=>setLng(e.target.value)}/></div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:8}}><button onClick={addCoordinate} style={{border:'1px solid #aab9a5',background:'#fff',padding:'9px 11px',borderRadius:9,fontWeight:850,cursor:'pointer'}}>Add coordinate</button><button onClick={addGps} style={{border:0,background:'#356943',color:'#fff',padding:'9px 11px',borderRadius:9,fontWeight:850,cursor:'pointer'}}>Add my GPS point</button><button onClick={()=>setBoundaryPoints([])} style={{border:'1px solid #c8b2a7',background:'#fff',padding:'9px 11px',borderRadius:9,fontWeight:850,cursor:'pointer'}}>Clear</button></div><div style={{fontSize:12,color:'#68756d',marginTop:8}}>{boundaryPoints.length>=3?`${boundaryPoints.length} points ready. Save the cloud record to store the GeoJSON polygon.`:'At least three points are required.'}</div></div>

        <div style={card}><div style={{display:'flex',gap:8,alignItems:'center',color:'#356943'}}><FileUp size={22}/><strong style={{fontSize:12}}>PRIVATE EVIDENCE</strong></div><h2 style={{fontSize:25,margin:'6px 0 11px'}}>Receipts, maps, photos and declarations.</h2><select style={input} value={evidenceType} onChange={e=>setEvidenceType(e.target.value)}><option value="supporting_document">Supporting document</option><option value="yield_record">Yield / harvest record</option><option value="nitrogen_receipt">Nitrogen / fertilizer receipt</option><option value="nutrient_log">Nutrient application log</option><option value="land_use">Land-use / eligibility proof</option><option value="gis_boundary">GIS boundary file</option><option value="traceability">Chain-of-custody / traceability</option><option value="water_record">Water / irrigation evidence</option><option value="attestation">Signed declaration / attestation</option></select><label style={{display:'block',marginTop:9,padding:12,border:'1px dashed #9fb398',borderRadius:10,textAlign:'center',fontWeight:900,cursor:'pointer',background:'#f7faf4'}}>Choose document or photo<input type="file" accept="image/*,.pdf,.csv,.txt,.doc,.docx,.xls,.xlsx" style={{display:'none'}} onChange={e=>{const file=e.target.files?.[0];if(file)uploadEvidence(file);e.currentTarget.value=''}}/></label><div style={{display:'grid',gap:7,marginTop:10}}>{currentFiles.length?currentFiles.map(f=><button key={f.id} onClick={()=>openEvidence(f.customer_file_id)} style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',textAlign:'left',padding:10,border:'1px solid #e0e5dd',borderRadius:9,background:'#fff',cursor:'pointer'}}><span><strong>{f.label||f.customer_files?.filename||'Evidence'}</strong><span style={{display:'block',fontSize:11,color:'#68756d'}}>{f.evidence_type||'supporting_document'}{f.customer_files?.size_bytes?` · ${bytes(f.customer_files.size_bytes)}`:''}</span></span><Download size={17} color="#356943"/></button>):<div style={{fontSize:12,color:'#68756d'}}>Save a cloud record, then attach evidence.</div>}</div></div>
      </div>}

      {accessToken&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:16}}>
        <div style={card}><div style={{display:'flex',gap:8,alignItems:'center',color:'#356943'}}><FileCheck2 size={22}/><strong style={{fontSize:12}}>OWNER-REVIEW PACKAGES</strong></div><h2 style={{fontSize:25,margin:'6px 0 11px'}}>Prepare the right slice for the right framework.</h2><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{(['45Z','ISCC','CARB'] as const).map(framework=><button key={framework} onClick={()=>exportFramework(framework)} disabled={busy} style={{border:'1px solid #9db292',background:'#eef6e9',color:'#285336',padding:'10px 12px',borderRadius:9,fontWeight:900,cursor:'pointer'}}>Export {framework}</button>)}</div><p style={{fontSize:12,color:'#68756d',lineHeight:1.45}}>These packages organize records and evidence for owner and reviewer use. They are not certification, tax advice or a guarantee of eligibility.</p></div>

        <div style={card}><div style={{display:'flex',gap:8,alignItems:'center',color:'#356943'}}><Link2 size={22}/><strong style={{fontSize:12}}>TEMPORARY REVIEW ROOM</strong></div><h2 style={{fontSize:25,margin:'6px 0 11px'}}>Buyer, verifier or auditor access.</h2><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><label style={{fontSize:12,fontWeight:850}}>Role<select style={input} value={shareRole} onChange={e=>setShareRole(e.target.value)}><option value="buyer">Buyer</option><option value="verifier">Verifier</option><option value="auditor">Auditor</option></select></label><label style={{fontSize:12,fontWeight:850}}>Expires<select style={input} value={shareDays} onChange={e=>setShareDays(e.target.value)}><option value="1">24 hours</option><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label></div><label style={{display:'flex',gap:7,alignItems:'center',fontSize:13,marginTop:9}}><input type="checkbox" checked={shareDocuments} onChange={e=>setShareDocuments(e.target.checked)}/>Include linked evidence documents</label><button onClick={createShare} disabled={busy} style={{marginTop:9,border:0,background:'#143d2a',color:'#fff',padding:'10px 13px',borderRadius:9,fontWeight:900,cursor:'pointer'}}>Create secure review link</button>{lastShareUrl&&<div style={{marginTop:10,padding:10,background:'#eef6e9',borderRadius:9,fontSize:12,wordBreak:'break-all'}}><strong>Copy this link now:</strong><div style={{marginTop:4}}>{lastShareUrl}</div><button onClick={copyShare} style={{marginTop:7,border:'1px solid #9db292',background:'#fff',padding:'7px 9px',borderRadius:8,fontWeight:850,cursor:'pointer'}}><Copy size={14} style={{verticalAlign:'middle',marginRight:4}}/>Copy</button></div>}</div>
      </div>}

      {accessToken&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:16}}>
        <div style={card}><div style={{display:'flex',gap:8,alignItems:'center',color:'#356943'}}><ShieldCheck size={22}/><strong style={{fontSize:12}}>ACTIVE ACCESS</strong></div><h2 style={{fontSize:25,margin:'6px 0 11px'}}>See who can still open the record.</h2><div style={{display:'grid',gap:7}}>{currentShares.length?currentShares.map(s=>{const active=!s.revoked_at&&new Date(s.expires_at).getTime()>Date.now();return <div key={s.id} style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',padding:10,border:'1px solid #e0e5dd',borderRadius:9}}><div><strong style={{textTransform:'capitalize'}}>{s.role}</strong><div style={{fontSize:11,color:'#68756d'}}>{active?'Active':'Inactive'} · expires {new Date(s.expires_at).toLocaleString()}{s.last_accessed_at?` · opened ${new Date(s.last_accessed_at).toLocaleString()}`:''}</div></div>{active&&<button onClick={()=>revokeShare(s.id)} style={{border:'1px solid #c8b2a7',background:'#fff',padding:'7px 9px',borderRadius:8,fontWeight:850,cursor:'pointer'}}>Revoke</button>}</div>}):<div style={{fontSize:12,color:'#68756d'}}>No temporary access exists for this field.</div>}</div></div>

        <div style={card}><div style={{display:'flex',gap:8,alignItems:'center',color:'#356943'}}><UserCheck size={22}/><strong style={{fontSize:12}}>REVIEWER INBOX</strong></div><h2 style={{fontSize:25,margin:'6px 0 11px'}}>Decisions and requests come back here.</h2><div style={{display:'grid',gap:8}}>{currentReviews.length?currentReviews.map(r=><div key={r.id} style={{padding:10,border:'1px solid #e0e5dd',borderRadius:9,background:'#fafaf7'}}><div style={{display:'flex',justifyContent:'space-between',gap:8,flexWrap:'wrap'}}><strong>{r.reviewer_name||'Reviewer'}{r.organization?` · ${r.organization}`:''}</strong><span style={{fontSize:11,fontWeight:900,color:'#356943',textTransform:'uppercase'}}>{r.review_status.replaceAll('_',' ')}</span></div>{r.notes&&<p style={{fontSize:13,lineHeight:1.45,margin:'7px 0 0'}}>{r.notes}</p>}{Array.isArray(r.requested_items)&&r.requested_items.length>0&&<div style={{fontSize:12,color:'#68756d',marginTop:7}}>Requested: {r.requested_items.join(', ')}</div>}<div style={{fontSize:10,color:'#859087',marginTop:7}}>{new Date(r.created_at).toLocaleString()}</div></div>):<div style={{fontSize:12,color:'#68756d'}}>No reviewer responses yet.</div>}</div></div>
      </div>}

      <div style={{...card,background:'#173f2c',color:'#fff',border:0,display:'flex',gap:10,alignItems:'flex-start'}}><ShieldCheck size={24} color="#c8e2ac"/><div><strong>Private by default</strong><div style={{fontSize:12,color:'#dce8df',lineHeight:1.5,marginTop:4}}>Farm Passport records stay tenant-scoped. Evidence uses the private customer-files bucket. Review tokens are stored as hashes, links expire, the owner can revoke access, and documents are delivered through short-lived signed URLs.</div></div></div>
    </section>

    <style jsx>{`@media(max-width:760px){.ready-grid{grid-template-columns:1fr!important}}`}</style>
  </main>
}
