'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { getBrowserClient } from '../../../lib/supabase';

type WorkspaceData = { email:string; role:string; tenant:{id:string;slug:string;business_name:string;owner_name:string|null;industry:string|null;tagline:string|null;primary_color:string|null;accent_color:string|null;plan:string|null;status:string|null;subscription_status:string|null}; projects:Array<{id:string;name:string;description?:string|null;status?:string|null}>; tasks:Array<{id:string;title:string;owner?:string|null;priority?:string|null;status?:string|null}>; knowledge:Array<{id:string;title:string;category?:string|null}> };

export default function CustomerWorkspace({ params }: { params: { slug: string } }) {
 const router=useRouter(); const [data,setData]=useState<WorkspaceData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{const db=getBrowserClient();db.auth.getSession().then(async({data:sessionData})=>{const token=sessionData.session?.access_token;if(!token){router.replace(`/customer/login?next=${encodeURIComponent(`/workspace/${params.slug}`)}`);return;}const response=await fetch(`/api/customer/workspace?slug=${encodeURIComponent(params.slug)}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const result=await response.json().catch(()=>({}));if(response.status===401||response.status===403){await db.auth.signOut();router.replace('/customer/login');return;}if(!response.ok){setError(result.error||'Unable to load this workspace.');setLoading(false);return;}setData(result as WorkspaceData);setLoading(false);});},[params.slug,router]);
 async function signOut(){await getBrowserClient().auth.signOut();router.replace('/customer/login');}
 if(loading)return <main style={loadingStyle}>Opening your company home…</main>;
 if(!data)return <main style={loadingStyle}><div style={{maxWidth:520,textAlign:'center'}}><h1>We could not open your workspace.</h1><p style={{color:'#B7C2D5'}}>{error}</p><Link href="/customer/account" style={{color:'#9EF0CF',fontWeight:900}}>Open account</Link></div></main>;
 const tenant=data.tenant,primary=tenant.primary_color||'#0B1020',accent=tenant.accent_color||'#72D6B2';const activeTasks=data.tasks.filter(t=>!['done','complete','completed','closed'].includes((t.status||'').toLowerCase()));const feedbackHref=`/customer/feedback?workspace=${encodeURIComponent(tenant.slug)}`;const isBeta=tenant.plan==='beta';
 return <main style={{minHeight:'100vh',background:primary,color:'#F8FAFC',fontFamily:'Arial, sans-serif',padding:'24px 18px 110px'}}><div style={{maxWidth:1080,margin:'0 auto'}}>
 <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,flexWrap:'wrap',marginBottom:24}}><div><div style={{fontSize:26,fontWeight:950}}>{tenant.business_name}</div><div style={{color:'#C5CEDD',marginTop:4,fontSize:13}}>Your company home</div></div><nav style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link href="/customer/start" style={navLink}>Main Room</Link><Link href="/customer/assistant" style={{...navLink,background:accent,color:'#07130F',borderColor:accent}}>Ask Eva</Link><Link href={`/workspace/${tenant.slug}/compass`} style={{...navLink,borderColor:'#F4C84A',color:'#F4C84A'}}>Compass</Link><Link href="/customer/creator" style={navLink}>Creator Studio</Link><Link href="/customer/sales" style={navLink}>Find Customers</Link>{isBeta&&<Link href="/customer/upgrade" style={{...navLink,background:'#F4D88B',color:'#241C08',borderColor:'#F4D88B'}}>Keep My Business OS</Link>}<Link href={feedbackHref} style={{...navLink,borderColor:accent,color:accent}}>Send Feedback</Link><Link href="/customer/account" style={navLink}>Account</Link><button onClick={signOut} style={navButton}>Sign out</button></nav></header>
 <section style={{background:'rgba(255,255,255,.06)',border:'1px solid rgba(255,255,255,.12)',borderRadius:22,padding:24}}><div style={{color:accent,fontSize:12,fontWeight:950}}>TODAY</div><h1 style={{fontSize:'clamp(38px,7vw,62px)',lineHeight:1,margin:'9px 0 12px'}}>{tenant.tagline||`What does ${tenant.business_name} need next?`}</h1><p style={{color:'#C8D0DE',maxWidth:800,lineHeight:1.65,fontSize:17}}>Use the executive team to run the business, Compass to evaluate opportunities, Creator Studio for marketing, and Scout to find customers. Your company information stays inside your private workspace.</p></section>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12,marginTop:16}}><HomeCard accent={accent} title="Executive Main Room" text="Talk with the Aridon executive team without changing rooms." href="/customer/start" button="Enter Main Room"/><HomeCard accent="#F4C84A" title="Aridon Compass" text="Compare opportunities, capture your preferences and build an evidence-first diligence path." href={`/workspace/${tenant.slug}/compass`} button="Open Compass"/><HomeCard accent={accent} title="Creator Studio" text="Turn one idea into reviewed multi-channel marketing drafts." href="/customer/creator" button="Create Marketing"/><HomeCard accent={accent} title="Find Customers" text="Teach Scout what you sell and research companies that may fit." href="/customer/sales" button="Open Sales"/></section>
 <section style={{marginTop:18,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:14}}><div style={panelStyle}><div style={{color:accent,fontSize:12,fontWeight:950}}>PROJECTS</div><h2>What we are working on</h2>{data.projects.length===0?<p style={mutedStyle}>No projects have been added yet.</p>:data.projects.slice(0,6).map(p=><div key={p.id} style={rowStyle}><strong>{p.name}</strong><span style={statusStyle}>{p.status||'active'}</span></div>)}</div><div style={panelStyle}><div style={{color:accent,fontSize:12,fontWeight:950}}>OPEN TASKS</div><h2>What still needs attention</h2>{activeTasks.length===0?<p style={mutedStyle}>No open tasks are waiting right now.</p>:activeTasks.slice(0,8).map(t=><div key={t.id} style={rowStyle}><strong>{t.title}</strong><span style={statusStyle}>{t.priority||'medium'}</span></div>)}</div></section>
 </div></main>;
}
function HomeCard({accent,title,text,href,button}:{accent:string;title:string;text:string;href:string;button:string}){return <article style={panelStyle}><div style={{color:accent,fontWeight:950,fontSize:22}}>{title}</div><p style={{color:'#C8D0DE',lineHeight:1.6,minHeight:76}}>{text}</p><Link href={href} style={{display:'inline-block',background:accent,color:'#07130F',borderRadius:10,padding:'10px 13px',textDecoration:'none',fontWeight:950}}>{button}</Link></article>}
const loadingStyle={minHeight:'100vh',background:'#0B1020',color:'#F8FAFC',display:'grid',placeItems:'center',padding:24,fontFamily:'Arial, sans-serif'};const navLink={border:'1px solid rgba(255,255,255,.2)',color:'#F8FAFC',borderRadius:10,padding:'9px 12px',fontSize:13,fontWeight:850,textDecoration:'none'};const navButton={...navLink,background:'transparent',cursor:'pointer'};const panelStyle={background:'rgba(255,255,255,.05)',border:'1px solid rgba(255,255,255,.11)',borderRadius:16,padding:18};const rowStyle={display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',borderTop:'1px solid rgba(255,255,255,.08)',padding:'11px 0'};const statusStyle={color:'#AEB9CB',fontSize:12};const mutedStyle={color:'#AEB9CB',lineHeight:1.6};
