'use client';

import Link from 'next/link';
import { useState } from 'react';

const card:React.CSSProperties={background:'#0D1728',border:'1px solid #263958',borderRadius:15,padding:16};
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#08111F',border:'1px solid #30435F',borderRadius:9,color:'#F8FAFC',padding:'9px 10px'};
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)||0);
export default function DecisionSupportPage({params}:{params:{id:string}}){
 const [financing,setFinancing]=useState({purchase_price:0,buyer_cash:0,seller_note:0,earnout:0,normalized_free_cash_flow:0,annual_debt_service:0,requested_sba_loan:0,operating_business_eligible:true});
 const [allocation,setAllocation]=useState({purchase_price:0,cash_and_receivables:0,inventory:0,equipment:0,real_estate:0,identifiable_intangibles:0,noncompete:0,goodwill:0,other:0});
 const [risk,setRisk]=useState({escrow_holdback_pct:0,indemnity_cap_pct:0,survival_months:18,rwi_readiness:25});
 const [result,setResult]=useState<any>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function run(){setBusy(true);setMessage('Running…');try{const r=await fetch(`/api/acquisitions/${params.id}/decision-support`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({financing,allocation,risk_transfer:risk})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to run.');setResult(p);setMessage('Decision support refreshed.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to run.');}finally{setBusy(false);}}
 const fields=(obj:any,setter:any,spec:[string,string,string?][])=> <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:9}}>{spec.map(([k,l,u])=><label key={k} style={{fontSize:13,color:'#C6D1DF'}}>{l}{u?<span style={{color:'#7D90A9'}}> · {u}</span>:null}<input type="number" style={{...input,marginTop:5}} value={obj[k]||''} onChange={e=>setter((v:any)=>({...v,[k]:Number(e.target.value)||0}))}/></label>)}</div>;
 return <main style={{minHeight:'100vh',background:'#07101D',color:'#F8FAFC',fontFamily:'Arial,sans-serif',padding:'24px 18px 70px'}}><div style={{maxWidth:1150,margin:'0 auto'}}>
  <nav style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><strong>ARIDON 3 · CAPITAL & GOVERNANCE</strong><div style={{display:'flex',gap:14}}><Link href={`/acquisitions/${params.id}`} style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>Deal Workspace</Link><Link href={`/acquisitions/${params.id}/underwriting`} style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>Underwriting</Link></div></nav>
  <header style={{padding:'42px 0 20px'}}><div style={{color:'#9EF0CF',fontSize:12,fontWeight:950}}>FINANCE IT · ALLOCATE IT · PROTECT IT · GOVERN IT</div><h1 style={{fontSize:'clamp(38px,6vw,64px)',lineHeight:1,margin:'8px 0 12px'}}>Finish the deal structure without pretending the calculator is the lender, CPA or attorney.</h1><p style={{color:'#AEBBD0',fontSize:17,lineHeight:1.6,maxWidth:900}}>This page screens financing paths, checks purchase-price allocation math, lays out the post-close governance cadence, and flags risk-transfer terms that need legal review.</p></header>
  <section style={{...card,marginBottom:12}}><h2 style={{marginTop:0}}>Capital stack & preliminary financing lanes</h2>{fields(financing,setFinancing,[['purchase_price','Purchase price','$'],['buyer_cash','Buyer cash','$'],['seller_note','Seller note','$'],['earnout','Earnout','$'],['normalized_free_cash_flow','Normalized free cash flow','$'],['annual_debt_service','Annual debt service','$'],['requested_sba_loan','Requested SBA loan','$']])}<label style={{display:'flex',gap:8,alignItems:'center',marginTop:10,color:'#C6D1DF'}}><input type="checkbox" checked={financing.operating_business_eligible} onChange={e=>setFinancing(v=>({...v,operating_business_eligible:e.target.checked}))}/> Operating business appears preliminarily eligible for an SBA loan category. This is not an eligibility determination.</label></section>
  <section style={{...card,marginBottom:12}}><h2 style={{marginTop:0}}>Purchase-price allocation consistency check</h2>{fields(allocation,setAllocation,[['purchase_price','Purchase price','$'],['cash_and_receivables','Cash / receivables','$'],['inventory','Inventory','$'],['equipment','Equipment / fixed assets','$'],['real_estate','Real estate','$'],['identifiable_intangibles','Identifiable intangibles','$'],['noncompete','Non-compete / covenant','$'],['goodwill','Goodwill','$'],['other','Other','$']])}<p style={{color:'#8EA0B7',fontSize:13}}>Aridon only checks that entered allocations reconcile to total consideration. Tax treatment belongs with qualified tax counsel/CPA.</p></section>
  <section style={{...card,marginBottom:12}}><h2 style={{marginTop:0}}>Risk-transfer terms</h2>{fields(risk,setRisk,[['escrow_holdback_pct','Escrow / holdback','%'],['indemnity_cap_pct','Indemnity cap','%'],['survival_months','Representation survival','months'],['rwi_readiness','R&W insurance readiness','%']])}</section>
  <button onClick={run} disabled={busy} style={{border:0,borderRadius:10,padding:'12px 17px',background:'#9EF0CF',color:'#07101D',fontWeight:950,cursor:'pointer'}}>{busy?'Running…':'Run Capital + Governance Review'}</button>{message?<div style={{color:'#BDD0E5',margin:'10px 0'}}>{message}</div>:null}
  {result?<div style={{display:'grid',gap:12,marginTop:15}}><section style={card}><h2 style={{marginTop:0}}>Financing paths</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:9}}>{result.financing.map((x:any)=><div key={x.name} style={{border:'1px solid #2B3F5E',borderRadius:11,padding:12}}><strong>{x.name}</strong><div style={{color:'#9EF0CF',fontWeight:950,margin:'6px 0'}}>{String(x.preliminary_fit).toUpperCase()}</div><div style={{color:'#B5C1D2',lineHeight:1.5,fontSize:13}}>{x.reason}<br/>Lender need: {money(x.lender_need)}{x.dscr?` · DSCR ${x.dscr.toFixed(2)}x`:''}</div><div style={{color:'#7F91AA',fontSize:12,marginTop:7}}>{x.approval_note}</div></div>)}</div></section>
   <section style={card}><h2 style={{marginTop:0}}>Allocation check</h2><div style={{fontSize:24,fontWeight:950,color:result.allocation.balanced?'#9EF0CF':'#FFD19A'}}>{result.allocation.balanced?'Balanced':'Needs reconciliation'}</div><p style={{color:'#B5C1D2'}}>Allocated {money(result.allocation.allocated)} against {money(result.allocation.purchase_price)} purchase price. Gap: {money(result.allocation.total_gap)}.</p><div style={{color:'#8294AD',fontSize:12}}>{result.allocation.advisor_note}</div></section>
   <section style={card}><h2 style={{marginTop:0}}>Governance cadence</h2><div style={{display:'grid',gap:9}}>{result.governance.map((g:any)=><div key={g.cadence} style={{borderTop:'1px solid #243653',paddingTop:8}}><strong>{g.cadence}</strong><div style={{color:'#9AAAC0',fontSize:13,marginTop:3}}>{g.owner} · {g.focus}</div></div>)}</div></section>
   <section style={card}><h2 style={{marginTop:0}}>Risk-transfer flags</h2>{result.risk_transfer.flags.length?<ul>{result.risk_transfer.flags.map((f:string)=><li key={f} style={{marginBottom:7}}>{f}</li>)}</ul>:<p style={{color:'#9EF0CF'}}>No basic structure gap from the entered risk-transfer fields.</p>}<div style={{color:'#8294AD',fontSize:12}}>{result.risk_transfer.legal_note}</div></section>
  </div>:null}
 </div></main>;
}
