'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {ArrowLeft,BadgeDollarSign,Building2,Calculator,Search,Sprout,Truck} from 'lucide-react';
type Buyer={name:string;type:string;products:string[];region:string;minVolume:number;unit:string;indicativePrice:number;terms:string};
const buyers:Buyer[]=[
{name:'Regional Food Distributor',type:'Wholesale distributor',products:['beef','produce','corn'],region:'Southwest',minVolume:1000,unit:'lb',indicativePrice:4.85,terms:'Recurring / spot'},
{name:'Institutional Food Buyer',type:'Schools, hospitals & institutions',products:['beef','produce'],region:'New Mexico + Arizona',minVolume:500,unit:'lb',indicativePrice:5.05,terms:'Contract / bid'},
{name:'Feed & Grain Buyer',type:'Processor / feed market',products:['corn','wheat','grain'],region:'Four Corners',minVolume:5000,unit:'bu',indicativePrice:5.2,terms:'Spot / forward'},
{name:'Local Restaurant Group',type:'Foodservice',products:['beef','produce'],region:'Regional',minVolume:200,unit:'lb',indicativePrice:6.15,terms:'Recurring'}];
export default function BuyerMarketEngine(){
const [product,setProduct]=useState('beef'),[volume,setVolume]=useState(1200),[cost,setCost]=useState(3.35),[freight,setFreight]=useState(.22);
const matches=useMemo(()=>buyers.filter(x=>x.products.includes(product.toLowerCase())).map(x=>({...x,net:x.indicativePrice-freight,margin:x.indicativePrice-freight-cost,fit:volume>=x.minVolume?'Volume fits':'Aggregate supply'})),[product,volume,cost,freight]);
return <main style={{minHeight:'100vh',background:'#f4f1e8',color:'#18251d',fontFamily:'Arial,sans-serif',padding:'24px 18px 70px'}}><div style={{maxWidth:1120,margin:'auto'}}>
<nav style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><Link href="/ag" style={{color:'#356943',fontWeight:900,textDecoration:'none'}}><ArrowLeft size={16}/> Aridon Ag</Link><strong>BUYER & MARKET ENGINE</strong></nav>
<header style={{padding:'46px 0 24px'}}><div style={{color:'#356943',fontWeight:950,fontSize:12}}>DEMAND → BUYER → ECONOMICS → OFFTAKE → FINANCE</div><h1 style={{fontSize:'clamp(42px,7vw,76px)',lineHeight:.95,letterSpacing:-3,margin:'10px 0 18px'}}>Find the buyer before the crop leaves the farm.</h1><p style={{fontSize:19,lineHeight:1.6,maxWidth:850,color:'#526058'}}>Match available production to buyer demand, compare net-to-farm economics and turn qualified interest into an owner-approved sales and financing workflow. Buyer records below are starter market archetypes until verified live buyer data is connected.</p></header>
<section style={{background:'#fff',border:'1px solid #d8e1d5',borderRadius:20,padding:22,display:'grid',gap:14}}><h2 style={{margin:0}}>What do you have to sell?</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}>
<label>Product<input value={product} onChange={e=>setProduct(e.target.value)} style={input}/></label><label>Available volume<input type="number" value={volume} onChange={e=>setVolume(+e.target.value)} style={input}/></label><label>Production cost / unit<input type="number" step=".01" value={cost} onChange={e=>setCost(+e.target.value)} style={input}/></label><label>Freight / unit<input type="number" step=".01" value={freight} onChange={e=>setFreight(+e.target.value)} style={input}/></label></div></section>
<section style={{padding:'28px 0'}}><div style={{display:'flex',gap:9,alignItems:'center'}}><Search color="#356943"/><h2>Buyer matches</h2></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:12}}>{matches.map(x=><article key={x.name} style={card}><Building2 color="#356943"/><h3>{x.name}</h3><p>{x.type} · {x.region}</p><p><b>{x.fit}</b> · minimum {x.minVolume.toLocaleString()} {x.unit}</p><p>Indicative gross: <b>{'$'+x.indicativePrice.toFixed(2)}</b> / unit</p><p>Estimated net to farm: <b>{'$'+x.net.toFixed(2)}</b></p><p>Margin after entered cost: <b>{'$'+x.margin.toFixed(2)}</b> / unit</p><p>{x.terms}</p><button style={button}>Build buyer offer</button></article>)}</div></section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}><article style={card}><Sprout color="#356943"/><h2>What should I grow?</h2><p>Work backward from buyer demand, specifications, timing, water and expected margin before planting.</p></article><article style={card}><Calculator color="#356943"/><h2>Profit per acre</h2><p>Compare gross price with production, freight, storage, processing and financing costs.</p></article><article style={card}><Truck color="#356943"/><h2>Aggregate supply</h2><p>Combine participating farms when one operation cannot meet a buyer's volume requirement.</p></article><article style={card}><BadgeDollarSign color="#356943"/><h2>Offtake → financing</h2><p>Carry an approved LOI or contract into Farm Freedom and capital-fit workflows as buyer evidence.</p></article></section>
</div></main>}
const input:React.CSSProperties={display:'block',width:'100%',boxSizing:'border-box',marginTop:6,padding:'12px 10px',border:'1px solid #cbd7c7',borderRadius:10,fontSize:16,background:'#fff'};
const card:React.CSSProperties={background:'#fff',border:'1px solid #d8e1d5',borderRadius:18,padding:20,lineHeight:1.5};
const button:React.CSSProperties={background:'#163d2a',color:'#fff',border:0,borderRadius:10,padding:'11px 13px',fontWeight:900};