import Link from 'next/link';

export const metadata = {
  title: 'Aridon Sentinel Privacy',
  description: 'Privacy and data handling information for Aridon Sentinel Grid and the Aridon Sentinel ChatGPT app.',
};

export default function SentinelPrivacyPage() {
  const card: React.CSSProperties = {
    border: '1px solid #24445b', borderRadius: 18, padding: 20,
    background: 'linear-gradient(180deg,#0d1c2a,#08131e)', marginBottom: 14,
  };
  return (
    <main style={{ minHeight: '100vh', background: '#06101b', color: '#f7fafc', fontFamily: 'Arial,sans-serif' }}>
      <div style={{ maxWidth: 900, margin: '0 auto', padding: '42px 18px 70px' }}>
        <Link href="/sentinel-grid" style={{ color: '#8cf0d0', textDecoration: 'none', fontWeight: 900 }}>← Aridon Sentinel Grid</Link>
        <div style={{ color: '#8cf0d0', fontWeight: 950, letterSpacing: 1.3, fontSize: 12, marginTop: 34 }}>ARIDON SENTINEL</div>
        <h1 style={{ fontSize: 'clamp(42px,7vw,72px)', lineHeight: .95, margin: '10px 0 18px' }}>Privacy & Data Handling</h1>
        <p style={{ color: '#9eb0c3', lineHeight: 1.7, fontSize: 17 }}>Effective September 2026. This notice covers the Aridon Sentinel Grid service and its ChatGPT/MCP integration.</p>

        <section style={card}>
          <h2>What Sentinel processes</h2>
          <p style={{ color: '#b8c6d5', lineHeight: 1.7 }}>Sentinel may process prompt text, recent conversation context supplied to it, descriptions of proposed tool actions, authorization context, and minimized risk signals supplied by participating AI systems. Sentinel uses that information to produce a defensive risk score, reasons, trajectory indicators, and a recommended pre-action gate.</p>
        </section>
        <section style={card}>
          <h2>Data minimization</h2>
          <p style={{ color: '#b8c6d5', lineHeight: 1.7 }}>The Sentinel design favors keeping raw prompts with the originating provider whenever possible. Cross-provider collaboration should use minimized threat indicators, scores, technique tags, confidence values, and confirmed campaign fingerprints rather than sharing full user conversations.</p>
        </section>
        <section style={card}>
          <h2>Storage and training</h2>
          <p style={{ color: '#b8c6d5', lineHeight: 1.7 }}>The current public Sentinel MCP endpoint performs stateless assessments and does not intentionally create a persistent Sentinel user profile from tool calls. Standard infrastructure, hosting, security, and application logs may still be generated by service providers for reliability, abuse prevention, and debugging. Aridon does not represent Sentinel assessments as a separate model-training dataset unless a future version clearly discloses and obtains any required permissions for such use.</p>
        </section>
        <section style={card}>
          <h2>Safety boundaries</h2>
          <p style={{ color: '#b8c6d5', lineHeight: 1.7 }}>Sentinel is defensive decision support. It does not grant authorization to access systems, guarantee that an action is safe, replace the host platform's safety controls, or replace human review for consequential decisions. A low risk score is not an approval to proceed with otherwise unauthorized activity.</p>
        </section>
        <section style={card}>
          <h2>Third parties</h2>
          <p style={{ color: '#b8c6d5', lineHeight: 1.7 }}>When Sentinel is used through ChatGPT or another MCP client, information is also handled under that platform's terms and privacy practices. Hosting and security providers may process technical request data needed to operate the service.</p>
        </section>
        <section style={card}>
          <h2>Changes and contact</h2>
          <p style={{ color: '#b8c6d5', lineHeight: 1.7 }}>Aridon may update this notice as Sentinel moves from prototype to production. Material changes should be reflected on this page. Business, privacy, security, and partnership inquiries can be directed through Aridon's published business contact channels.</p>
        </section>
        <p style={{ color: '#6f859b', fontSize: 12, lineHeight: 1.6 }}>Prototype notice: Sentinel Grid remains an evolving security system. Organizations should independently validate its controls, retention settings, authentication, monitoring, and incident-response procedures before production deployment.</p>
      </div>
    </main>
  );
}
