'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

type Workspace={lead:any;score:any;structures:any[];diligence:any[];lois:any[];timeline:any[];tasks:any[]};
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)||0);
const card:React.CSSProperties={background:'#0D1728',border:'1px solid #263958',borderRadius:15,padding:16};
const stages=['lead_captured','reviewing','qualified','contact_strategy_ready','negotiating','loi_drafted','loi_sent','diligence','final_approval','closed','lost'];
export default function DealPage({params}:{params:{id:string}}){
 const [data,setData]=useState<Workspace|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch(`/api/acquisitions/${params.id}`,{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load deal.');setData(p);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load deal.');}}
 useEffect(()=>{load();},[params.id]);
 async function stage(value:string){setBusy(true);try{const r=await fetch('/api/acquisitions/pipeline',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:params.id,stage:value})});if(!r.ok)throw new Error('Stage update failed.');await load();}catch(e){setError(e instanceof Error?e.message:'Stage update failed.');}finally{setBusy(false);}}
 if(!data)return <main style={{minHeight:'100vh',background:'#07101D',color:'#F8FAFC',padding:30,fontFamily:'Arial,sans-serif'}}>{error||'Loading acquisition workspace…'}</main>;
 const l=data.lead;const done=data.diligence.filter(x=>x.status==='done').length;
 return <main style={{minHeight:'100vh',background:'#07101D',color:'#F8FAFC',fontFamily:'Arial,sans-serif',padding:'24px 18px 70px'}}><div style={{maxWidth:1200,margin:'0 auto'}}>
  <nav style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><strong>ARIDON 3 · DEAL WORKSPACE</strong><div style={{display:'flex',gap:14,flexWrap:'wrap'}}><Link href="/acquisitions/pipeline" style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>Pipeline</Link><Link href={`/acquisitions/${params.id}/underwriting`} style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>Underwriting Lab</Link><Link href={`/acquisitions/${params.id}/decision-support`} style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>Capital + Governance</Link></div></nav>
  <header style={{padding:'42px 0 20px'}}><div style={{color:'#9EF0CF',fontSize:12,fontWeight:950}}>ACTIVE ACQUISITION</div><h1 style={{fontSize:'clamp(40px,6vw,66px)',lineHeight:1,margin:'8px 0 10px'}}>{l.business_name}</h1><p style={{color:'#AEBBD0',fontSize:17}}>{[l.industry,l.city,l.state].filter(Boolean).join(' · ')||'Deal details still being collected'}</p></header>
  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10,marginBottom:14}}>{[['Acquisition Score',data.score?.overall_score??'—'],['Thesis Fit',l.thesis_fit_score?`${l.thesis_fit_score}/100`:'—'],['Recommendation',data.score?.recommendation??'unscored'],['Asking Price',l.asking_price?money(l.asking_price):'—'],['EBITDA / SDE',l.estimated_ebitda?money(l.estimated_ebitda):'—'],['Diligence',`${done}/${data.diligence.length}`],['LOIs',data.lois.length]].map(([k,v])=><div key={String(k)} style={card}><div style={{color:'#7E90A9',fontSize:11,fontWeight:900}}>{k}</div><div style={{fontSize:22,fontWeight:950,marginTop:5}}>{v}</div></div>)}</section>
  <section style={{...card,marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'center'}}><div><h2 style={{margin:'0 0 5px'}}>Pipeline stage</h2><div style={{color:'#9AAAC0'}}>{l.stage}</div></div><select disabled={busy} value={l.stage} onChange={e=>stage(e.target.value)} style={{background:'#08111F',color:'#F8FAFC',border:'1px solid #30435F',borderRadius:9,padding:'10px 12px'}}>{stages.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></div></section>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:14}}>
   <section style={card}><h2 style={{marginTop:0}}>Underwrite before negotiating harder</h2><p style={{color:'#B7C3D4',lineHeight:1.6}}>Test sustainable earnings, owner dependence, customers, working capital, financing, comps, disruption, regulation, cyber/technology, people, tax readiness, risk transfer and evidence confidence.</p><Link href={`/acquisitions/${params.id}/underwriting`} style={{display:'inline-block',background:'#9EF0CF',color:'#07101D',fontWeight:950,textDecoration:'none',borderRadius:9,padding:'10px 13px'}}>Open Underwriting Lab</Link></section>
   <section style={card}><h2 style={{marginTop:0}}>Finish the capital stack</h2><p style={{color:'#B7C3D4',lineHeight:1.6}}>Screen SBA/conventional/seller-finance paths, reconcile purchase-price allocation math, define governance cadence and flag risk-transfer gaps.</p><Link href={`/acquisitions/${params.id}/decision-support`} style={{display:'inline-block',border:'1px solid #486080',color:'#E8F0FA',fontWeight:950,textDecoration:'none',borderRadius:9,padding:'10px 13px'}}>Open Capital + Governance</Link></section>
   <section style={card}><h2 style={{marginTop:0}}>Seller intelligence</h2><div style={{color:'#B7C3D4',lineHeight:1.6}}><strong>Reason for sale:</strong> {l.reason_for_sale||'Unknown'}<br/><strong>Seller priorities:</strong> {l.seller_priorities||'Unknown'}<br/><strong>Seller-finance willingness:</strong> {l.seller_finance_willingness??'—'}%</div></section>
  </div>
  <section style={{...card,marginTop:14}}><h2 style={{marginTop:0}}>Deal structures</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:10}}>{data.structures.map((s:any)=><div key={s.id||s.structure_name} style={{border:'1px solid #2B3E5C',borderRadius:12,padding:12}}><strong>{s.structure_name}</strong><div style={{fontSize:20,fontWeight:950,color:'#9EF0CF',margin:'6px 0'}}>{money(s.purchase_price)}</div><div style={{color:'#AAB7C9',fontSize:13,lineHeight:1.55}}>Cash {money(s.down_payment)}<br/>Seller note {money(s.seller_note)}<br/>Earnout {money(s.earnout)}<br/>Funding gap {money(s.funding_gap)}</div></div>)}</div></section>
  <section style={{...card,marginTop:14}}><h2 style={{marginTop:0}}>Recent deal history</h2><div style={{display:'grid',gap:8}}>{data.timeline.slice(0,12).map((t:any)=><div key={t.id} style={{borderBottom:'1px solid #20314A',paddingBottom:8}}><strong>{t.event_title}</strong><div style={{color:'#8FA0B8',fontSize:13,marginTop:3}}>{t.event_detail}</div></div>)}</div></section>
  {error?<div style={{color:'#FFB4B4',marginTop:12}}>{error}</div>:null}
 </div></main>;
}
