import Link from 'next/link';
import { acquisitionWorkflow, activeAcquisitions, capitalSources } from '../../../../lib/acquisitionCommand';

export default function AcquisitionCommandPage({ params }: { params: { slug: string } }) {
  return (
    <main style={page}><div style={shell}>
      <header style={header}>
        <div><div style={eyebrow}>ARIDON · ACQUISITION COMMAND</div><h1 style={h1}>Buy businesses with structure, not bravado.</h1><p style={lead}>Acquisition Command screens opportunities, verifies cash flow, routes capital, builds seller-financing structures, stress-tests debt service, and keeps human approval at every consequential step.</p></div>
        <div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link href={`/workspace/${params.slug}/mission-control`} style={outline}>Mission Control</Link><Link href={`/workspace/${params.slug}/executive-suite`} style={mint}>Executive Suite</Link></div>
      </header>

      <section style={twoCol}>
        <article style={panel}><div style={label}>ACTIVE DEAL</div><h2 style={h2}>{activeAcquisitions[0].name}</h2><div style={metrics}><div><strong>${activeAcquisitions[0].askingPrice.toLocaleString()}</strong><span>Asking price</span></div><div><strong>${activeAcquisitions[0].advertisedCashFlow.toLocaleString()}</strong><span>Advertised cash flow</span></div></div><p style={copy}>{activeAcquisitions[0].structureGoal}</p><p style={muted}>{activeAcquisitions[0].status}</p><h3>Next actions</h3><ol style={list}>{activeAcquisitions[0].nextActions.map((item)=><li key={item}>{item}</li>)}</ol></article>
        <article style={{...panel,background:'#0D1728',color:'#fff'}}><div style={{...label,color:'#9EF0CF'}}>DEAL DISCIPLINE</div><h2 style={h2}>No-money-down is a structure goal, not an excuse to ignore risk.</h2><p style={copy}>Aridon should optimize for low buyer cash while preserving working capital, realistic debt coverage, seller alignment, clean collateral, and an exit if diligence breaks the thesis.</p><div style={chips}><span style={chip}>Seller carry</span><span style={chip}>Senior debt</span><span style={chip}>Equipment collateral</span><span style={chip}>Earnout</span><span style={chip}>Standby note</span></div></article>
      </section>

      <section style={panel}><div style={label}>CAPITAL ROUTER</div><h2 style={h2}>Permanent financing sources</h2>{capitalSources.map((source)=><div key={source.id} style={sourceCard}><div><strong style={{fontSize:20}}>{source.name}</strong><div style={muted}>{source.category}</div></div><div style={status}>{source.status.toUpperCase()}</div><p style={{gridColumn:'1 / -1',margin:'6px 0'}}>{source.notes}</p><div style={{gridColumn:'1 / -1'}}><b>Programs:</b> {source.programs.join(' · ')}</div><div style={{gridColumn:'1 / -1'}}><b>Submission:</b> {source.submission}</div></div>)}</section>

      <section style={{...panel,marginTop:14}}><div style={label}>ACQUISITION LOOP</div><h2 style={h2}>From listing to ownership</h2><div style={workflow}>{acquisitionWorkflow.map((step,index)=><div key={step} style={stepCard}><span style={stepNum}>{index+1}</span><span>{step}</span></div>)}</div></section>
    </div></main>
  );
}

const page={minHeight:'100vh',background:'#07101D',color:'#F7FAFC',fontFamily:'Arial,sans-serif',padding:'28px 20px 72px'};const shell={maxWidth:1200,margin:'0 auto'};const header={display:'flex',justifyContent:'space-between',gap:20,alignItems:'start',flexWrap:'wrap' as const,marginBottom:22};const eyebrow={color:'#9EF0CF',fontSize:12,fontWeight:950,letterSpacing:1};const h1={fontSize:'clamp(42px,6vw,70px)',lineHeight:.98,letterSpacing:-2.5,margin:'10px 0 14px',maxWidth:850};const lead={color:'#B9C5D6',fontSize:18,lineHeight:1.6,maxWidth:850,margin:0};const twoCol={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(340px,1fr))',gap:14,marginBottom:14};const panel={background:'#F6F3EB',color:'#171717',borderRadius:18,padding:20,border:'1px solid #D7D0C3'};const label={fontSize:11,fontWeight:950,letterSpacing:1};const h2={fontSize:27,margin:'8px 0 15px'};const metrics={display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:14};const copy={fontSize:17,lineHeight:1.65};const muted={color:'#6A645D',fontSize:13,lineHeight:1.55};const list={lineHeight:1.7,paddingLeft:20};const chips={display:'flex',gap:8,flexWrap:'wrap' as const,marginTop:14};const chip={background:'#19314A',border:'1px solid #34506A',borderRadius:999,padding:'7px 10px',fontSize:12};const sourceCard={display:'grid',gridTemplateColumns:'1fr auto',gap:8,border:'1px solid #D9D1C4',background:'#fff',borderRadius:13,padding:15,marginTop:10};const status={background:'#E4F4ED',color:'#174D3E',borderRadius:999,padding:'6px 9px',fontSize:11,fontWeight:900,height:'fit-content'};const workflow={display:'grid',gap:8};const stepCard={display:'flex',gap:10,alignItems:'center',background:'#fff',border:'1px solid #D9D1C4',borderRadius:11,padding:11};const stepNum={width:28,height:28,borderRadius:999,display:'grid',placeItems:'center',background:'#0C5D49',color:'#fff',fontWeight:900,fontSize:12};const mint={background:'#9EF0CF',color:'#07130F',padding:'12px 16px',borderRadius:11,textDecoration:'none',fontWeight:950};const outline={border:'1px solid #52627A',color:'#F7FAFC',padding:'11px 15px',borderRadius:11,textDecoration:'none',fontWeight:900};
