import Link from 'next/link';

const BUSINESS_CHECKOUT='https://buy.stripe.com/6oU8wOaDR1aHbfUd464AU06';
const mint='#9EF0CF';
const card={background:'#0D1728',border:'1px solid #2A3A57',borderRadius:20,padding:26} as const;

export default function SubscribePage(){return <main style={{minHeight:'100vh',background:'#07101D',color:'#F8FAFC',fontFamily:'Arial,sans-serif'}}>
<section style={{maxWidth:1080,margin:'0 auto',padding:'32px 20px 72px'}}>
<nav style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><Link href="/" style={{color:'#fff',textDecoration:'none',fontWeight:950}}>ARIDON</Link><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link href="/install" style={{color:'#D8E2EF',textDecoration:'none',fontWeight:900}}>Install App</Link><Link href="/analyze-business" style={{color:'#07130F',background:mint,textDecoration:'none',fontWeight:950,padding:'11px 14px',borderRadius:10}}>Analyze Free First</Link></div></nav>
<div style={{paddingTop:66,maxWidth:930}}><div style={{color:mint,fontSize:12,fontWeight:950,letterSpacing:1}}>ARIDON FOR BUSINESS</div><h1 style={{fontSize:'clamp(48px,7vw,78px)',lineHeight:.96,letterSpacing:-3,margin:'12px 0 18px'}}>Start at $198. Move up when your company needs more firepower.</h1><p style={{color:'#B8C4D5',fontSize:20,lineHeight:1.65,maxWidth:850}}>Essentials makes the core Aridon company operating system affordable to smaller businesses. Aridon Business keeps the deeper automation, growth and revenue-recovery capacity at $497/month.</p></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:14,marginTop:30}}>
<section style={{...card,borderColor:'#5DAA8B'}}><div style={{color:mint,fontSize:12,fontWeight:950}}>MOST ACCESSIBLE</div><div style={{display:'flex',alignItems:'baseline',gap:8,flexWrap:'wrap'}}><strong style={{fontSize:58}}>$198</strong><span style={{fontSize:18}}>/ month</span></div><h2>Aridon Essentials</h2><ul style={{lineHeight:1.9,color:'#D5DEEA',paddingLeft:20}}><li>1 private company workspace</li><li>Core AI executive support</li><li>Company Brain</li><li>Projects and tasks</li><li>Business analysis and research</li><li>Owner-approved execution controls</li><li>Installable app access</li></ul><Link href="/business-os/checkout?plan=essentials" style={{display:'inline-block',background:mint,color:'#07130F',textDecoration:'none',fontWeight:950,padding:'14px 18px',borderRadius:12}}>Start Essentials at $198/month</Link></section>
<section style={card}><div style={{color:'#B9CFFF',fontSize:12,fontWeight:950}}>FULL BUSINESS SYSTEM</div><div style={{display:'flex',alignItems:'baseline',gap:8,flexWrap:'wrap'}}><strong style={{fontSize:58}}>$497</strong><span style={{fontSize:18}}>/ month</span></div><h2>Aridon Business</h2><ul style={{lineHeight:1.9,color:'#D5DEEA',paddingLeft:20}}><li>AI executive analysis and decision support</li><li>Growth and revenue-recovery workflows</li><li>Company context, projects and tasks</li><li>Research and prioritized recommendations</li><li>Broader automation and operating capacity</li><li>Owner-approved execution path</li><li>Installable app access</li></ul><a href={BUSINESS_CHECKOUT} target="_blank" rel="noreferrer" style={{display:'inline-block',background:'#fff',color:'#07101D',textDecoration:'none',fontWeight:950,padding:'14px 18px',borderRadius:12}}>Start Aridon Business at $497/month</a></section>
</div>
<section style={{background:'#F4F1E9',color:'#171717',borderRadius:20,padding:26,marginTop:16}}><div style={{fontSize:12,fontWeight:950}}>WANT PROOF FIRST?</div><h2 style={{fontSize:32,margin:'9px 0'}}>Test Aridon before paying.</h2><p style={{color:'#5D5A54',fontSize:17,lineHeight:1.6}}>Run the free website analysis, review public proof, or explore the installable-app experience first.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link href="/analyze-business" style={{background:'#171717',color:'#fff',textDecoration:'none',fontWeight:950,padding:'13px 16px',borderRadius:11}}>Analyze My Business Free</Link><Link href="/install" style={{border:'1px solid #777067',color:'#171717',textDecoration:'none',fontWeight:900,padding:'12px 16px',borderRadius:11}}>See the Installable App</Link><Link href="/business-os/proof" style={{color:'#171717',fontWeight:850,padding:'12px 4px'}}>View Public Proof</Link></div></section>
<div style={{marginTop:30,color:'#8998AE',fontSize:12}}>No revenue guarantee. Review <Link href="/business-os/terms" style={{color:'#C9D6E8'}}>terms</Link> and <Link href="/business-os/privacy" style={{color:'#C9D6E8'}}>privacy</Link> before purchase.</div>
</section></main>}
