import Link from 'next/link';

const CHECKOUT_URL='https://buy.stripe.com/6oU8wOaDR1aHbfUd464AU06';
const mint='#9EF0CF';

export default function SubscribePage(){return <main style={{minHeight:'100vh',background:'#07101D',color:'#F8FAFC',fontFamily:'Arial,sans-serif'}}>
<section style={{maxWidth:980,margin:'0 auto',padding:'32px 20px 72px'}}>
<nav style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><Link href="/" style={{color:'#fff',textDecoration:'none',fontWeight:950}}>ARIDON</Link><Link href="/analyze-business" style={{color:'#07130F',background:mint,textDecoration:'none',fontWeight:950,padding:'11px 14px',borderRadius:10}}>Analyze Free First</Link></nav>
<div style={{paddingTop:68,maxWidth:900}}><div style={{color:mint,fontSize:12,fontWeight:950,letterSpacing:1}}>ARIDON FOUNDING SUBSCRIPTION</div><h1 style={{fontSize:'clamp(48px,7vw,78px)',lineHeight:.96,letterSpacing:-3,margin:'12px 0 18px'}}>Keep an AI executive team working on your business for $497/month.</h1><p style={{color:'#B8C4D5',fontSize:20,lineHeight:1.65,maxWidth:820}}>Use Aridon for business analysis, decision support, growth and revenue-recovery work, company context, projects, tasks, research and owner-approved execution. Start only when the value is clear enough to justify the subscription.</p></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:14,marginTop:30}}>
<section style={{background:'#0D1728',border:'1px solid #2A3A57',borderRadius:20,padding:26}}><div style={{display:'flex',alignItems:'baseline',gap:8,flexWrap:'wrap'}}><strong style={{fontSize:58}}>$497</strong><span style={{fontSize:18}}>/ month</span></div><ul style={{lineHeight:1.9,color:'#D5DEEA',paddingLeft:20}}><li>AI executive analysis and decision support</li><li>Growth and revenue-recovery workflows</li><li>Company context, projects and tasks</li><li>Research and prioritized recommendations</li><li>Owner-approved execution path</li><li>Cancel anytime</li></ul><a href={CHECKOUT_URL} target="_blank" rel="noreferrer" style={{display:'inline-block',background:mint,color:'#07130F',textDecoration:'none',fontWeight:950,padding:'14px 18px',borderRadius:12}}>Start Aridon at $497/month</a><p style={{color:'#8998AE',fontSize:12,lineHeight:1.5}}>No revenue guarantee. Starting a subscription is an explicit owner decision.</p></section>
<section style={{background:'#F4F1E9',color:'#171717',borderRadius:20,padding:26}}><div style={{fontSize:12,fontWeight:950}}>WANT PROOF FIRST?</div><h2 style={{fontSize:32,margin:'9px 0'}}>Test Aridon before paying.</h2><p style={{color:'#5D5A54',fontSize:17,lineHeight:1.6}}>Run a free analysis on your own website. Eligible New Mexico and Arizona plumbing/HVAC businesses can also request the focused 14-day Revenue Recovery Pilot.</p><div style={{display:'grid',gap:10}}><Link href="/analyze-business" style={{background:'#171717',color:'#fff',textDecoration:'none',fontWeight:950,padding:'13px 16px',borderRadius:11,textAlign:'center'}}>Analyze My Business Free</Link><Link href="/business-os/revenue-recovery" style={{border:'1px solid #777067',color:'#171717',textDecoration:'none',fontWeight:900,padding:'12px 16px',borderRadius:11,textAlign:'center'}}>See the 14-Day Pilot</Link><Link href="/business-os/proof" style={{color:'#171717',textDecoration:'underline',fontWeight:850,textAlign:'center'}}>View Public Proof</Link></div></section>
</div>
<div style={{marginTop:30,color:'#8998AE',fontSize:12}}>Review <Link href="/business-os/terms" style={{color:'#C9D6E8'}}>terms</Link> and <Link href="/business-os/privacy" style={{color:'#C9D6E8'}}>privacy</Link> before purchase.</div>
</section></main>}
