import Link from 'next/link';
import InstallAridon from '../../components/InstallAridon';

export default function AgInstall(){return <main style={{minHeight:'100vh',background:'#0a533e',color:'#fff',fontFamily:'Arial,sans-serif'}}><section style={{maxWidth:980,margin:'auto',padding:'34px 20px 80px'}}>
<nav style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><Link href="/ag" style={{color:'#fff',textDecoration:'none',fontWeight:950}}>ARIDON AG</Link><Link href="/ag/app" style={{color:'#b9ee91',textDecoration:'none',fontWeight:900}}>Open Farm App</Link></nav>
<div style={{paddingTop:58,maxWidth:860}}><div style={{fontSize:12,fontWeight:950,color:'#b9ee91',letterSpacing:1}}>ARIDON AG MOBILE</div><h1 style={{fontSize:'clamp(46px,8vw,80px)',lineHeight:.96,margin:'12px 0 18px'}}>Put your farm operating system in your pocket.</h1><p style={{fontSize:20,lineHeight:1.65,color:'#dcebe3'}}>Install Aridon Ag on a supported phone, tablet or computer. It opens like an app, launches directly into the farm command center and keeps the same web-based account available across devices.</p></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:14,marginTop:28}}>
<section style={{background:'#fff',color:'#183b4e',borderRadius:20,padding:26}}><div style={{fontSize:12,fontWeight:950,color:'#2e7d32'}}>INSTALL ON THIS DEVICE</div><h2 style={{fontSize:34,margin:'8px 0 12px'}}>Aridon Ag</h2><p style={{color:'#607284',lineHeight:1.65}}>Use the install button below where supported. On iPhone/iPad, use Safari's Share menu and choose <strong>Add to Home Screen</strong>. On Android/Chrome, choose <strong>Install app</strong> or <strong>Add to Home screen</strong>.</p><InstallAridon /></section>
<section style={{background:'#123c31',border:'1px solid #4c806d',borderRadius:20,padding:26}}><div style={{fontSize:12,fontWeight:950,color:'#b9ee91'}}>FIELD USE</div><h2 style={{fontSize:34,margin:'8px 0 12px'}}>Built for quick checks</h2><ul style={{lineHeight:1.9,paddingLeft:20,color:'#deeee7'}}><li>Daily farm priorities</li><li>Buyer and sales follow-up</li><li>Crop and field profitability</li><li>Payroll and overtime alerts</li><li>Inventory and equipment checks</li><li>Water and drought resilience</li><li>AI Farm Advisor actions</li></ul></section>
</div>
<section style={{marginTop:16,background:'#eaf5e7',color:'#183b4e',borderRadius:20,padding:24}}><h2 style={{fontSize:30,marginTop:0}}>One farm account. Phone, tablet and desktop.</h2><p style={{color:'#52677a',lineHeight:1.65}}>The install is a Progressive Web App (PWA), so farmers can use Aridon Ag in a dedicated app window without waiting for an app-store download. A native iOS/Android wrapper can be added later for app-store distribution while keeping the same Aridon Ag web core.</p><Link href="/ag/app" style={{display:'inline-block',background:'#0a533e',color:'#fff',textDecoration:'none',fontWeight:950,padding:'13px 16px',borderRadius:11}}>Open Farm Command Center</Link></section>
</section></main>}
