'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ClipboardList, Droplets, FlaskConical, Gauge, Leaf, Plus, Sprout, Thermometer, TimerReset, Wheat } from 'lucide-react';

type Payload={facilities:any[];facility:any|null;zones:any[];activities:any[];harvests:any[];tasks:any[];alerts:any[];summary:any};
const panel:React.CSSProperties={background:'#fff',border:'1px solid #dce8df',borderRadius:18,padding:18};
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',border:'1px solid #cddbd0',borderRadius:9,padding:'9px 10px',background:'#fbfdfb',color:'#183b4e'};
const button:React.CSSProperties={border:0,borderRadius:9,padding:'10px 13px',background:'#0a533e',color:'#fff',fontWeight:900,cursor:'pointer'};
const emptyReading={air_temp_f:'',humidity_pct:'',co2_ppm:'',ppfd_umol_m2_s:'',dli_mol_m2_day:'',root_zone_temp_f:'',substrate_moisture_pct:'',ph:'',ec_ms_cm:'',irrigation_gallons:'',runoff_pct:'',dissolved_oxygen_mg_l:'',notes:''};
const activityTypes=['scouting','irrigation','fertigation','fertilizer','pruning','trellising','pollination','transplant','seeding','sanitation','biocontrol','pest_disease','maintenance','other'];
const stages=['planning','germination','seedling','vegetative','flowering','fruiting','harvest','turnover'];

export default function GreenhousePage(){
 const [data,setData]=useState<Payload|null>(null);const [facilityId,setFacilityId]=useState('');const [zoneId,setZoneId]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const [facility,setFacility]=useState({name:'',location:'',structure_type:'greenhouse',area_sqft:'',growing_system:'mixed',notes:''});
 const [zone,setZone]=useState({name:'',crop:'Tomato',variety:'',growth_stage:'planning',planting_date:'',target_harvest_date:'',plant_count:'',area_sqft:'',growing_system:'hydroponic',substrate:'',irrigation_method:'drip',notes:''});
 const [reading,setReading]=useState<any>(emptyReading);
 const [activity,setActivity]=useState({activity_type:'scouting',product_or_material:'',quantity:'',unit:'',labor_hours:'',cost:'',scout_result:'',notes:''});
 const [harvest,setHarvest]=useState({harvest_date:new Date().toISOString().slice(0,10),marketable_lb:'',cull_lb:'',units_harvested:'',unit_name:'lb',sale_price_per_unit:'',revenue:'',labor_hours:'',notes:''});
 const [task,setTask]=useState({title:'',task_type:'crop',priority:'medium',due_at:'',assigned_to:'',notes:''});

 async function load(id=''){
  try{const r=await fetch(`/api/ag/greenhouse${id?`?facility_id=${encodeURIComponent(id)}`:''}`,{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load greenhouse.');setData(p);const resolved=id||p.facility?.id||'';setFacilityId(resolved);if(p.zones?.length&&!p.zones.some((z:any)=>z.id===zoneId))setZoneId(p.zones[0].id);setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load greenhouse.');}
 }
 useEffect(()=>{load();},[]);
 async function save(action:string,payload:any,after?:()=>void){setBusy(true);setMessage('Saving…');try{const r=await fetch('/api/ag/greenhouse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to save.');if(action==='facility')setFacilityId(p.id);after?.();await load(action==='facility'?p.id:facilityId);setMessage('Saved.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 async function patch(kind:string,id:string,payload:any){setBusy(true);try{const r=await fetch('/api/ag/greenhouse',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,id,...payload})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Update failed.');await load(facilityId);}catch(e){setMessage(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}}
 const selectedZone=useMemo(()=>data?.zones?.find((z:any)=>z.id===zoneId)||data?.zones?.[0]||null,[data,zoneId]);
 const zoneName=(id:string)=>data?.zones.find((z:any)=>z.id===id)?.name||'Whole greenhouse';
 const summary=data?.summary||{};
 return <main style={{minHeight:'100vh',background:'#eef4ee',color:'#183b4e',fontFamily:'Arial,sans-serif',paddingBottom:80}}>
  <header style={{background:'#073d31',color:'#fff',padding:'18px 18px 22px',position:'sticky',top:0,zIndex:12,boxShadow:'0 4px 16px #173b2a24'}}><div style={{maxWidth:1250,margin:'auto',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:12,fontWeight:950,color:'#b9ee91',letterSpacing:1}}>ARIDON AG · CONTROLLED ENVIRONMENT</div><strong style={{fontSize:24}}>Greenhouse Growing OS</strong></div><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Link href="/ag/app" style={{color:'#fff',textDecoration:'none',fontWeight:850}}>Farm Command Center</Link><Link href="/ag" style={{color:'#b9ee91',textDecoration:'none',fontWeight:900}}>Aridon Ag</Link></div></div></header>
  <section style={{maxWidth:1250,margin:'auto',padding:'26px 18px'}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'end',flexWrap:'wrap'}}><div><div style={{fontSize:12,fontWeight:950,color:'#2e7d32'}}>GROW LIKE A FARMER, MEASURE LIKE A GREENHOUSE</div><h1 style={{fontSize:'clamp(38px,6vw,64px)',lineHeight:1,margin:'7px 0 10px'}}>Track the crop from seed to sale.</h1><p style={{maxWidth:870,color:'#607284',fontSize:17,lineHeight:1.6,margin:0}}>Record climate, light, water, root-zone conditions, pH, EC, labor, crop work, scouting, harvest and revenue by greenhouse and growing zone. Crop target ranges are editable starter presets, not agronomic prescriptions.</p></div>{data?.facilities?.length?<label style={{minWidth:260,fontWeight:800}}>Greenhouse<select style={{...input,marginTop:6}} value={facilityId} onChange={e=>{setFacilityId(e.target.value);load(e.target.value)}}>{data.facilities.map((f:any)=><option key={f.id} value={f.id}>{f.name}{f.location?` · ${f.location}`:''}</option>)}</select></label>:null}</div>
   {message?<div style={{marginTop:12,padding:11,borderRadius:10,background:'#f7fbf5',border:'1px solid #d6e5d3',color:'#516978'}}>{message}</div>:null}

   {!data?.facility?<section style={{...panel,marginTop:18,maxWidth:800}}><h2 style={{marginTop:0}}>Set up the first greenhouse</h2><p style={{color:'#607284'}}>Create the structure first. Then add bays, benches or crop zones and start the daily grow log.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10}}><Field label="Greenhouse name" value={facility.name} onChange={v=>setFacility(x=>({...x,name:v}))}/><Field label="Location" value={facility.location} onChange={v=>setFacility(x=>({...x,location:v}))}/><Field label="Area sq ft" type="number" value={facility.area_sqft} onChange={v=>setFacility(x=>({...x,area_sqft:v}))}/><label>Growing system<select style={{...input,marginTop:5}} value={facility.growing_system} onChange={e=>setFacility(x=>({...x,growing_system:e.target.value}))}><option>mixed</option><option>soil</option><option>hydroponic</option><option>aeroponic</option><option>substrate</option></select></label></div><button disabled={busy} style={{...button,marginTop:12}} onClick={()=>save('facility',facility,()=>setFacility({name:'',location:'',structure_type:'greenhouse',area_sqft:'',growing_system:'mixed',notes:''}))}>Create Greenhouse</button></section>:null}

   {data?.facility?<>
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(165px,1fr))',gap:10,marginTop:18}}><Metric icon={<Gauge/>} label="Crop Health" value={`${summary.health??0}/100`} sub="Across active zones"/><Metric icon={<Sprout/>} label="Growing Zones" value={String(summary.zones??0)} sub={`${summary.plants??0} plants tracked`}/><Metric icon={<AlertTriangle/>} label="Active Alerts" value={String(summary.activeAlerts??0)} sub={`${summary.criticalAlerts??0} critical`}/><Metric icon={<Droplets/>} label="Water 24h" value={`${Number(summary.irrigationGallons24h||0).toLocaleString()} gal`} sub="Recorded irrigation"/><Metric icon={<Wheat/>} label="Harvest 30d" value={`${Number(summary.marketableLb30d||0).toLocaleString()} lb`} sub="Marketable yield"/><Metric icon={<TimerReset/>} label="Labor 30d" value={`${Number(summary.laborHours30d||0).toLocaleString()} hr`} sub={`Inputs $${Number(summary.inputCost30d||0).toLocaleString()}`}/></section>

    <div style={{display:'grid',gridTemplateColumns:'minmax(0,1.35fr) minmax(300px,.65fr)',gap:14,marginTop:14}}>
     <section style={panel}><div style={{display:'flex',alignItems:'center',gap:9}}><AlertTriangle color="#b45f06"/><div><div style={{fontSize:12,fontWeight:950,color:'#b45f06'}}>GROWER ATTENTION</div><h2 style={{margin:'2px 0'}}>What needs attention now?</h2></div></div>{data.alerts.length?<div style={{display:'grid',gap:8,marginTop:12}}>{data.alerts.slice(0,12).map((a:any,i:number)=><div key={`${a.zone_id}-${a.parameter}-${i}`} style={{padding:11,borderRadius:10,background:a.level==='critical'?'#fff0ef':'#fff8e8',border:`1px solid ${a.level==='critical'?'#efc0bb':'#ead6a5'}`}}><strong>{a.zone_name} · {a.level.toUpperCase()}</strong><div style={{color:'#607284',fontSize:13,marginTop:3}}>{a.message}</div></div>)}</div>:<p style={{color:'#2e7d32',fontWeight:850}}>No out-of-range conditions are showing from the latest entries.</p>}</section>
     <section style={{...panel,background:'#0d314c',color:'#fff'}}><Leaf color="#b9ee91"/><div style={{fontSize:12,fontWeight:950,color:'#b9ee91',marginTop:8}}>DAILY GROWER RHYTHM</div><h2 style={{fontSize:29,margin:'5px 0 10px'}}>Walk it like a field.</h2><ol style={{lineHeight:1.8,color:'#d7e5ee',paddingLeft:20}}><li>Check climate and root zone.</li><li>Log irrigation, EC and pH.</li><li>Scout leaves, flowers and fruit.</li><li>Record labor and materials.</li><li>Log harvest and culls.</li><li>Close tasks before the next cycle.</li></ol></section>
    </div>

    <h2 style={{fontSize:30,margin:'26px 0 10px'}}>Growing zones</h2>
    {data.zones.length?<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10}}>{data.zones.map((z:any)=><button key={z.id} onClick={()=>setZoneId(z.id)} style={{...panel,textAlign:'left',cursor:'pointer',borderColor:zoneId===z.id?'#0a533e':'#dce8df',background:zoneId===z.id?'#f4fbf2':'#fff'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong style={{fontSize:19}}>{z.name}</strong><span style={{fontWeight:950,color:z.health_score>=80?'#2e7d32':z.health_score>=60?'#9a6700':'#b42318'}}>{z.health_score}/100</span></div><div style={{color:'#607284',marginTop:4}}>{[z.crop,z.variety,z.growth_stage].filter(Boolean).join(' · ')}</div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:5,marginTop:10,fontSize:13}}><span>🌡 {z.latest_reading?.air_temp_f??'—'} °F</span><span>💧 {z.latest_reading?.humidity_pct??'—'}% RH</span><span>🧪 pH {z.latest_reading?.ph??'—'}</span><span>⚡ EC {z.latest_reading?.ec_ms_cm??'—'}</span></div><div style={{fontSize:12,color:'#7c8c99',marginTop:8}}>{z.plant_count} plants · {z.area_sqft} sq ft · {z.alerts.length} alerts</div></button>)}</section>:<div style={{...panel,color:'#607284'}}>No zones yet. Add a crop zone below.</div>}

    {selectedZone?<div style={{display:'grid',gridTemplateColumns:'minmax(0,1.4fr) minmax(290px,.6fr)',gap:14,marginTop:16}}>
     <section style={panel}><div style={{display:'flex',gap:9,alignItems:'center'}}><Thermometer color="#2e7d32"/><div><div style={{fontSize:12,fontWeight:950,color:'#2e7d32'}}>QUICK CROP READING</div><h2 style={{margin:'2px 0'}}>Log {selectedZone.name}</h2></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:9,marginTop:12}}>{[
      ['air_temp_f','Air temp °F'],['humidity_pct','Humidity %'],['co2_ppm','CO₂ ppm'],['ppfd_umol_m2_s','PPFD'],['dli_mol_m2_day','DLI'],['root_zone_temp_f','Root temp °F'],['substrate_moisture_pct','Moisture %'],['ph','pH'],['ec_ms_cm','EC mS/cm'],['irrigation_gallons','Irrigation gal'],['runoff_pct','Runoff %'],['dissolved_oxygen_mg_l','DO mg/L']
     ].map(([k,l])=><Field key={k} label={l} type="number" value={reading[k]} onChange={v=>setReading((x:any)=>({...x,[k]:v}))}/>)}</div><Field label="Crop notes" value={reading.notes} onChange={v=>setReading((x:any)=>({...x,notes:v}))}/><button disabled={busy} style={{...button,marginTop:10}} onClick={()=>save('reading',{facility_id:facilityId,zone_id:selectedZone.id,...reading},()=>setReading(emptyReading))}>Save Crop Reading</button></section>
     <section style={panel}><div style={{display:'flex',gap:8,alignItems:'center'}}><FlaskConical color="#2e7d32"/><h2 style={{margin:0}}>Target window</h2></div><p style={{fontSize:12,color:'#607284'}}>Starter ranges for {selectedZone.crop||'this crop'}. Adjust to cultivar, growth stage, climate strategy and your agronomist/seed supplier guidance.</p><div style={{display:'grid',gap:7}}>{Object.entries(selectedZone.target_profile||{}).map(([k,v]:any)=><div key={k} style={{display:'flex',justifyContent:'space-between',gap:10,borderBottom:'1px solid #edf2ed',paddingBottom:6}}><span>{v.label}</span><strong>{v.min}–{v.max}{v.unit}</strong></div>)}</div><label style={{display:'block',marginTop:12,fontWeight:800}}>Growth stage<select style={{...input,marginTop:5}} value={selectedZone.growth_stage} onChange={e=>patch('zone',selectedZone.id,{growth_stage:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label></section>
    </div>:null}

    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:14,marginTop:16}}>
     <section style={panel}><ClipboardList color="#2e7d32"/><h2>Farm-style crop log</h2><p style={{color:'#607284',fontSize:13}}>Record scouting, fertilizer/fertigation, pruning, pollination, sanitation, pest/disease observations, maintenance and labor.</p><ZoneSelect data={data} value={zoneId} onChange={setZoneId}/><label>Activity type<select style={{...input,marginTop:5}} value={activity.activity_type} onChange={e=>setActivity(x=>({...x,activity_type:e.target.value}))}>{activityTypes.map(x=><option key={x}>{x}</option>)}</select></label><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8,marginTop:8}}><Field label="Material / product" value={activity.product_or_material} onChange={v=>setActivity(x=>({...x,product_or_material:v}))}/><Field label="Quantity" type="number" value={activity.quantity} onChange={v=>setActivity(x=>({...x,quantity:v}))}/><Field label="Unit" value={activity.unit} onChange={v=>setActivity(x=>({...x,unit:v}))}/><Field label="Labor hours" type="number" value={activity.labor_hours} onChange={v=>setActivity(x=>({...x,labor_hours:v}))}/><Field label="Cost $" type="number" value={activity.cost} onChange={v=>setActivity(x=>({...x,cost:v}))}/></div><Field label="Scouting result" value={activity.scout_result} onChange={v=>setActivity(x=>({...x,scout_result:v}))}/><Field label="Notes" value={activity.notes} onChange={v=>setActivity(x=>({...x,notes:v}))}/><button disabled={busy} style={{...button,marginTop:9}} onClick={()=>save('activity',{facility_id:facilityId,zone_id:zoneId,...activity},()=>setActivity({activity_type:'scouting',product_or_material:'',quantity:'',unit:'',labor_hours:'',cost:'',scout_result:'',notes:''}))}>Add Crop Activity</button></section>

     <section style={panel}><Wheat color="#2e7d32"/><h2>Harvest & yield</h2><ZoneSelect data={data} value={zoneId} onChange={setZoneId}/><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8}}><Field label="Harvest date" type="date" value={harvest.harvest_date} onChange={v=>setHarvest(x=>({...x,harvest_date:v}))}/><Field label="Marketable lb" type="number" value={harvest.marketable_lb} onChange={v=>setHarvest(x=>({...x,marketable_lb:v}))}/><Field label="Cull lb" type="number" value={harvest.cull_lb} onChange={v=>setHarvest(x=>({...x,cull_lb:v}))}/><Field label="Units harvested" type="number" value={harvest.units_harvested} onChange={v=>setHarvest(x=>({...x,units_harvested:v}))}/><Field label="Unit name" value={harvest.unit_name} onChange={v=>setHarvest(x=>({...x,unit_name:v}))}/><Field label="Price / unit $" type="number" value={harvest.sale_price_per_unit} onChange={v=>setHarvest(x=>({...x,sale_price_per_unit:v}))}/><Field label="Revenue $" type="number" value={harvest.revenue} onChange={v=>setHarvest(x=>({...x,revenue:v}))}/><Field label="Harvest labor hr" type="number" value={harvest.labor_hours} onChange={v=>setHarvest(x=>({...x,labor_hours:v}))}/></div><Field label="Harvest notes" value={harvest.notes} onChange={v=>setHarvest(x=>({...x,notes:v}))}/><button disabled={busy||!zoneId} style={{...button,marginTop:9}} onClick={()=>save('harvest',{facility_id:facilityId,zone_id:zoneId,...harvest},()=>setHarvest({harvest_date:new Date().toISOString().slice(0,10),marketable_lb:'',cull_lb:'',units_harvested:'',unit_name:'lb',sale_price_per_unit:'',revenue:'',labor_hours:'',notes:''}))}>Record Harvest</button></section>

     <section style={panel}><TimerReset color="#2e7d32"/><h2>Grower tasks</h2><ZoneSelect data={data} value={zoneId} onChange={setZoneId}/><Field label="Task" value={task.title} onChange={v=>setTask(x=>({...x,title:v}))}/><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8}}><label>Type<select style={{...input,marginTop:5}} value={task.task_type} onChange={e=>setTask(x=>({...x,task_type:e.target.value}))}>{['crop','irrigation','scouting','nutrition','harvest','maintenance','sanitation','sales'].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select style={{...input,marginTop:5}} value={task.priority} onChange={e=>setTask(x=>({...x,priority:e.target.value}))}>{['low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Due" type="datetime-local" value={task.due_at} onChange={v=>setTask(x=>({...x,due_at:v}))}/><Field label="Assigned to" value={task.assigned_to} onChange={v=>setTask(x=>({...x,assigned_to:v}))}/></div><Field label="Notes" value={task.notes} onChange={v=>setTask(x=>({...x,notes:v}))}/><button disabled={busy} style={{...button,marginTop:9}} onClick={()=>save('task',{facility_id:facilityId,zone_id:zoneId,...task},()=>setTask({title:'',task_type:'crop',priority:'medium',due_at:'',assigned_to:'',notes:''}))}>Add Task</button><div style={{display:'grid',gap:7,marginTop:12}}>{data.tasks.slice(0,10).map((t:any)=><div key={t.id} style={{borderTop:'1px solid #e6ede7',paddingTop:8}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong>{t.title}</strong><span style={{fontSize:11,fontWeight:900,color:t.priority==='critical'?'#b42318':t.priority==='high'?'#9a6700':'#607284'}}>{t.priority.toUpperCase()}</span></div><div style={{fontSize:12,color:'#607284',margin:'3px 0'}}>{zoneName(t.zone_id)}{t.due_at?` · due ${new Date(t.due_at).toLocaleString()}`:''}</div><select value={t.status} onChange={e=>patch('task',t.id,{status:e.target.value})} style={{...input,padding:'6px 8px',fontSize:12}}><option>open</option><option>in_progress</option><option>blocked</option><option>done</option></select></div>)}</div></section>
    </div>

    <section style={{...panel,marginTop:16}}><h2 style={{marginTop:0}}>Add a growing zone</h2><p style={{color:'#607284',fontSize:13}}>Use a zone for a bay, bench, house section, hydroponic loop or any crop block managed together.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(165px,1fr))',gap:8}}><Field label="Zone / bay name" value={zone.name} onChange={v=>setZone(x=>({...x,name:v}))}/><Field label="Crop" value={zone.crop} onChange={v=>setZone(x=>({...x,crop:v}))}/><Field label="Variety" value={zone.variety} onChange={v=>setZone(x=>({...x,variety:v}))}/><label>Growth stage<select style={{...input,marginTop:5}} value={zone.growth_stage} onChange={e=>setZone(x=>({...x,growth_stage:e.target.value}))}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><Field label="Planting date" type="date" value={zone.planting_date} onChange={v=>setZone(x=>({...x,planting_date:v}))}/><Field label="Target harvest" type="date" value={zone.target_harvest_date} onChange={v=>setZone(x=>({...x,target_harvest_date:v}))}/><Field label="Plant count" type="number" value={zone.plant_count} onChange={v=>setZone(x=>({...x,plant_count:v}))}/><Field label="Area sq ft" type="number" value={zone.area_sqft} onChange={v=>setZone(x=>({...x,area_sqft:v}))}/><label>Growing system<select style={{...input,marginTop:5}} value={zone.growing_system} onChange={e=>setZone(x=>({...x,growing_system:e.target.value}))}><option>soil</option><option>hydroponic</option><option>substrate</option><option>aeroponic</option><option>mixed</option></select></label><Field label="Substrate" value={zone.substrate} onChange={v=>setZone(x=>({...x,substrate:v}))}/><Field label="Irrigation" value={zone.irrigation_method} onChange={v=>setZone(x=>({...x,irrigation_method:v}))}/></div><Field label="Zone notes" value={zone.notes} onChange={v=>setZone(x=>({...x,notes:v}))}/><button disabled={busy} style={{...button,marginTop:10}} onClick={()=>save('zone',{facility_id:facilityId,...zone},()=>setZone({name:'',crop:'Tomato',variety:'',growth_stage:'planning',planting_date:'',target_harvest_date:'',plant_count:'',area_sqft:'',growing_system:'hydroponic',substrate:'',irrigation_method:'drip',notes:''}))}><Plus size={15} style={{verticalAlign:'middle',marginRight:5}}/>Add Growing Zone</button></section>

    <section style={{...panel,marginTop:16}}><h2 style={{marginTop:0}}>Recent farm records</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(290px,1fr))',gap:14}}><div><h3>Crop activities</h3>{data.activities.slice(0,12).map((a:any)=><div key={a.id} style={{padding:'8px 0',borderBottom:'1px solid #e6ede7'}}><strong>{a.activity_type} · {zoneName(a.zone_id)}</strong><div style={{fontSize:12,color:'#607284'}}>{new Date(a.activity_date).toLocaleString()} · {a.labor_hours||0} hr · ${Number(a.cost||0).toLocaleString()}</div><div style={{fontSize:13,marginTop:2}}>{a.scout_result||a.notes||a.product_or_material||'Recorded'}</div></div>)}</div><div><h3>Harvests</h3>{data.harvests.slice(0,12).map((h:any)=><div key={h.id} style={{padding:'8px 0',borderBottom:'1px solid #e6ede7'}}><strong>{zoneName(h.zone_id)} · {h.marketable_lb} lb marketable</strong><div style={{fontSize:12,color:'#607284'}}>{h.harvest_date} · {h.cull_lb} lb cull · ${Number(h.revenue||0).toLocaleString()} revenue</div></div>)}</div></div></section>
   </>:null}
  </section>
 </main>
}

function Metric({icon,label,value,sub}:{icon:React.ReactNode;label:string;value:string;sub:string}){return <section style={panel}><div style={{display:'flex',justifyContent:'space-between',color:'#2e7d32'}}><span>{icon}</span><span style={{fontSize:11,fontWeight:900,color:'#607284'}}>{label.toUpperCase()}</span></div><div style={{fontSize:28,fontWeight:950,margin:'7px 0 3px'}}>{value}</div><div style={{fontSize:12,color:'#607284'}}>{sub}</div></section>}
function Field({label,value,onChange,type='text'}:{label:string;value:any;onChange:(v:string)=>void;type?:string}){return <label style={{display:'block',fontSize:13,fontWeight:750,marginTop:7}}>{label}<input type={type} step={type==='number'?'any':undefined} style={{...input,marginTop:5}} value={value??''} onChange={e=>onChange(e.target.value)}/></label>}
function ZoneSelect({data,value,onChange}:{data:Payload;value:string;onChange:(v:string)=>void}){return <label style={{display:'block',fontSize:13,fontWeight:800,marginBottom:8}}>Crop zone<select style={{...input,marginTop:5}} value={value} onChange={e=>onChange(e.target.value)}><option value="">Whole greenhouse</option>{data.zones.map((z:any)=><option key={z.id} value={z.id}>{z.name} · {z.crop}</option>)}</select></label>}
