'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Boxes, Code2, History, LogOut, Megaphone, PackageCheck, Plus, Printer, ShieldCheck, Truck, Users, WandSparkles } from 'lucide-react';
import { getBrowserClient } from '../../../../lib/supabase';

type Membership={tenant_id:string;role:string};
type Grain={id:string;grain:string;quantity:number;unit:string;storage_location:string;source_company:string;notes:string};
type Pickup={id:string;source_company:string;contact_name:string;contact_phone:string;grain:string;quantity:number;unit:string;pickup_address:string;pickup_date:string|null;driver:string;destination:string;status:string;notes:string};
type Workshop={id:string;title:string;event_date:string|null;event_time:string;location:string;audience:string;goal:string;talking_points:string;sponsor_ask:string;flyer_body:string;status:string};
type Module={id:string;name:string;description:string;fields:string[]};
type Offer={id:string;company_name:string;contact_name:string;grain:string;quantity:number;unit:string;pickup_address:string;ready_date:string|null;status:string};
type Audit={id:number;action:string;entity_type:string;detail:any;created_at:string};
type Version={id:string;module_id:string;module_name:string;version_no:number;change_type:string;created_at:string};

const blankWorkshop={title:'Small Farm Resilience Workshop',event_date:'',event_time:'',location:'',audience:'Small farms and ranches',goal:'Help producers organize records, find funding, improve water/feed decisions, and leave with one clear next action.',talking_points:'Welcome and producer needs; records and paperwork; water/feed decisions; grants and loans; one next action per producer.',sponsor_ask:'Sponsor lunch, printing, producer travel, workshop space, or technical expertise.',flyer_body:'Practical help for small farms and ranches. Bring your questions and leave with one clear next action.',status:'draft'};

export default function S3PilotPage(){
 const db=useMemo(()=>getBrowserClient(),[]);
 const [session,setSession]=useState<any>(null); const [membership,setMembership]=useState<Membership|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('');
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [pilotCode,setPilotCode]=useState('');
 const [grains,setGrains]=useState<Grain[]>([]); const [pickups,setPickups]=useState<Pickup[]>([]); const [workshops,setWorkshops]=useState<Workshop[]>([]); const [modules,setModules]=useState<Module[]>([]); const [offers,setOffers]=useState<Offer[]>([]); const [audit,setAudit]=useState<Audit[]>([]); const [versions,setVersions]=useState<Version[]>([]);
 const [grainForm,setGrainForm]=useState({grain:'Corn',quantity:'',unit:'bushels',storage_location:'S3 storage',source_company:'',notes:''});
 const [pickupForm,setPickupForm]=useState({source_company:'',contact_name:'',contact_phone:'',grain:'',quantity:'',unit:'bushels',pickup_address:'',pickup_date:'',driver:'',destination:'S3 Legacy Ranch',status:'requested',notes:''});
 const [workshop,setWorkshop]=useState(blankWorkshop); const [moduleForm,setModuleForm]=useState({name:'',description:'',fields:''});

 useEffect(()=>{ db.auth.getSession().then(({data})=>{setSession(data.session||null); if(data.session) resolveMembership(data.session.access_token); else setLoading(false)}); const {data:s}=db.auth.onAuthStateChange((_e,x)=>setSession(x)); return()=>s.subscription.unsubscribe(); },[db]);
 async function resolveMembership(token:string){ setLoading(true); const r=await fetch('/api/customer/me',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'}); const j=await r.json().catch(()=>({})); if(r.ok&&j.tenant?.slug==='s3-legacy-ranch'){setMembership({tenant_id:j.tenant.id,role:j.membership?.role||'member'}); await loadAll(j.tenant.id);} else setMembership(null); setLoading(false); }
 async function loadAll(tid:string){ const [g,p,w,m,o,a,v]=await Promise.all([
  db.from('s3_grain_inventory').select('*').eq('tenant_id',tid).order('created_at',{ascending:false}),
  db.from('s3_pickups').select('*').eq('tenant_id',tid).order('created_at',{ascending:false}),
  db.from('s3_workshops').select('*').eq('tenant_id',tid).order('created_at',{ascending:false}),
  db.from('s3_pilot_modules').select('*').eq('tenant_id',tid).eq('active',true).order('created_at',{ascending:false}),
  db.from('s3_company_grain_offers').select('*').eq('tenant_id',tid).order('created_at',{ascending:false}),
  db.from('s3_pilot_audit').select('*').eq('tenant_id',tid).order('created_at',{ascending:false}).limit(20),
  db.from('s3_pilot_module_versions').select('*').eq('tenant_id',tid).order('created_at',{ascending:false}).limit(30)
 ]); setGrains(g.data||[]);setPickups(p.data||[]);setWorkshops(w.data||[]);setModules((m.data||[]).map((x:any)=>({...x,fields:Array.isArray(x.fields)?x.fields:[]})));setOffers(o.data||[]);setAudit(a.data||[]);setVersions(v.data||[]); }
 async function signIn(e:FormEvent){e.preventDefault();setMessage('');const {data,error}=await db.auth.signInWithPassword({email:email.trim(),password});if(error||!data.session){setMessage(error?.message||'Could not sign in.');return;}setSession(data.session);await resolveMembership(data.session.access_token);}
 async function signUp(){setMessage('');if(!email||password.length<8){setMessage('Use a valid email and a password of at least 8 characters.');return;}const {data,error}=await db.auth.signUp({email:email.trim(),password});if(error){setMessage(error.message);return;}setMessage(data.session?'Account created. Enter your private pilot code below.':'Account created. Check your email if confirmation is required, then sign in.');if(data.session){setSession(data.session);setLoading(false);}}
 async function claim(){if(!session||!pilotCode.trim())return;setMessage('');const {error}=await db.rpc('claim_s3_pilot',{code:pilotCode.trim()});if(error){setMessage('That pilot code did not work.');return;}setPilotCode('');await resolveMembership(session.access_token);}
 async function addGrain(){if(!membership)return;const {error}=await db.from('s3_grain_inventory').insert({tenant_id:membership.tenant_id,grain:grainForm.grain,quantity:Number(grainForm.quantity)||0,unit:grainForm.unit,storage_location:grainForm.storage_location,source_company:grainForm.source_company,notes:grainForm.notes,created_by:session.user.id,updated_by:session.user.id});if(error){setMessage(error.message);return;}setGrainForm({...grainForm,quantity:'',source_company:'',notes:''});await loadAll(membership.tenant_id);}
 async function addPickup(prefill?:Offer){if(!membership)return;const f=prefill?{...pickupForm,source_company:prefill.company_name,contact_name:prefill.contact_name,grain:prefill.grain,quantity:String(prefill.quantity),unit:prefill.unit,pickup_address:prefill.pickup_address,pickup_date:prefill.ready_date||''}:pickupForm;const {error}=await db.from('s3_pickups').insert({tenant_id:membership.tenant_id,...f,quantity:Number(f.quantity)||0,pickup_date:f.pickup_date||null,created_by:session.user.id,updated_by:session.user.id});if(error){setMessage(error.message);return;}if(prefill)await db.from('s3_company_grain_offers').update({status:'scheduled'}).eq('id',prefill.id);setPickupForm({source_company:'',contact_name:'',contact_phone:'',grain:'',quantity:'',unit:'bushels',pickup_address:'',pickup_date:'',driver:'',destination:'S3 Legacy Ranch',status:'requested',notes:''});await loadAll(membership.tenant_id);}
 async function saveWorkshop(){if(!membership)return;const {error}=await db.from('s3_workshops').insert({tenant_id:membership.tenant_id,...workshop,event_date:workshop.event_date||null,created_by:session.user.id,updated_by:session.user.id});if(error){setMessage(error.message);return;}await loadAll(membership.tenant_id);}
 async function addModule(){if(!membership||!moduleForm.name.trim())return;const fields=moduleForm.fields.split(',').map(x=>x.trim()).filter(Boolean);const {error}=await db.from('s3_pilot_modules').insert({tenant_id:membership.tenant_id,name:moduleForm.name.trim(),description:moduleForm.description.trim(),fields,created_by:session.user.id});if(error){setMessage(error.message);return;}setModuleForm({name:'',description:'',fields:''});await loadAll(membership.tenant_id);}
 async function rollback(moduleId:string,versionId:string){if(!membership)return;const {error}=await db.rpc('rollback_s3_module',{target_module:moduleId,target_version:versionId});if(error){setMessage(error.message);return;}await loadAll(membership.tenant_id);}
 const total=grains.reduce((n,g)=>n+Number(g.quantity||0),0); const latestWorkshop=workshops[0]||null; const isBuilder=['owner','admin','builder'].includes(membership?.role||'');
 const outreach='Hi — I’m inviting a small group of local producers to a practical workshop focused on records, funding, water/feed decisions and finding the right next resource. It is designed to be useful, not salesy. If you know a producer who could use help getting organized or finding support, I’d appreciate an introduction.';
 const sponsor='We are building a hands-on workshop for small farms and ranches that helps producers organize records, identify funding, strengthen water/feed decisions and leave with a concrete action plan. We are seeking sponsors for lunch, venue, printing, producer travel or technical expertise.';

 if(loading)return <main style={center}><strong>Loading S3 Pilot…</strong></main>;
 if(!session)return <main style={center}><div style={{...panel,maxWidth:480,width:'100%'}}><div style={eyebrow}>ARIDON AG · PILOT #1</div><h1>S3 Legacy Ranch</h1><p style={muted}>Each team member uses their own account. Sign in, then claim the private S3 pilot with the code supplied by Aridon.</p><form onSubmit={signIn} style={{display:'grid',gap:10}}><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" style={input}/><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" style={input}/><button style={btn}>Sign in</button></form><button onClick={signUp} style={outline}>Create account</button>{message&&<p style={notice}>{message}</p>}<Link href="/ag/pilot/s3/company" style={link}>Company with grain ready for S3? Open pickup intake →</Link></div></main>;
 if(!membership)return <main style={center}><div style={{...panel,maxWidth:520,width:'100%'}}><ShieldCheck/><h1>Claim your S3 workspace</h1><p style={muted}>Enter the private owner or builder code Aridon sent to S3. Codes assign different permissions.</p><input value={pilotCode} onChange={e=>setPilotCode(e.target.value)} placeholder="Private pilot code" style={{...input,width:'100%'}}/><button onClick={claim} style={btn}>Join S3 Pilot</button><button onClick={()=>db.auth.signOut()} style={outline}>Sign out</button>{message&&<p style={notice}>{message}</p>}</div></main>;

 return <main style={{minHeight:'100vh',background:'#f4f1e8',color:'#17241c',fontFamily:'Arial,sans-serif',paddingBottom:60}}><header style={{background:'#163d2a',color:'#fff',padding:'15px 18px',position:'sticky',top:0,zIndex:20}}><div style={{maxWidth:1180,margin:'auto',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{color:'#c5e2aa',fontSize:12,fontWeight:950}}>ARIDON AG · OFFICIAL PILOT #1</div><strong style={{fontSize:21}}>S3 Legacy Ranch Shared Workspace</strong></div><div style={{display:'flex',gap:9,alignItems:'center',flexWrap:'wrap'}}><span style={{fontSize:12}}>Role: <b>{membership.role}</b></span><Link href="/ag/pilot/s3/company" style={{color:'#fff',fontWeight:900}}>Company intake</Link><button onClick={()=>window.print()} style={smallBtn}><Printer size={14}/> Flyer</button><button onClick={()=>db.auth.signOut()} style={smallBtn}><LogOut size={14}/> Sign out</button></div></div></header>
 <section style={{maxWidth:1180,margin:'auto',padding:'22px 16px'}}>{message&&<div style={notice}>{message}</div>}
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(245px,1fr))',gap:12}}><article style={card}><Boxes/><h3>Grain inventory</h3><b style={{fontSize:32}}>{total.toLocaleString()}</b><p style={muted}>Shared live inventory</p></article><article style={card}><Truck/><h3>S3 pickups</h3><b style={{fontSize:32}}>{pickups.length}</b><p style={muted}>S3 collects from outside companies</p></article><article style={card}><PackageCheck/><h3>Company offers</h3><b style={{fontSize:32}}>{offers.filter(x=>x.status==='new').length}</b><p style={muted}>New grain-ready notices</p></article><article style={card}><Users/><h3>Shared pilot</h3><b style={{fontSize:22}}>Cloud synced</b><p style={muted}>Separate accounts + role permissions + audit history</p></article></section>

 <section style={{...panel,marginTop:14}}><div style={eyebrow}>ADD GRAIN</div><div style={grid}>{Object.entries(grainForm).map(([k,v])=><input key={k} value={v} onChange={e=>setGrainForm({...grainForm,[k]:e.target.value})} placeholder={k.replaceAll('_',' ')} style={input}/>)}</div><button onClick={addGrain} style={btn}>Save grain</button><div style={{marginTop:12,display:'grid',gap:7}}>{grains.slice(0,8).map(g=><div key={g.id} style={row}><b>{g.grain}</b><span>{g.quantity} {g.unit}</span><span>{g.source_company||'source not entered'}</span><span>{g.storage_location}</span></div>)}</div></section>

 <section style={{...panel,marginTop:14}}><div style={eyebrow}>EXTERNAL COMPANY INTAKE</div><h2>Companies tell S3 grain is ready. S3 decides when to pick it up.</h2>{offers.length===0?<p style={muted}>No company notices yet. Share the Company Intake link with grain sources.</p>:offers.slice(0,10).map(o=><div key={o.id} style={row}><div><b>{o.company_name}</b><br/><small>{o.contact_name}</small></div><span>{o.grain}: {o.quantity} {o.unit}</span><span>{o.pickup_address}</span><span>{o.ready_date||'date open'}</span><button onClick={()=>addPickup(o)} style={miniBtn} disabled={o.status==='scheduled'}>{o.status==='scheduled'?'Scheduled':'Create S3 pickup'}</button></div>)}</section>

 <section style={{...panel,marginTop:14}}><div style={eyebrow}>S3 DISPATCH</div><div style={grid}>{Object.entries(pickupForm).map(([k,v])=><input key={k} type={k==='pickup_date'?'date':'text'} value={v} onChange={e=>setPickupForm({...pickupForm,[k]:e.target.value})} placeholder={k.replaceAll('_',' ')} style={input}/>)}</div><button onClick={()=>addPickup()} style={btn}>Add S3 pickup</button>{pickups.slice(0,10).map(p=><div key={p.id} style={row}><b>{p.source_company||'Source'}</b><span>{p.grain} {p.quantity} {p.unit}</span><span>{p.pickup_address}</span><span>{p.driver||'Driver TBD'}</span><span>{p.status}</span></div>)}</section>

 {isBuilder&&<section style={{...panel,marginTop:14,border:'2px solid #356943'}}><div style={{display:'flex',gap:8,alignItems:'center'}}><Code2/><div style={eyebrow}>TRUSTED PILOT BUILDER</div></div><h2>Add working modules without waiting for Aridon to hard-code them.</h2><p style={muted}>Describe the module and its fields. The module is shared with S3 immediately, versioned automatically, and can be rolled back.</p><div style={grid}><input value={moduleForm.name} onChange={e=>setModuleForm({...moduleForm,name:e.target.value})} placeholder="Module name" style={input}/><input value={moduleForm.fields} onChange={e=>setModuleForm({...moduleForm,fields:e.target.value})} placeholder="Fields, comma separated" style={input}/></div><textarea value={moduleForm.description} onChange={e=>setModuleForm({...moduleForm,description:e.target.value})} placeholder="What should this module do?" style={{...input,width:'100%',minHeight:80,marginTop:8}}/><button onClick={addModule} style={btn}><Plus size={15}/> Add shared module</button>{modules.map(m=><div key={m.id} style={{...row,marginTop:8}}><div><b>{m.name}</b><br/><small>{m.description}</small></div><span>{m.fields.join(' · ')||'Notes module'}</span></div>)}</section>}

 {isBuilder&&versions.length>0&&<section style={{...panel,marginTop:14}}><div style={{display:'flex',gap:8,alignItems:'center'}}><History/><div style={eyebrow}>BUILDER VERSION HISTORY</div></div>{versions.slice(0,12).map(v=><div key={v.id} style={row}><b>{v.module_name}</b><span>v{v.version_no}</span><span>{v.change_type}</span><small>{new Date(v.created_at).toLocaleString()}</small>{v.change_type!=='delete'&&<button style={miniBtn} onClick={()=>rollback(v.module_id,v.id)}>Rollback to this</button>}</div>)}</section>}

 <section style={{...panel,marginTop:14}}><div style={eyebrow}>WORKSHOP STUDIO</div><h2>Plan it, schedule it, know what to say, and make the flyer.</h2><div style={grid}>{Object.entries(workshop).map(([k,v])=>k==='talking_points'||k==='flyer_body'?null:<input key={k} type={k==='event_date'?'date':'text'} value={v} onChange={e=>setWorkshop({...workshop,[k]:e.target.value})} placeholder={k.replaceAll('_',' ')} style={input}/>)}</div><textarea value={workshop.talking_points} onChange={e=>setWorkshop({...workshop,talking_points:e.target.value})} style={{...input,width:'100%',minHeight:70,marginTop:8}} placeholder="Talking points"/><textarea value={workshop.flyer_body} onChange={e=>setWorkshop({...workshop,flyer_body:e.target.value})} style={{...input,width:'100%',minHeight:70,marginTop:8}} placeholder="Flyer copy"/><button onClick={saveWorkshop} style={btn}>Save workshop</button><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(270px,1fr))',gap:12,marginTop:15}}><article style={soft}><Megaphone/><h3>Small-farm outreach</h3><p>{outreach}</p></article><article style={soft}><PackageCheck/><h3>Sponsor outreach</h3><p>{sponsor}</p><small>Targets: ag lenders, feed stores, equipment dealers, Farm Bureau, rural electric co-ops, veterinarians, extension, conservation districts, seed/fertilizer suppliers, insurance and regional food buyers.</small></article></div></section>

 <section id="flyer" style={{...panel,marginTop:14,border:'3px solid #163d2a'}}><div style={{display:'flex',gap:8,alignItems:'center',color:'#356943',fontWeight:950}}><WandSparkles/> ONE-PAGE WORKSHOP FLYER</div><h2 style={{fontSize:36,margin:'8px 0'}}>{latestWorkshop?.title||workshop.title}</h2><b>{latestWorkshop?.event_date||workshop.event_date||'Date TBD'} · {latestWorkshop?.event_time||workshop.event_time||'Time TBD'} · {latestWorkshop?.location||workshop.location||'Location TBD'}</b><p style={{fontSize:17,lineHeight:1.6}}>{latestWorkshop?.flyer_body||workshop.flyer_body}</p><p><b>For:</b> {latestWorkshop?.audience||workshop.audience}</p><p><b>Sponsor opportunity:</b> {latestWorkshop?.sponsor_ask||workshop.sponsor_ask}</p><small>Powered by S3 Legacy Ranch + Aridon Ag · Official Pilot #1</small></section>

 <section style={{...panel,marginTop:14}}><div style={eyebrow}>RECENT ACTIVITY</div><h2>Audit trail</h2>{audit.slice(0,12).map(a=><div key={a.id} style={row}><b>{a.action}</b><span>{a.entity_type.replace('s3_','')}</span><small>{new Date(a.created_at).toLocaleString()}</small></div>)}</section>
 </section></main>;
}

const center:React.CSSProperties={minHeight:'100vh',background:'#f4f1e8',display:'grid',placeItems:'center',padding:20,fontFamily:'Arial,sans-serif',color:'#17241c'};
const card:React.CSSProperties={background:'#fff',border:'1px solid #d7dfd4',borderRadius:17,padding:18}; const panel:React.CSSProperties={background:'#fff',border:'1px solid #d7dfd4',borderRadius:18,padding:20}; const soft:React.CSSProperties={background:'#edf2e9',borderRadius:14,padding:16};
const input:React.CSSProperties={border:'1px solid #cfd8cc',borderRadius:9,padding:'10px 11px',background:'#fff',minWidth:0}; const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:8}; const row:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(120px,1fr))',gap:8,alignItems:'center',padding:'10px 12px',background:'#f8f7f2',borderRadius:10,marginTop:7};
const btn:React.CSSProperties={marginTop:10,border:0,borderRadius:10,padding:'10px 13px',background:'#163d2a',color:'#fff',fontWeight:900,cursor:'pointer',display:'inline-flex',gap:5,alignItems:'center'}; const miniBtn:React.CSSProperties={border:0,borderRadius:8,padding:'8px 9px',background:'#163d2a',color:'#fff',fontWeight:850,cursor:'pointer'}; const smallBtn:React.CSSProperties={border:'1px solid #52705e',borderRadius:8,padding:'7px 9px',background:'transparent',color:'#fff',fontWeight:850,display:'flex',gap:5,alignItems:'center'}; const outline:React.CSSProperties={...btn,background:'transparent',color:'#163d2a',border:'1px solid #163d2a'};
const muted:React.CSSProperties={color:'#667169',lineHeight:1.5}; const eyebrow:React.CSSProperties={color:'#356943',fontSize:12,fontWeight:950,letterSpacing:.7}; const notice:React.CSSProperties={background:'#fff5d8',border:'1px solid #e2ca78',padding:11,borderRadius:10,lineHeight:1.45}; const link:React.CSSProperties={display:'block',marginTop:16,color:'#356943',fontWeight:900,textDecoration:'none'};
