'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { getBrowserClient } from '../../../../lib/supabase';
import { benchmarkScenarios } from '../../../../lib/aridonBenchmark';

type Action = { id:string; executive:string; action_type:string; title:string; rationale?:string; expected_outcome?:string; risk_level:string; approval_required:boolean; status:string; created_at:string };
type CompetitorRun = { id:string; competitor_name:string; scenario_title:string; overall_score:number; verdict?:string; created_at:string };

export default function ActionCenter({ params }:{ params:{slug:string} }) {
  const router=useRouter(); const [token,setToken]=useState(''); const [actions,setActions]=useState<Action[]>([]); const [runs,setRuns]=useState<CompetitorRun[]>([]); const [error,setError]=useState('');
  const [actionForm,setActionForm]=useState({ executive:'Eva', actionType:'growth', title:'', rationale:'', expectedOutcome:'', riskLevel:'medium' });
  const [comp,setComp]=useState({ competitorName:'', scenarioId:benchmarkScenarios[0].id as string, answer:'' }); const [compResult,setCompResult]=useState<any>(null);
  useEffect(()=>{ const db=getBrowserClient(); db.auth.getSession().then(async({data})=>{ const access=data.session?.access_token||''; if(!access){router.replace(`/customer/login?next=${encodeURIComponent(`/workspace/${params.slug}/action-center`)}`);return;} setToken(access); await load(access); }); },[params.slug,router]);
  async function load(access=token){ const h={Authorization:`Bearer ${access}`}; const [a,c]=await Promise.all([fetch(`/api/customer/action-queue?slug=${encodeURIComponent(params.slug)}`,{headers:h,cache:'no-store'}),fetch(`/api/customer/competitor-benchmark?slug=${encodeURIComponent(params.slug)}`,{headers:h,cache:'no-store'})]); const ad=await a.json().catch(()=>({})); const cd=await c.json().catch(()=>({})); if(!a.ok||!c.ok){setError(ad.error||cd.error||'Unable to load action center.');return;} setActions(ad.actions||[]);setRuns(cd.runs||[]); }
  async function propose(){ const r=await fetch('/api/customer/action-queue',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({slug:params.slug,...actionForm,approvalRequired:true})}); const d=await r.json().catch(()=>({})); if(!r.ok){setError(d.error||'Unable to propose action.');return;} setActionForm({...actionForm,title:'',rationale:'',expectedOutcome:''}); await load(); }
  async function change(id:string,status:string){ const r=await fetch('/api/customer/action-queue',{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({slug:params.slug,id,status})}); const d=await r.json().catch(()=>({})); if(!r.ok){setError(d.error||'Unable to update action.');return;} await load(); }
  async function scoreCompetitor(){ setCompResult(null); const r=await fetch('/api/customer/competitor-benchmark',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({slug:params.slug,...comp})}); const d=await r.json().catch(()=>({})); if(!r.ok){setError(d.error||'Comparison failed.');return;} setCompResult(d); await load(); }
  return <main style={page}><div style={shell}>
    <header style={header}><div><div style={eyebrow}>ARIDON · EXECUTION + PROOF</div><h1 style={h1}>Action Center</h1><p style={lead}>Move work from proposal to owner-approved execution, and compare competing systems under the same visible-answer benchmark instead of marketing claims.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link href={`/workspace/${params.slug}/mission-control`} style={outline}>Mission Control</Link><Link href={`/workspace/${params.slug}/systems`} style={mint}>Systems</Link></div></header>
    {error&&<div style={errorBox}>{error}</div>}
    <section style={grid}><article style={panel}><div style={label}>CONTROLLED EXECUTION QUEUE</div><h2>Propose an action</h2>{['executive','actionType','title','rationale','expectedOutcome','riskLevel'].map(k=><input key={k} style={input} placeholder={k} value={(actionForm as any)[k]} onChange={e=>setActionForm({...actionForm,[k]:e.target.value})}/>)}<button style={primary} onClick={()=>void propose()}>Send to approval queue</button></article>
    <article style={panel}><div style={label}>SAME-RUBRIC COMPETITOR TEST</div><h2>Score a visible competitor answer</h2><input style={input} placeholder="Competitor/product name" value={comp.competitorName} onChange={e=>setComp({...comp,competitorName:e.target.value})}/><select style={input} value={comp.scenarioId} onChange={e=>setComp({...comp,scenarioId:e.target.value})}>{benchmarkScenarios.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><textarea style={{...input,minHeight:180}} placeholder="Paste the competitor's visible answer to the same scenario" value={comp.answer} onChange={e=>setComp({...comp,answer:e.target.value})}/><button style={primary} onClick={()=>void scoreCompetitor()}>Score under Aridon rubric</button>{compResult&&<div style={result}><strong>{compResult.run.competitor_name}: {compResult.run.overall_score}/100</strong><p>{compResult.run.verdict}</p></div>}</article></section>
    <section style={{...panel,marginTop:14}}><div style={label}>APPROVAL QUEUE</div>{actions.length===0?<p style={muted}>No proposed actions yet.</p>:actions.map(a=><div key={a.id} style={row}><div><strong>{a.title}</strong><div style={muted}>{a.executive} · {a.action_type} · risk {a.risk_level} · {a.status}</div>{a.expected_outcome&&<div style={muted}>Expected: {a.expected_outcome}</div>}</div><div style={{display:'flex',gap:6}}>{a.status==='proposed'&&<><button style={small} onClick={()=>void change(a.id,'approved')}>Approve</button><button style={small} onClick={()=>void change(a.id,'rejected')}>Reject</button></>}{a.status==='approved'&&<button style={small} onClick={()=>void change(a.id,'completed')}>Mark completed</button>}</div></div>)}</section>
    <section style={{...panel,marginTop:14}}><div style={label}>COMPETITOR HISTORY</div>{runs.length===0?<p style={muted}>No side-by-side evidence yet.</p>:runs.map(r=><div key={r.id} style={row}><div><strong>{r.competitor_name}</strong><div style={muted}>{r.scenario_title}</div></div><strong>{r.overall_score}/100</strong></div>)}</section>
  </div></main>;
}

const page={minHeight:'100vh',background:'#07101D',color:'#F7FAFC',fontFamily:'Arial, sans-serif',padding:'28px 20px 72px'};const shell={maxWidth:1180,margin:'0 auto'};const header={display:'flex',justifyContent:'space-between',gap:20,alignItems:'start',flexWrap:'wrap' as const,marginBottom:24};const eyebrow={color:'#9EF0CF',fontSize:12,fontWeight:950,letterSpacing:1};const h1={fontSize:'clamp(46px,7vw,78px)',lineHeight:.95,letterSpacing:-3,margin:'10px 0 14px'};const lead={color:'#B9C5D6',fontSize:18,lineHeight:1.6,maxWidth:850};const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(340px,1fr))',gap:14};const panel={background:'#F6F3EB',color:'#171717',borderRadius:18,padding:20,border:'1px solid #D7D0C3'};const label={fontSize:11,fontWeight:950,letterSpacing:1};const input={width:'100%',boxSizing:'border-box' as const,border:'1px solid #C9C1B4',borderRadius:9,padding:11,font:'inherit',marginTop:8};const primary={marginTop:12,background:'#171717',color:'#fff',border:0,borderRadius:10,padding:'12px 15px',fontWeight:950,cursor:'pointer'};const row={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',padding:'12px 0',borderTop:'1px solid #DED7CB',flexWrap:'wrap' as const};const muted={color:'#6A655D',fontSize:12,lineHeight:1.5};const small={border:'1px solid #BFB7AA',background:'#fff',borderRadius:8,padding:'7px 9px',fontWeight:850,cursor:'pointer'};const result={background:'#E6F4EE',padding:12,borderRadius:10,marginTop:12};const mint={background:'#9EF0CF',color:'#07130F',padding:'12px 16px',borderRadius:11,textDecoration:'none',fontWeight:950};const outline={border:'1px solid #52627A',color:'#F7FAFC',padding:'11px 15px',borderRadius:11,textDecoration:'none',fontWeight:900};const errorBox={background:'#FCE5EA',color:'#7B233A',borderRadius:10,padding:12,marginBottom:14};
