import Link from 'next/link';

const mint='#9EF0CF';
const btn={background:mint,color:'#07130F',textDecoration:'none',fontWeight:950,padding:'14px 18px',borderRadius:12,display:'inline-block'} as const;
const nav={color:'#DCE4EF',textDecoration:'none',fontWeight:850,fontSize:13} as const;

export default function Home(){return <main style={{minHeight:'100vh',background:'#07101D',color:'#F8FAFC',fontFamily:'Arial,sans-serif'}}>
<section style={{maxWidth:1100,margin:'0 auto',padding:'24px 20px 76px'}}>
<nav style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><strong>ARIDON</strong><div style={{display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}><Link href="/exchange" style={nav}>Knowledge Exchange</Link><Link href="/business-os/proof" style={nav}>Proof</Link><Link href="/dashboard" style={nav}>Workspace</Link><Link href="/analyze-business" style={btn}>Analyze My Business Free</Link></div></nav>
<div style={{paddingTop:74,maxWidth:950}}><div style={{color:mint,fontWeight:950,fontSize:12,letterSpacing:1}}>AI EXECUTIVE TEAM FOR OWNER-LED BUSINESSES</div><h1 style={{fontSize:'clamp(50px,8vw,88px)',lineHeight:.93,letterSpacing:-4,margin:'14px 0 22px'}}>Find what your business is leaking. Put an AI executive team on fixing it.</h1><p style={{color:'#B8C4D5',fontSize:21,lineHeight:1.65,maxWidth:850}}>Start with a free analysis of your real website. Aridon shows what is working, what is costing opportunity and what the executive team would attack first. If the value is there, continue for $497/month.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:26}}><Link href="/analyze-business" style={btn}>Analyze My Business Free</Link><a href="#price" style={{...btn,background:'transparent',color:'#fff',border:'1px solid #51617A'}}>See the $497 Plan</a></div><p style={{color:'#91A0B5',fontSize:12,fontWeight:800}}>No card to analyze · No login required · Owner approval stays in control</p></div>
</section>
<section style={{background:'#F4F1E9',color:'#171717',padding:'68px 20px'}}><div style={{maxWidth:1050,margin:'0 auto'}}><div style={{fontSize:12,fontWeight:950}}>SEE IT BEFORE YOU BUY IT</div><h2 style={{fontSize:'clamp(38px,6vw,60px)',lineHeight:1,margin:'10px 0 26px'}}>A real business goes in. A prioritized executive readout comes out.</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}><Card t="Analyze" x="Paste your website and get clarity, conversion, trust and visibility findings."/><Card t="Prioritize" x="Aridon turns the findings into the few moves worth attacking first."/><Card t="Execute" x="Continue only when the work is worth paying for, with consequential actions under owner approval."/></div><div style={{marginTop:28}}><Link href="/analyze-business" style={btn}>Run the Free Analysis</Link></div></div></section>
<section style={{padding:'68px 20px'}}><div style={{maxWidth:1050,margin:'0 auto'}}><div style={{color:mint,fontSize:12,fontWeight:950}}>WHY ARIDON</div><h2 style={{fontSize:'clamp(38px,6vw,60px)',lineHeight:1,margin:'10px 0 24px'}}>Not another chatbot tab. A system built to move business work.</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}><Dark t="Revenue leaks" x="Stale estimates, dormant customers and missed follow-up."/><Dark t="Execution leaks" x="Important work buried in inboxes, spreadsheets and delays."/><Dark t="Decision leaks" x="Research and comparison work that steals owner time."/><Dark t="Proof" x="Measurable pilots and a public proof scoreboard instead of vague claims."/></div></div></section>
<section id="price" style={{background:'#F4F1E9',color:'#171717',padding:'68px 20px'}}><div style={{maxWidth:850,margin:'0 auto'}}><div style={{fontSize:12,fontWeight:950}}>FOUNDING CONTINUATION</div><div style={{background:'#fff',border:'1px solid #D4CEC2',borderRadius:20,padding:26,marginTop:12}}><div><strong style={{fontSize:58}}>$497</strong><span style={{fontSize:18}}> / month</span></div><p style={{fontSize:18,lineHeight:1.65,color:'#5D5A54'}}>Continue when the analysis, demo or pilot shows enough value to justify keeping Aridon working for your business.</p><Link href="/business-os/revenue-recovery" style={{...btn,background:'#171717',color:'#fff'}}>See the Pilot & $497 Continuation</Link></div></div></section>
</main>}
function Card({t,x}:{t:string;x:string}){return <article style={{background:'#fff',border:'1px solid #D4CEC2',borderRadius:16,padding:20}}><h3>{t}</h3><p style={{color:'#5D5A54',lineHeight:1.6}}>{x}</p></article>}
function Dark({t,x}:{t:string;x:string}){return <article style={{background:'#0D1728',border:'1px solid #2A3A57',borderRadius:16,padding:20}}><h3>{t}</h3><p style={{color:'#AEBBD0',lineHeight:1.6}}>{x}</p></article>}
