/**
 * Canonical Aridon context used by Eva.
 * Keep this factual: shipped repository capabilities, owner-approved strategy, and route inventory.
 * Generated/maintained as a durable baseline so Eva does not depend on a single chat session.
 */
export const ARIDON_CANONICAL_CONTEXT = {
  "identity": "Aridon is an AI-driven operating platform. Eva is the default orchestrator/front door: objective -> workstreams -> delegate to specialist executives -> compare -> execute safe/reversible internal work -> escalate consequential actions for approval. Sentinel is the security, identity, authority, intent, behavior-correlation and action-gating layer.",
  "platformStrategy": [
    "Create new customer behaviors and own distribution rather than treating every capability as an isolated product.",
    "Customers should be able to tell Eva the outcome they want; Eva should orchestrate the appropriate Aridon systems, agents, data and workflows.",
    "Build reusable primitives, APIs and partner-extensible workflows, with customer-learning loops and appropriate privacy/consent.",
    "Eva should maintain continuity through durable company knowledge and memory, and must never claim something was saved or executed until persistence/action results confirm success."
  ],
  "majorPrograms": [
    "Southwest Technology Campus (STC): Farmington/Four Corners-centered technology campus strategy spanning AI/data infrastructure, water, energy, agriculture, manufacturing, R&D/testing, tenant space and demonstration facilities.",
    "Water/AWG: atmospheric water generation program, including AWG 30K direction, low-energy R&D, target delivered water cost under $0.60/gallon, pilots and regional water-resilience deployment.",
    "Energy/Iron Grid: geothermal from abandoned wells, solar, storage, microgrids, grid intelligence, resilient power and data-center infrastructure.",
    "Agriculture/Farm OS: farm intelligence, pilots, buyer matching, financing/funding, regenerative transition, robotics, farm passport, food processing, greenhouse and resilience programs.",
    "Sentinel: defensive pre-action AI security across standalone Sentinel, Bank/Financial OS, Business OS and Eva. Core sequence: AI Agent -> Intent Gate -> Identity/Authority Check -> Behavior Correlation -> Action Gate -> Tool/API/Computer. Controls include Agent Passport, Intent Firewall, Chain Detector, Privilege Governor, Machine-Speed Circuit Breaker, Forensic Ledger, prompt-injection protection, continuous risk scoring and independent/human approval for consequential actions.",
    "Business OS: private AI business operating system with executive team, Company Brain, projects/tasks, action fabric, sales/revenue/growth, finance, creator/marketing, acquisition and customer workspaces.",
    "Eva: Aridon orchestrator with chat, live voice, meeting, calling/phone, executive routing, research, action fabric, durable memories and company context."
  ],
  "commercialDirections": [
    "Sentinel consumer/security subscription direction discussed at $49.99/month, including computer protection and financial transaction pause/review concepts where institution/account integrations permit.",
    "Aridon platform distribution includes direct customers, institutional partnerships and third parties/partners building reusable workflows on Aridon.",
    "Pilots are treated as discovery engines: identify repeated customer behavior, automate it, productize it and distribute it."
  ],
  "repoFacts": {
    "repository": "jimrusk/aridon-app",
    "productionBase": "https://aridon-v02.vercel.app",
    "routeCount": 240,
    "documentation": [
      "README.md",
      "docs/ARIDON_AGENT_STACK_2026.md",
      "docs/ARIDON_AG_RD_PORTFOLIO_2026.md",
      "docs/ARIDON_COMMUNITY_RESILIENCE_PILOT.md",
      "docs/ARIDON_FSLC_FOOD_TANK_PROPOSAL_2026.md",
      "docs/AWG_GEN4_LOW_COST_2026.md",
      "docs/DRONE_GRID_INTELLIGENCE_LIVE.md",
      "docs/DRONE_GRID_INTELLIGENCE_MVP.md",
      "docs/EVA_CLIMATE_WEEK_2026_IMPLEMENTATION_DIRECTIVE.md",
      "docs/FACEBOOK_PAGE_LAUNCH_CHECKLIST.md",
      "docs/HIGH_TICKET_BACKEND.md",
      "docs/OPENAI_IMPACT_PARTNERSHIP.md",
      "docs/SENTINEL_AUDIT_AND_PENTEST.md",
      "docs/SENTINEL_BENCHMARK_PROTOCOL.md",
      "docs/SENTINEL_CHATGPT_APP_SUBMISSION.md",
      "docs/SENTINEL_GRID_PARTNER_PROPOSAL.md",
      "docs/STC_EMERGING_COMPUTE_SPINTRONICS.md",
      "docs/agriwebb-staging.md",
      "docs/content-integrity-lane.md",
      "docs/executive-operations-layer.md",
      "docs/farm-bureau-aridon-ag-proposal.md",
      "docs/finance-os.md",
      "docs/index-engine-plan.md",
      "docs/revenue-channel-launch-kit.md"
    ],
    "siteRoutes": [
      "/acquisitions/[id]/decision-support",
      "/acquisitions/[id]",
      "/acquisitions/[id]/underwriting",
      "/acquisitions",
      "/acquisitions/pipeline",
      "/acquisitions/thesis",
      "/advisors/awg1000",
      "/advisors",
      "/ag-robotics",
      "/ag/app",
      "/ag/farm-passport",
      "/ag/farm-passport/review/[token]",
      "/ag/farm-to-health",
      "/ag/farmer-start",
      "/ag/finance/capital-fit",
      "/ag/finance/farm-ownership",
      "/ag/finance",
      "/ag/funding",
      "/ag/governance",
      "/ag/greenhouse",
      "/ag/install",
      "/ag/intelligence",
      "/ag/market-opportunities",
      "/ag/meat-processing",
      "/ag/need-card",
      "/ag",
      "/ag/pilot/s3/company",
      "/ag/pilot/s3",
      "/ag/rancher-network",
      "/ag/rancher-network/proposal",
      "/ag/rancher-network/range",
      "/ag/rd/awg-gen4",
      "/ag/rd/center",
      "/ag/rd/fslc",
      "/ag/rd",
      "/ag/regen",
      "/ag/regenerative/impact",
      "/ag/regenerative",
      "/ag/regenerative/underwriting",
      "/ag/resilience",
      "/ag/snapshot",
      "/ag/soilscan",
      "/ag/standards",
      "/ag/standards/purpose-pledge",
      "/ag/standards/rainforest-alliance",
      "/ag/trust",
      "/ag/wendell-berry",
      "/agent-supervisor",
      "/ai-visibility",
      "/analyze-business",
      "/aridon-browser",
      "/aridon-one",
      "/avatars",
      "/boardroom",
      "/business-os/activate",
      "/business-os/beta",
      "/business-os/beta/sites",
      "/business-os/beta/sites/pratt-marketing",
      "/business-os/checkout",
      "/business-os/clean-energy-leadership",
      "/business-os/deliverability",
      "/business-os/finance",
      "/business-os/growth-command",
      "/business-os/intent-engine",
      "/business-os",
      "/business-os/privacy",
      "/business-os/proof",
      "/business-os/prospect-demo",
      "/business-os/revenue-engine",
      "/business-os/revenue-recovery",
      "/business-os/revenue",
      "/business-os/sentinel/override",
      "/business-os/sentinel",
      "/business-os/sentinel/palo-alto",
      "/business-os/signup",
      "/business-os/subscribe",
      "/business-os/terms",
      "/business-os/zero-to-million",
      "/ceo-brief",
      "/cloud-workers",
      "/commerce",
      "/community-resilience",
      "/controls",
      "/creative-finance",
      "/creator-teacher",
      "/crossroads",
      "/customer-admin",
      "/customer/account",
      "/customer/ag-governance",
      "/customer/aridon-one",
      "/customer/aridon-three",
      "/customer/aridon-two",
      "/customer/assistant",
      "/customer/audience-translator",
      "/customer/claim",
      "/customer/creator/business-builder",
      "/customer/creator/library",
      "/customer/creator",
      "/customer/creator/product-studio",
      "/customer/creator/review",
      "/customer/feedback",
      "/customer/finance",
      "/customer/intelligence",
      "/customer/login",
      "/customer/opportunities",
      "/customer/referrals",
      "/customer/reset",
      "/customer/sales/launch",
      "/customer/sales/opportunity-radar",
      "/customer/sales",
      "/customer/sales/security-radar",
      "/customer/start",
      "/customer/upgrade",
      "/customer/upgrade/success",
      "/customer/visual",
      "/customer/visual/review",
      "/customers/beta",
      "/customers/feedback",
      "/customers/metrics",
      "/daily-demos/[slug]",
      "/daily-demos/reliable-air-a13",
      "/dashboard",
      "/david-austin",
      "/demos/[slug]",
      "/demos/endurance-fcu",
      "/demos/rfsi-forum",
      "/demos/rodale-10-million-acres",
      "/email",
      "/eva-calls",
      "/eva-chat",
      "/eva-core",
      "/eva-live",
      "/eva-meeting-bridge",
      "/eva-meeting-direct",
      "/eva-meeting",
      "/eva-phone-bridge",
      "/eva-phone",
      "/exchange",
      "/execution/doe-test",
      "/execution",
      "/executive-ops/control-center",
      "/executive-ops",
      "/facebook-launch",
      "/finance",
      "/flexible-energy-campus",
      "/founding-demos/[slug]",
      "/garden-commerce",
      "/grid-intelligence/live",
      "/grid-intelligence",
      "/grid-os/lpea-carbon",
      "/grid-os",
      "/gridready",
      "/growth-audit",
      "/growth-desk",
      "/growth-desk/scout-hvac-abq",
      "/growth/next",
      "/growth",
      "/impact-os",
      "/install",
      "/intelligence",
      "/investor-intelligence",
      "/investor-signal",
      "/landscape-os",
      "/landscape-os/visual-builder",
      "/local-growth",
      "/manifesto",
      "/marketing-autopilot",
      "/marketing-autopilot/proof-engine",
      "/media-engine",
      "/mobile-app/analyze",
      "/mobile-app/demo",
      "/mobile-app",
      "/model-router",
      "/next-actions",
      "/opportunity-intelligence",
      "/opportunity-map/closing-guide",
      "/opportunity-map",
      "/outreach-monitor",
      "/partners/cnm-ingenuity",
      "/partners/cnm-ingenuity/teacher",
      "/partners/codie-sanchez",
      "/partners/codie-sanchez/teacher",
      "/partners/maria-wendt",
      "/partners/maria-wendt/teacher",
      "/partners/openai-impact",
      "/presentation-studio",
      "/property-intelligence/land",
      "/property-intelligence/market",
      "/property-intelligence",
      "/property-intelligence/sources",
      "/property-intelligence/value",
      "/prospect-demos/[slug]",
      "/prospect-demos/shes-rooted-home",
      "/r-beautiful",
      "/relationship-brain",
      "/resilience-offers",
      "/revenue",
      "/safewalk/g/[token]",
      "/sales-team",
      "/sales/high-ticket",
      "/sales",
      "/sentinel-demo",
      "/sentinel-grid",
      "/sentinel-grid/privacy",
      "/sentinel-lab",
      "/sentinel-pilot",
      "/sentinel-security",
      "/sentinel-security/palo-alto",
      "/shop/[category]",
      "/shop",
      "/shop/product/[slug]",
      "/shop/success",
      "/site-indexing",
      "/sms",
      "/stadium-os/[team]",
      "/trust-layer",
      "/video-studio",
      "/wildfire-resilience",
      "/worker-connections",
      "/workspace/[slug]/acquisition-command",
      "/workspace/[slug]/action-center",
      "/workspace/[slug]/ag-governance",
      "/workspace/[slug]/aridon-one",
      "/workspace/[slug]/audience-translator",
      "/workspace/[slug]/benchmark",
      "/workspace/[slug]/call-command/live",
      "/workspace/[slug]/call-command",
      "/workspace/[slug]/cloud-workers",
      "/workspace/[slug]/compass",
      "/workspace/[slug]/digital-humans",
      "/workspace/[slug]/executive-call",
      "/workspace/[slug]/executive-command",
      "/workspace/[slug]/executive-suite",
      "/workspace/[slug]/finance",
      "/workspace/[slug]/mission-control",
      "/workspace/[slug]",
      "/workspace/[slug]/systems",
      "/workspace/[slug]/technology-radar",
      "/workspace/[slug]/worker-connections",
      "/workspace/preview"
    ]
  }
} as const;

export function aridonCanonicalContext() {
  return ARIDON_CANONICAL_CONTEXT;
}
