import type { DailyProspectDemo } from './prospectDemosDaily';
const expiresAt='2026-08-28T23:59:59-06:00';
type Kind='hvac'|'construction'|'landscape'|'auto'|'roofing'|'plumbing';
const presets={
 hvac:{services:['HVAC service and repair','Installation and replacement','Preventive maintenance','Customer follow-up'],opportunities:['Unclosed replacement estimates','Missed service callbacks','Seasonal maintenance reactivation','Owner/admin follow-up bottlenecks']},
 construction:{services:['Construction and remodeling','Estimates and consultations','Project coordination','Customer follow-up'],opportunities:['Estimates that never closed','Qualified inquiries waiting on a next step','Past customers with new project potential','Owner time lost to proposal follow-up']},
 landscape:{services:['Landscape design or maintenance','Project estimates','Scheduling','Customer follow-up'],opportunities:['Landscape estimates that went quiet','Seasonal repeat-customer reactivation','Consultations that never became booked work','Owner/admin time lost to follow-up']},
 auto:{services:['Auto sales and service','Maintenance','Service estimates','Customer follow-up'],opportunities:['Service estimates that were postponed','Past customers due for maintenance','Missed callbacks','Front-office follow-up bottlenecks']},
 roofing:{services:['Roofing repair and replacement','Inspections and estimates','Project scheduling','Customer follow-up'],opportunities:['Roof estimates that never closed','Inspection leads needing a next step','Past customers due for maintenance or repair','Estimator/admin follow-up bottlenecks']},
 plumbing:{services:['Plumbing and HVAC service','Repair and replacement','Estimates','Customer follow-up'],opportunities:['Unclosed repair or replacement estimates','Missed service inquiries','Past customers with repeat-service potential','Scheduling and follow-up bottlenecks']}
} as const;
function d(slug:string,kind:Kind,companyName:string,industry:string,location:string,website:string,contactEmail:string,publicSummary:string):DailyProspectDemo{const p=presets[kind];return{slug,active:true,expiresAt,companyName,industry,location,website,contactEmail,publicSummary,services:[...p.services],opportunities:[...p.opportunities],sampleBrief:['Baseline: identify a permissioned list of stale leads, estimates or repeat-customer opportunities.','Pilot: prioritize likely recoverable opportunities without sending anything externally without approval.','Measure: separate influenced opportunity value from revenue actually collected.','Day 14: report responses, booked work, collected revenue if known, and documented time saved.'],starterQuestions:['What stale estimates or missed follow-ups should we test first?','What is a clean success threshold for a 14-day pilot?','How can we recover value while keeping every external action approval-gated?']};}
export const prospectDemosAug14:DailyProspectDemo[]=[
 d('ground-up-landscape-a14','landscape','From the Ground Up Landscape Construction & Design','Landscaping','Rio Rancho, New Mexico','https://fromthegrounduplandscapesnm.com/','contact@fromthegrounduplandscapesnm.com','Public information describes a Rio Rancho landscape construction and design company offering project quotes and ongoing customer communication.'),
 d('all-seasons-landscape-a14','landscape','All Seasons Landscape','Landscaping','Rio Rancho, New Mexico','https://www.allseasonsnm.com/','contact@allseasonsnm.com','Public information describes a Rio Rancho landscaping company offering design and project implementation services.'),
 d('medinas-plumbing-a14','plumbing','Medina’s Plumbing','Plumbing and HVAC','Las Cruces, New Mexico','https://medinasplumbing.com/','medinasplumbing@outlook.com','Public information describes a Las Cruces plumbing and HVAC service company handling appointments, emergency service, repair and customer inquiries.'),
 d('silvas-roofing-a14','roofing','Silva’s Roofing & Gutters','Roofing','Albuquerque, New Mexico','https://www.silvasroofingnm.com/','info@silvasroofingnm.com','Public information describes an Albuquerque-area roofing company offering roof installation, estimates and customer inquiry response.'),
 d('mountain-paradise-a14','landscape','Mountain Paradise Landscaping','Landscaping and outdoor construction','Albuquerque / Rio Rancho, New Mexico','https://mp-nm.com/','david@mp-nm.com','Public information describes an owner-led landscaping company providing design, construction, hardscaping, pools, irrigation and outdoor projects.'),
 d('car-land-a14','auto','Car Land','Auto sales and service','Farmington, New Mexico','https://www.carlandonline.com/','scott@carlandonline.com','Public information describes a Farmington auto business with sales, service and a long-tenured local team.'),
 d('santa-fe-style-builders-a14','construction','Santa Fe Style Builders','Construction','Santa Fe, New Mexico','https://santafestylebuilders.com/','info@santafestylebuilders.com','Public information describes a Santa Fe builder led by founder Michael Roybal with a process spanning client engagement, design, planning and construction.'),
 d('hyde-park-construction-a14','construction','Hyde Park Stucco & Construction','Stucco and construction','Santa Fe, New Mexico','https://www.hydeparkconstruction.com/','cristian@hydeparkconstruction.com','Public information describes a family-owned Santa Fe contractor providing stucco, plaster and construction services.'),
 d('scottsdale-plumbing-a14','plumbing','Scottsdale Plumbing','Plumbing','Scottsdale, Arizona','https://www.scottsdaleplumbing.com/','info@scottsdaleplumbing.com','Public information describes a family-owned full-service plumbing company offering emergency service, repairs, installations, remodeling and commercial plumbing.'),
 d('abrc-tucson-a14','roofing','ABRC','Roofing and exteriors','Tucson, Arizona','https://www.abrctucson.com/','admin@usabestroofing.com','Public information describes a Tucson roofing and exterior contractor offering inspections, roofing, siding, gutters and estimates.'),
 d('dlc-construction-a14','construction','DLC Construction & Remodeling LLC','Construction and remodeling','Arizona','https://dlcconstructionaz.com/','dlccon.remodeling@gmail.com','Public information describes a family-owned Arizona general contractor providing residential and commercial remodeling, additions and custom builds.'),
 d('san-tan-renovations-a14','construction','San Tan Renovations and Home Services','Renovation and property services','East Valley, Arizona','https://santanrenovations.com/','david@santanrenovations.com','Public information describes an East Valley renovation and home-services contractor handling remodels, handyman work, property repairs and estimates.'),
 d('norris-air-a14','hvac','Norris Air','HVAC','Mesa, Arizona','https://norrisair.com/','norrisair@norrisairinc.com','Public information describes a Mesa HVAC company handling service, repair, installation, maintenance and customer scheduling.'),
 d('desert-paradise-landscape-a14','landscape','Desert Paradise Landscape Management','Landscaping','Chandler, Arizona','https://www.desertparadiselandscape.com/','info@desertparadiselandscape.com','Public information describes a Chandler landscape company providing project estimates, landscape work and ongoing customer service.'),
 d('peak-landscape-a14','landscape','Peak Landscape','Landscaping','Chandler, Arizona','https://azpeaklandscape.com/','jordan@azpeaklandscape.com','Public information describes a Chandler landscaping company providing maintenance, enhancements and consultation services.'),
 d('america-roofing-a14','roofing','America Roofing','Roofing','Phoenix / Tucson, Arizona','https://www.americaroofingco.com/','sales@americaroofingco.com','Public information describes an Arizona residential and commercial roofing company serving Phoenix and Tucson and offering free roofing quotes and bids.')
];