import type { DailyProspectDemo } from './prospectDemosDaily';
const expiresAt='2026-08-27T23:59:59-06:00';
type Kind='hvac'|'construction'|'landscape'|'property'|'auto';
const presets={
 hvac:{services:['HVAC service and repair','Installation and replacement','Preventive maintenance','Customer follow-up'],opportunities:['Unclosed estimates and replacement quotes','Missed callbacks and service inquiries','Seasonal maintenance reactivation','Owner/admin follow-up bottlenecks']},
 construction:{services:['Construction and remodeling','Estimates and consultations','Project coordination','Customer follow-up'],opportunities:['Estimates and consultations that never closed','Qualified inquiries waiting on a next step','Past customers with new project potential','Owner time lost to proposal and follow-up administration']},
 landscape:{services:['Landscape design or maintenance','Project estimates','Scheduling','Customer follow-up'],opportunities:['Landscape estimates that went quiet','Seasonal or repeat-customer reactivation','Consultations that never became booked work','Owner/admin time lost to follow-up']},
 property:{services:['Property services','Client inquiries','Recurring service coordination','Customer follow-up'],opportunities:['Owner or tenant inquiries needing follow-up','Past clients with repeat-service potential','Proposals or service opportunities that stalled','Administrative work consuming owner time']},
 auto:{services:['Auto repair and maintenance','Diagnostics','Service estimates','Customer follow-up'],opportunities:['Repair estimates that were postponed','Past customers due for maintenance','Missed service callbacks','Front-office follow-up and scheduling bottlenecks']}
} as const;
function d(slug:string,kind:Kind,companyName:string,industry:string,location:string,website:string,contactEmail:string,publicSummary:string):DailyProspectDemo{const p=presets[kind];return{slug,active:true,expiresAt,companyName,industry,location,website,contactEmail,publicSummary,services:[...p.services],opportunities:[...p.opportunities],sampleBrief:[`Baseline: identify a permissioned list of stale leads, estimates or repeat-customer opportunities.`,`Pilot: prioritize the most likely recoverable opportunities without sending anything externally without approval.`,`Measure: separate influenced opportunity value from revenue actually collected.`,`Day 14: report responses, booked work, collected revenue if known, and documented time saved.`],starterQuestions:['What stale estimates or missed follow-ups should we test first?','What is a clean success threshold for a 14-day pilot?','How can we recover value while keeping every external action approval-gated?']};}
export const prospectDemosAug13:DailyProspectDemo[]=[
 d('whelchel-landscape-a13','landscape','Whelchel Landscape & Construction','Landscaping and construction','Bernalillo / Albuquerque Metro, New Mexico','https://nmlandscaping.com/','info@nmlandscaping.com','Public information describes a small family-owned landscaping and construction business serving Albuquerque-area communities for more than 20 years with design, installation, xeriscaping and outdoor projects.'),
 d('premier-contractors-nm-a13','construction','Premier Contractors Inc','Construction and remodeling','New Mexico','https://www.premiercontractorsnm.com/','info@premiercontractorsnm.com','Public information describes a New Mexico contractor offering custom homes, additions, renovations, kitchen and bath upgrades, exterior work, flooring, framing, stucco, painting and related services.'),
 d('poulin-design-a13','construction','Poulin Design Center','Remodeling and design-build','Albuquerque / Santa Fe, New Mexico','https://poulindesigncenter.com/','info@PoulinRemodeling.com','Public information describes a New Mexico remodeling and design center serving Albuquerque, Santa Fe, Los Alamos and surrounding communities with kitchen, bath and home remodeling services.'),
 d('rakso-construction-a13','construction','Rakso Construction','General contracting and remodeling','Santa Fe, New Mexico','https://raksoconstruction.com/','info@raksoconstruction.com','Public information describes an owner-led Santa Fe general contractor and master stoneworker providing residential construction, remodeling, masonry and related services for more than 20 years.'),
 d('las-cruces-builder-a13','construction','Las Cruces Builder','Custom homes and remodeling','Las Cruces, New Mexico','https://lascrucesbuilder.com/','info@lascrucesbuilder.com','Public information describes a Las Cruces builder providing custom homes, remodeling, renovations, repairs and metalwork with an emphasis on communication and customer service.'),
 d('heartwood-construction-a13','construction','Heartwood Construction','Custom residential construction','Santa Fe, New Mexico','https://www.hwcbuild.com/','Info@hwcbuild.com','Public information describes a Santa Fe construction company focused on custom residential homes, remodeling, high-performance building and low-carbon design.'),
 d('rojas-auto-a13','auto','Rojas Auto Solutions','Auto repair and maintenance','Albuquerque, New Mexico','https://www.rojasautosolutions.com/','Info@rojasautosolutions.com','Public information describes an Albuquerque auto repair shop providing routine maintenance, inspections, diagnostics and repairs from its Central Avenue location.'),
 d('ecoscapes-sf-a13','landscape','EcoScapes of Santa Fe','Landscape design-build','Santa Fe, New Mexico','https://ecoscapesnm.com/','info@ecoscapesnm.com','Public information describes a Santa Fe landscape company founded in 2001 providing ecological landscape design, construction, maintenance, irrigation and water-conservation services.'),
 d('gold-canyon-remodeling-a13','construction','Gold Canyon Remodeling','Home remodeling','Phoenix / East Valley, Arizona','https://www.goldcanyonremodeling.com/','info@goldcanyonremodeling.com','Public information describes an Arizona remodeling contractor with decades of experience providing kitchens, bathrooms, additions, whole-home remodels, exterior makeovers and repairs.'),
 d('sms-az-a13','hvac','Specialized Mechanical Solutions','Industrial HVAC and refrigeration','Arizona','https://www.smsaz.net/','info@smsaz.net','Public information describes an Arizona mechanical and refrigeration contractor providing industrial HVAC design, installation, repair, maintenance and emergency support.'),
 d('chavez-construction-az-a13','construction','Chavez Construction LLC','Construction and remodeling','Phoenix, Arizona','https://www.chavezbuild.com/','info@chavezbuild.com','Public information describes a Phoenix contractor with more than 25 years of experience in new builds, remodels, additions and general contracting for residential and commercial clients.'),
 d('alpha-remodel-az-a13','construction','Alpha Remodel LLC','General contracting and remodeling','Phoenix, Arizona','https://www.alpharemodelaz.com/','info@alpharemodelaz.com','Public information describes a small Arizona general contractor focused on residential and commercial remodeling, additions, new builds, design, renderings and permitting.'),
 d('custom-design-build-az-a13','construction','Custom Design Build & Remodel','Remodeling and home services','Mesa / Phoenix Metro, Arizona','https://customdesignbuildremodel.com/','info@customdesignbuildremodel.com','Public information describes a Phoenix-metro remodeling contractor providing renovations and additions alongside licensed cooling, plumbing and electrical capabilities.'),
 d('lafarga-franz-a13','construction','Lafarga-Franz Construction','General contracting and remodeling','Tucson, Arizona','https://thetucsoncontractor.com/','info@thetucsoncontractor.com','Public information describes a Tucson general contractor serving homeowners and property managers with remodeling, additions, roofing, drywall, stucco, painting, flooring and framing.'),
 d('unique-electrical-a13','construction','Unique Electrical Contractors','Electrical contracting','Scottsdale / Phoenix Metro, Arizona','https://www.uniqueelectrical.com/','info@uniqueelectrical.com','Public information describes an Arizona electrical contractor serving residential and commercial clients with new construction, service upgrades, lighting, remodels, security and tenant improvements.'),
 d('halo-electric-a13','construction','Halo Electric LLC','Electrical contracting','Scottsdale / Phoenix Metro, Arizona','https://haloelectricaz.com/','info@HaloElectricAz.com','Public information describes an Arizona electrical contractor providing commercial, industrial and construction electrical work, repairs, remodels, installations, design and emergency power solutions.')
];