import type { DailyProspectDemo } from './prospectDemosDaily';

const expiresAt = '2026-08-25T23:59:59-06:00';
const commonOps = [
  'Create one owner-visible follow-up queue so qualified inquiries, estimates and callbacks do not disappear during busy weeks.',
  'Rank open revenue opportunities by urgency, value, probability and the next human-approved action.',
  'Turn completed work into a repeatable review, referral, reactivation and recurring-service pipeline.',
  'Give the owner a concise daily brief covering new demand, overdue follow-up, operational risk and the few actions that matter most.'
];
const commonBrief = [
  'Revenue: identify the highest-value open opportunities that need a human follow-up today.',
  'Operations: surface work, estimates or customer promises blocked by a missing decision or dependency.',
  'Customer: identify completed work ready for review, referral or repeat-service outreach.',
  'Owner: show the top three decisions or approvals that would move the business forward today.'
];
const commonQuestions = [
  'Where is revenue most likely leaking out of our current follow-up process?',
  'Build a simple owner dashboard for leads, estimates, active work and repeat customers.',
  'Create a 30-day plan to increase conversion and repeat business without adding unnecessary admin work.'
];
function demo(slug:string, companyName:string, industry:string, location:string, website:string, contactEmail:string, publicSummary:string, services:string[]):DailyProspectDemo {
  return { slug, active:true, expiresAt, companyName, industry, location, website, contactEmail, publicSummary, services, opportunities:[...commonOps], sampleBrief:[...commonBrief], starterQuestions:[...commonQuestions] };
}

export const prospectDemosAug11: DailyProspectDemo[] = [
  demo('marathon-janitorial-a11m','Marathon Janitorial','Commercial janitorial services','Albuquerque, New Mexico','https://www.marathonjanitorial.com/','info@marathonjanitorial.com','Public website information describes Marathon Janitorial as a family-owned Albuquerque small business providing commercial cleaning for offices, real estate, medical facilities, schools and other facilities.',['Commercial janitorial service','Office and facility cleaning','Medical and school cleaning','Customer scheduling and account follow-up']),
  demo('daves-grounds-a11d','Dave’s Grounds Maintenance, Inc.','Landscaping and grounds maintenance','Albuquerque, New Mexico','https://www.davesgrounds.com/','dgmgrounds@msn.com','Public website information describes Dave’s Grounds Maintenance as a locally and family-owned New Mexico landscaping company serving residents and businesses since 1998, with landscape, lawn, tree, shrub, irrigation and plant-care services.',['Landscape maintenance','Lawn and plant care','Irrigation installation and repair','Residential and commercial account service']),
  demo('otero-brothers-a11o','Otero Brothers Landscaping','Landscape design and installation','Albuquerque, New Mexico','https://www.oterobrotherslandscaping.com/','csr@oterobrosnm.com','Public website information describes Otero Brothers Landscaping as a family-owned Albuquerque company providing landscape design, installation, hardscaping, irrigation, water features and yard maintenance for residential and commercial customers.',['Landscape design and installation','Hardscaping and outdoor living','Irrigation and water features','Residential and commercial landscaping']),
  demo('cordray-electric-a11c','Cordray Electric, Inc.','Commercial electrical contractor','Albuquerque and Santa Fe, New Mexico','https://www.cordrayelectric.com/','deanna@cordrayelectric.com','Public website information describes Cordray Electric as a family-owned New Mexico electrical contractor founded in 2000 and serving Albuquerque and Santa Fe as a primary electrical contractor or specialty subcontractor.',['Commercial electrical contracting','Electrical project coordination','Subcontract electrical work','Customer and contractor follow-up']),
  demo('sta-plumbing-a11s','STA Plumbing LLC','Plumbing services','Albuquerque, New Mexico','https://staplumbingabq.com/','staplumbing@yahoo.com','Public website information describes STA Plumbing as a locally owned and family-operated Albuquerque plumbing business serving customers since 2011 with residential plumbing, troubleshooting and repair services.',['Residential plumbing','Plumbing repair and troubleshooting','Estimates and appointments','Customer follow-up']),
  demo('all-green-nm-a11g','All Green Landscaping LLC','Landscaping services','Albuquerque, New Mexico','https://allgreennm.com/','sales@allgreenNM.com','Public website information describes All Green Landscaping as a family-owned Albuquerque landscaping business providing lawn care, garden design, irrigation, hardscaping and complete outdoor transformations.',['Landscape design','Lawn and garden care','Irrigation systems','Hardscaping and outdoor transformations']),
  demo('urban-earth-a11u','Urban Earth Landscaping','Landscape design and installation','Albuquerque and surrounding New Mexico communities','https://urbanearthlandscaping.com/','info@urbanearthlandscaping.com','Public website information describes Urban Earth Landscaping as a locally owned, family-operated full-service Albuquerque company offering landscape design, installation, pavers, irrigation, lighting, outdoor kitchens, pergolas, ponds, turf, water features and xeriscaping.',['Landscape design and installation','Irrigation and xeriscaping','Outdoor living construction','Landscape maintenance']),
  demo('tnt-pest-a11t','TNT Pest Control','Pest and weed control','Albuquerque, New Mexico','https://www.tntpestcontrolservice.com/','contact@tntpestcontrolservice.com','Public website information describes TNT Pest Control as a family-owned and operated New Mexico business providing residential, commercial and industrial pest, weed, wildlife and pest-bird management services.',['Residential pest control','Commercial and industrial pest control','Weed control','Wildlife and pest-bird management']),
  demo('spark-pro-electric-a11p','Spark Pro Electric','Electrical contractor','Greater Phoenix, Arizona','https://www.sparkproelectric.com/','sparkproaz@gmail.com','Public website information describes Spark Pro Electric as a family-owned and operated electrical contractor serving the greater Phoenix area with residential and commercial electrical services.',['Residential electrical service','Commercial electrical service','Troubleshooting and upgrades','Estimates and customer follow-up']),
  demo('wellco-electric-a11w','Wellco Electric','Commercial electrical contractor','Phoenix, Arizona','https://wellcoaz.com/','bradw@wellcoaz.com','Public website information describes Wellco Electric as a family-owned Phoenix commercial electrical contractor serving construction, remodel, restaurant, manufacturing and service projects since 1980.',['Commercial electrical construction','Remodel electrical work','Service and troubleshooting','Bid and project follow-up']),
  demo('hort-frontiers-a11h','Horticultural Frontiers','Landscape design and installation','Phoenix, Arizona','https://www.hortfrontiers.com/','horticulturalfrontiers@cox.net','Public website information describes Horticultural Frontiers as a family-owned and operated Phoenix landscaping company specializing in custom landscape design, installation and consultation.',['Landscape design','Landscape installation','Consultation','Project follow-up']),
  demo('sandoval-electric-a11e','Sandoval Electrical Services LLC','Electrical contractor','Fountain Hills and Phoenix area, Arizona','https://www.sandovalelectrical.com/','sandoval.electric@protonmail.com','Public website information describes Sandoval Electrical Services as a family-owned and operated licensed Arizona electrical contractor serving residential and commercial customers.',['Residential electrical service','Commercial electrical service','Electrical upgrades and repairs','Estimates and customer follow-up']),
  demo('frank-son-landscape-a11f','Frank & Son Landscaping','Landscaping services','Phoenix Valley, Arizona','https://www.frankandsonlandscaping.com/','juan.sanchez@frankandsonlandscaping.com','Public website information describes Frank & Son Landscaping as a family-owned and operated Arizona company providing residential and commercial landscaping, design, installation, hardscape and property maintenance.',['Residential landscaping','Commercial and HOA maintenance','Landscape design and installation','Hardscape']),
  demo('ag-procare-a11a','A&G ProCare Landscaping','Landscape design, installation and maintenance','Phoenix Metro, Arizona','https://www.agprocarelandscaping.com/','info@agprocarelandscaping.com','Public website information describes A&G ProCare Landscaping as a locally owned, family-operated Phoenix-area full-service landscape design, installation and maintenance company that grew from a 2020 startup into hundreds of clients.',['Landscape design','Landscape installation','Landscape maintenance','Customer account service']),
  demo('az-ground-control-a11z','Arizona Ground Control','Lawn and landscape maintenance','Phoenix and Scottsdale, Arizona','https://arizonagroundcontrol.com/','info@arizonagroundcontrol.com','Public website information describes Arizona Ground Control as a family-owned and operated Phoenix-area lawn maintenance and landscaping company providing mowing, weed control, trimming, irrigation, seeding, fertilizing and related services.',['Lawn maintenance','Landscape cleanup','Irrigation work','Weed, shrub and tree care']),
  demo('champion-air-a11i','Champion Air Conditioning & Heating','HVAC services','Phoenix and Scottsdale, Arizona','https://www.championair.com/','office@championair.com','Public website information describes Champion Air as a family-owned Arizona HVAC company serving Phoenix and Scottsdale with air-conditioning, heating, emergency support and related home-comfort services.',['Air conditioning service','Heating service','Emergency HVAC support','Estimates and customer follow-up'])
];
