import type { DailyProspectDemo } from './prospectDemosDaily';
const expiresAt='2026-08-29T23:59:59-06:00';
type Kind='hvac'|'construction'|'landscape'|'roofing'|'plumbing'|'electrical';
const presets={
 hvac:{services:['HVAC service and repair','Installation and replacement','Preventive maintenance','Customer follow-up'],opportunities:['Unclosed replacement estimates','Missed service callbacks','Seasonal maintenance reactivation','Owner/admin follow-up bottlenecks']},
 construction:{services:['Construction and remodeling','Estimates and consultations','Project coordination','Customer follow-up'],opportunities:['Estimates that never closed','Qualified inquiries waiting on a next step','Past customers with new project potential','Owner time lost to proposal follow-up']},
 landscape:{services:['Landscape design or maintenance','Project estimates','Scheduling','Customer follow-up'],opportunities:['Landscape estimates that went quiet','Seasonal repeat-customer reactivation','Consultations that never became booked work','Owner/admin time lost to follow-up']},
 roofing:{services:['Roofing repair and replacement','Inspections and estimates','Project scheduling','Customer follow-up'],opportunities:['Roof estimates that never closed','Inspection leads needing a next step','Past customers due for maintenance or repair','Estimator/admin follow-up bottlenecks']},
 plumbing:{services:['Plumbing service and repair','Repair and replacement','Estimates','Customer follow-up'],opportunities:['Unclosed repair or replacement estimates','Missed service inquiries','Past customers with repeat-service potential','Scheduling and follow-up bottlenecks']},
 electrical:{services:['Electrical service and installation','Residential and commercial estimates','Project scheduling','Customer follow-up'],opportunities:['Electrical estimates that never closed','Missed service inquiries','Past customers with upgrade or repeat-service potential','Scheduling and follow-up bottlenecks']}
} as const;
function d(slug:string,kind:Kind,companyName:string,industry:string,location:string,website:string,contactEmail:string,publicSummary:string):DailyProspectDemo{const p=presets[kind];return{slug,active:true,expiresAt,companyName,industry,location,website,contactEmail,publicSummary,services:[...p.services],opportunities:[...p.opportunities],sampleBrief:['Baseline: identify a permissioned list of stale leads, estimates or repeat-customer opportunities.','Pilot: prioritize likely recoverable opportunities without sending anything externally without approval.','Measure: separate influenced opportunity value from revenue actually collected.','Day 14: report responses, booked work, collected revenue if known, and documented time saved.'],starterQuestions:['What stale estimates or missed follow-ups should we test first?','What is a clean success threshold for a 14-day pilot?','How can we recover value while keeping every external action approval-gated?']};}
export const prospectDemosAug15:DailyProspectDemo[]=[
 d('all-green-landscaping-a15','landscape','All Green Landscaping LLC','Landscaping','Albuquerque, New Mexico','https://www.allgreennmllc.com/','sales@allgreennmllc.com','Public information describes an Albuquerque landscaping company serving Albuquerque, Rio Rancho, Los Lunas, Belen and Santa Fe with project consultations and landscape work.'),
 d('sotelo-jm-construction-a15','construction','Sotelo JM Construction LLC','Construction and remodeling','Santa Fe / Albuquerque, New Mexico','https://jmconstructionnm.com/','sotelojose22@gmail.com','Public information describes a licensed New Mexico contractor providing remodeling, roofing, concrete, framing, flooring and related construction services.'),
 d('jr-general-remodeling-a15','construction','JR General Remodeling & Outdoor Maintenance','Remodeling and property services','Santa Fe, New Mexico','https://www.jrgeneralremodeling.com/','jrgeneralremodel@gmail.com','Public information describes a Santa Fe owner-led remodeling and property-maintenance company offering handyman, remodeling, landscaping, roofing repair and ongoing maintenance work.'),
 d('dreamscape-nm-a15','landscape','Dreamscape NM','Landscaping and outdoor construction','Albuquerque / Rio Rancho, New Mexico','https://dreamscapenm.com/','support@dreamscapenm.com','Public information describes a New Mexico landscape and outdoor-construction company providing pools, turf, concrete, stucco, walls and landscape projects.'),
 d('back-breakers-a15','landscape','Back Breakers Landscaping & Maintenance LLC','Landscaping','Albuquerque / Rio Rancho, New Mexico','https://back-breakers.com/','office@back-breakers.com','Public information describes a licensed Albuquerque-area landscaping and maintenance company offering hardscaping, landscaping, maintenance and commercial landscape services.'),
 d('all-roofing-enterprises-a15','roofing','All Roofing Enterprises LLC','Roofing','Santa Fe / Albuquerque, New Mexico','https://www.allroofingnm.com/','Ferbie@allroofingnm.com','Public information describes a New Mexico roofing contractor offering roofing estimates, repair and roofing services in Santa Fe and Albuquerque.'),
 d('five-star-electric-a15','electrical','Five Star Electric','Electrical','Rio Rancho / Albuquerque, New Mexico','https://www.fivestarelectricnm.com/','fivestarelectricnm@gmail.com','Public information describes a Rio Rancho electrical contractor serving Albuquerque-area residential and commercial customers and offering free estimates.'),
 d('defined-electric-a15','electrical','Defined Electric','Electrical','Albuquerque / Rio Rancho, New Mexico','https://definedelectric.com/','defined.electric@gmail.com','Public information describes a veteran-owned Albuquerque electrical contractor providing repairs, installations, rewiring, service upgrades and project estimates.'),
 d('signature-landscaping-a15','landscape','Signature Landscaping Services LLC','Landscaping','Mesa / Phoenix / Scottsdale, Arizona','https://signaturelandscapingservices.com/','SignatureLandscapingServicessls@yahoo.com','Public information describes an Arizona landscaping contractor providing irrigation, hardscaping, outdoor living, grading and landscape construction.'),
 d('phoenix-az-landscaping-a15','landscape','Phoenix AZ Landscaping','Landscaping','Phoenix, Arizona','https://phoenixazlandscaping.com/','hi@phoenixazlandscaping.com','Public information describes a Phoenix landscaping business offering desert landscape design, xeriscaping, turf, hardscaping, maintenance and free estimates.'),
 d('tucson-plumbing-a15','plumbing','Tucson Plumbing','Plumbing','Tucson, Arizona','https://tucsonplumbing.com/','dispatcher@tucsonplumbing.com','Public information describes a long-running Tucson plumbing company providing repairs, upgrades, emergency service and scheduled customer service.'),
 d('square-one-construction-a15','construction','Square One Construction','Remodeling and construction','Scottsdale, Arizona','https://www.squareonearizona.com/','hello@squareonearizona.com','Public information describes a Scottsdale remodeling company providing full-home renovations, kitchens, bathrooms, additions and consultation-led projects.'),
 d('ruco-electric-a15','electrical','RUCO Electric','Electrical','Mesa, Arizona','https://www.rucoelectric.com/','Jeff@rucoelectric.com','Public information describes a veteran-owned Mesa electrical contractor providing residential and commercial electrical work and free estimates.'),
 d('home-nice-remodeling-a15','construction','Home Nice Remodeling','Remodeling and construction','Scottsdale, Arizona','https://www.homeniceremodeling.com/','info@homeniceremodeling.com','Public information describes a Scottsdale remodeling contractor providing whole-home, kitchen, bathroom, addition and new-home construction services.'),
 d('prestige-electrical-a15','electrical','Prestige Electrical Contractor LLC','Electrical and HVAC','Mesa, Arizona','https://www.prestigeelectricalcontractor.com/','info@prestigeelectricalcontractor.com','Public information describes a Mesa electrical and HVAC contractor serving residential, commercial, builder and homeowner projects.'),
 d('rattler-electric-a15','electrical','Rattler Electric LLC','Electrical','Mesa / East Valley, Arizona','https://rattlerelectricllc.com/','contact@rattlerelectricllc.com','Public information describes an owner-led Mesa residential electrical contractor offering consultations and electrical service across the East Valley.')
];