export type StarterProject = {
  id: string;
  name: string;
  status: 'active' | 'planning' | 'paused' | 'complete' | 'closed';
  description: string;
  executive: 'Heather' | 'Ethos' | 'Atlas' | 'Eva' | 'Scout' | 'Ledger' | 'Oracle';
  created_at: string;
};

const SEEDED_AT = '2026-08-04T16:00:00.000Z';

export const STARTER_PROJECTS: StarterProject[] = [
{
  id: 'project-app',
  name: 'Aridon AI Executive OS',
  status: 'active',
  description: 'Secure and expand the Aridon command center: Heather Chat, executive team, CRM, projects, tasks, Knowledge Vault, Builder Mode, GitHub/Vercel deployment, and Supabase data recovery.',
  executive: 'Eva',
  created_at: SEEDED_AT,
},
{
  id: 'project-awg-core',
  name: 'AWG-1000 Core Engineering & Prototype',
  status: 'active',
  description: 'Engineer the first containerized atmospheric-water module targeting approximately 1,000 liters/day under site-dependent conditions. Complete DFM, prototype fabrication, FAT, commissioning, and independent performance verification.',
  executive: 'Atlas',
  created_at: SEEDED_AT,
},
{
  id: 'project-awg-gen2',
  name: 'AWG-1000 Gen 2 Capacity Upgrade',
  status: 'planning',
  description: 'Develop the next-generation AWG-1000 architecture with improved airflow, heat rejection, controls, water treatment, energy efficiency, serviceability, and higher site-adjusted output.',
  executive: 'Atlas',
  created_at: SEEDED_AT,
},
{
  id: 'project-manufacturing',
  name: 'AWG-1000 Manufacturing Facility — 10 Units/Month',
  status: 'planning',
  description: 'Design the New Mexico manufacturing operation, tooling, staffing, quality system, floor layout, suppliers, and capital plan required to produce at least ten AWG-1000 modules per month.',
  executive: 'Ledger',
  created_at: SEEDED_AT,
},
{
  id: 'project-sjc',
  name: 'San Juan College Build & Workforce Partnership',
  status: 'active',
  description: 'Create an AWG-1000 prototyping, student training, certification, workforce-development, and eventual production partnership with San Juan College, SBDC, and Enterprise Center.',
  executive: 'Heather',
  created_at: SEEDED_AT,
},
{
  id: 'project-navajo',
  name: 'Navajo Nation Water Resilience Pilot',
  status: 'active',
  description: 'Structure a paid site-qualification and monitored AWG-1000 pilot with resilient power, remote monitoring, O&M, and Tribal workforce participation for a Navajo community or utility.',
  executive: 'Ethos',
  created_at: SEEDED_AT,
},
{
  id: 'project-aztec',
  name: 'Aztec Emergency Water Pilot',
  status: 'active',
  description: 'Develop an interim and supplemental water-supply pilot for Aztec, New Mexico, focused on drought response, public facilities, parks, businesses, and emergency resilience.',
  executive: 'Heather',
  created_at: SEEDED_AT,
},
{
  id: 'project-corpus',
  name: 'Corpus Christi Freshwater Security Pilot',
  status: 'active',
  description: 'Follow up with Corpus Christi leadership on a paid feasibility and AWG-1000 demonstration addressing long-term freshwater supply risk and industrial resilience.',
  executive: 'Heather',
  created_at: SEEDED_AT,
},
{
  id: 'project-willcox',
  name: 'Willcox Arizona Water Augmentation Pilot',
  status: 'planning',
  description: 'Advance the Willcox Active Management Area as the primary Arizona monitored pilot site, with Pinetop-Lakeside/Apache-Sitgreaves as a secondary forest-resilience demonstration.',
  executive: 'Scout',
  created_at: SEEDED_AT,
},
{
  id: 'project-colorado-river',
  name: 'Colorado River Independence Pilot',
  status: 'active',
  description: 'Package verified atmospheric-water production, avoided groundwater withdrawal, resilient power, and a paid feasibility phase for ADWR, WIFA, Tribal authorities, and drought-exposed utilities.',
  executive: 'Ethos',
  created_at: SEEDED_AT,
},
{
  id: 'project-swsa',
  name: 'Southwestern Water Security Alliance',
  status: 'active',
  description: 'Build the multi-state water-and-power sovereignty coalition and compact working group, coordinate state and Tribal leaders, and position Aridon as the operating infrastructure partner.',
  executive: 'Heather',
  created_at: SEEDED_AT,
},
{
  id: 'project-grid-grant',
  name: 'New Mexico Grid Modernization Grant',
  status: 'active',
  description: 'Prepare a partner-led application framing AWG-1000 as integrated water-and-power resilience with storage, monitoring, emergency island operation, and a municipal, Tribal, college, or utility host.',
  executive: 'Scout',
  created_at: SEEDED_AT,
},
{
  id: 'project-unit-fund',
  name: 'New Mexico Unit Fund Southwest Pilot',
  status: 'active',
  description: 'Secure an eligible Catron, Grant, Hidalgo, or Luna County partner for the New Mexico Unit Fund pilot cycle and submit a measurable local-water concept.',
  executive: 'Scout',
  created_at: SEEDED_AT,
},
{
  id: 'project-tribal-drought',
  name: 'USBR Tribal Drought-Resilience Funding',
  status: 'active',
  description: 'Develop a concept paper and eligible Tribal partnership for Bureau of Reclamation drought-resilience funding, including Navajo, Jicarilla Apache, Zuni, Southern Ute, or Ute Mountain Ute pathways.',
  executive: 'Scout',
  created_at: SEEDED_AT,
},
{
  id: 'project-wifa',
  name: 'Arizona WIFA Financing Path',
  status: 'active',
  description: 'Pursue WIFA financing and augmentation-fund eligibility for an AWG/microgrid pilot, beginning with a second-round financing and project-fit inquiry.',
  executive: 'Ledger',
  created_at: SEEDED_AT,
},
{
  id: 'project-cleantech',
  name: '2026 Oil & Gas Cleantech Challenge',
  status: 'active',
  description: 'Complete the application, technical positioning, financial projections, and ten-minute pitch for an industrial AWG-1000 field-validation partnership in Denver on October 7, 2026.',
  executive: 'Heather',
  created_at: SEEDED_AT,
},
{
  id: 'project-h2oasis',
  name: 'H2Oasis Home AWG',
  status: 'planning',
  description: 'Develop the countertop 110V atmospheric-water product derived from AWG-1000, including manufacturer evaluation, landed cost, tariffs, water quality, branding, and crowdfunding path.',
  executive: 'Atlas',
  created_at: SEEDED_AT,
},
{
  id: 'project-million-liters',
  name: 'AWG Farm — 1 Million Liters/Day',
  status: 'planning',
  description: 'Design the modular farm architecture, unit count, power requirements, footprint, operations, maintenance, and economics for one million liters/day of site-adjusted production.',
  executive: 'Atlas',
  created_at: SEEDED_AT,
},
{
  id: 'project-million-gallons',
  name: 'AWG Farm — 1 Million Gallons/Day',
  status: 'planning',
  description: 'Create the separate large-scale deployment framework, infrastructure requirements, phasing, and economics for a one-million-gallon/day atmospheric-water campus.',
  executive: 'Atlas',
  created_at: SEEDED_AT,
},
{
  id: 'project-token',
  name: 'Digital Water Verification & Tokenization',
  status: 'planning',
  description: 'Pressure-test metering, independent verification, baseline, water-rights, securities, custody, retirement, and buyer-demand issues. Keep physical deployment and paid offtake ahead of token issuance.',
  executive: 'Ledger',
  created_at: SEEDED_AT,
},
{
  id: 'project-rain',
  name: 'Humidity Monitoring & Rainfall Enhancement Research',
  status: 'planning',
  description: 'Measure local humidity effects around pilot sites and investigate defensible research partnerships for droplet formation and ground-based rainfall-enhancement concepts.',
  executive: 'Oracle',
  created_at: SEEDED_AT,
},
{
  id: 'project-theron',
  name: 'Theron Zero-Emission Power Integration',
  status: 'planning',
  description: 'Integrate Theron permanent-magnet generation with AWG modules, microgrids, batteries, controls, safety review, engineering validation, and resilient off-grid operation.',
  executive: 'Atlas',
  created_at: SEEDED_AT,
},
{
  id: 'project-investors',
  name: 'Investor & Strategic Partner Pipeline',
  status: 'active',
  description: 'Manage outreach to climate investors, engineering firms, manufacturers, data-center partners, corporate resilience buyers, and federal-capture advisers.',
  executive: 'Heather',
  created_at: SEEDED_AT,
},
{
  id: 'project-tpg',
  name: 'TPG Rise Climate Outreach',
  status: 'active',
  description: 'Advance the Aridon water-resilience package and introduction path to Nicole Brady/TPG Rise Climate, leading with paid feasibility, verified production, and scalable Southwest deployment.',
  executive: 'Heather',
  created_at: SEEDED_AT,
},
{
  id: 'project-state-pilots',
  name: 'Southwestern State Drought Pilot Outreach',
  status: 'active',
  description: 'Maintain one priority AWG-1000 pilot location and responsible drought/water contact for New Mexico, Arizona, Texas, Nevada, Utah, Colorado, California, and nearby states.',
  executive: 'Scout',
  created_at: SEEDED_AT,
},
{
  id: 'project-engineering',
  name: 'Engineering RFP & Independent Verification',
  status: 'active',
  description: 'Recruit engineering, fabrication, water-quality, controls, and third-party verification partners; issue the engineering packet and convert interest into a paid scoped proposal.',
  executive: 'Atlas',
  created_at: SEEDED_AT,
},
{
  id: 'project-federal',
  name: 'Federal Capture & Paid Feasibility Program',
  status: 'active',
  description: 'Turn federal, Tribal, state, and infrastructure opportunities into paid site-qualification studies, fundable scopes, anchor-partner commitments, and compliant grant submissions.',
  executive: 'Scout',
  created_at: SEEDED_AT,
}
];
