export type StarterLead = {
  id: string;
  name: string;
  company: string;
  email: string;
  status: 'new' | 'qualified' | 'active' | 'closed';
  notes: string;
  created_at: string;
};

const SEEDED_AT = '2026-08-04T16:00:00.000Z';

// Restored Aridon pipeline compiled from Jim's prior outreach, pilot packages,
// public agency routing, and active strategic relationships.
export const STARTER_LEADS: StarterLead[] = [
{
  id: 'starter-corpus-manager',
  name: 'Peter Zanoni',
  company: 'City of Corpus Christi',
  email: 'PeterZ@CorpusChristiTX.gov',
  status: 'active',
  notes: 'City Manager • Phone: (361) 826-3220 • AWG-1000 freshwater-security pilot email sent; two-week follow-up path.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-corpus-water',
  name: 'Ashley Marion',
  company: 'Corpus Christi Water',
  email: 'ashleym6@corpuschristiTX.gov',
  status: 'qualified',
  notes: 'Strategic Business Manager • Phone: (361) 826-3706 • Water-supply project and pilot coordination.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-navajo-dwr',
  name: 'Jason John',
  company: 'Navajo Nation Department of Water Resources',
  email: '',
  status: 'qualified',
  notes: 'Department Director • Phone: (928) 729-4003 • Tribal water-resilience and AWG pilot pathway.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-nm-engineer',
  name: 'Mike Hamman',
  company: 'New Mexico Office of the State Engineer',
  email: 'Mike.Hamman@ose.nm.gov',
  status: 'active',
  notes: 'State Engineer • SWSA and Tribal water-rights leadership outreach sent July 27, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-nm-water',
  name: 'Water Use & Conservation Program',
  company: 'New Mexico Office of the State Engineer',
  email: 'water.nm@ose.nm.gov',
  status: 'active',
  notes: 'Phone: (505) 827-6755 • State drought planning, conservation, and public-water-system coordination.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-nm-aztec',
  name: 'District 5 Office',
  company: 'New Mexico Office of the State Engineer',
  email: '',
  status: 'qualified',
  notes: 'Aztec district office • Phone: (505) 383-4571 • Four Corners water-rights and local pilot coordination.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-adwr-director',
  name: 'Tom Buschatzke',
  company: 'Arizona Department of Water Resources',
  email: '',
  status: 'qualified',
  notes: 'Director • Phone: (602) 771-8426 • Arizona drought, Colorado River, and augmentation strategy.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-adwr-general',
  name: 'Arizona Water Planning Team',
  company: 'Arizona Department of Water Resources',
  email: 'crm@azwater.gov',
  status: 'new',
  notes: 'Main line: (602) 771-8500 • Colorado River Independence Pilot, augmentation, conservation, and state routing.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-wifa',
  name: 'Water Infrastructure Finance Authority',
  company: 'WIFA Arizona',
  email: 'contact@azwifa.gov',
  status: 'active',
  notes: 'Phone: (602) 364-1310 • AWG/microgrid financing inquiry and Long-Term Water Augmentation Fund pathway.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-cwcb',
  name: 'Lauren Ris',
  company: 'Colorado Water Conservation Board',
  email: 'lauren.ris@state.co.us',
  status: 'active',
  notes: 'Director • SWSA Colorado leadership outreach sent July 27, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-snwa',
  name: 'John Entsminger',
  company: 'Southern Nevada Water Authority',
  email: 'john.entsminger@snwa.com',
  status: 'active',
  notes: 'General Manager • SWSA Nevada long-term certainty outreach sent July 27, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-wyoming',
  name: 'Brandon Gebhart',
  company: 'Wyoming State Engineer\'s Office',
  email: 'brandon.gebhart@wyo.gov',
  status: 'active',
  notes: 'State Engineer • SWSA senior-water-rights outreach sent July 27, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-az-governor',
  name: 'Governor\'s Constituent Services',
  company: 'State of Arizona',
  email: 'engage@az.gov',
  status: 'active',
  notes: 'SWSA regional water-compact proposal sent July 19, 2026; awaiting routing or response.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-utah-water',
  name: 'Utah Water Resources Director\'s Office',
  company: 'State of Utah',
  email: 'rcarroll@utah.gov',
  status: 'active',
  notes: 'SWSA Utah compact outreach sent July 19, 2026; awaiting routing or response.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-sk',
  name: 'SK Karanam',
  company: 'FlowStateGTM',
  email: 'sk@flowstategtm.com',
  status: 'active',
  notes: 'Federal and Tribal capture adviser • WaterSMART opportunity sent July 22, 2026 • Meeting completed/relationship active.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-ken',
  name: 'Ken Greenberg',
  company: 'Eddy Corporation',
  email: 'kgreenberg@eddycorp.us',
  status: 'active',
  notes: 'Tribal pilots and microgrid-water systems • Introductory call completed • SWSA briefing shared.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-robert',
  name: 'Robert Miller',
  company: 'Tesla3D',
  email: 'tesla3d@outlook.com',
  status: 'qualified',
  notes: 'Technical/strategic connection introduced through Ken Greenberg • SWSA briefing shared.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-paul',
  name: 'Paul Zelizer',
  company: 'New Mexico Climate-Tech Ecosystem',
  email: '',
  status: 'active',
  notes: 'Climate-tech partnerships and capital ecosystem connector • Intro meeting held July 17, 2026.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-erik',
  name: 'Erik Williams',
  company: 'beaded.cloud',
  email: '',
  status: 'qualified',
  notes: 'Aridon strategy/technology meeting held July 17, 2026.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-austin',
  name: 'Austin Burrus',
  company: 'Blue Whale Materials',
  email: '',
  status: 'qualified',
  notes: 'Potential adviser/fractional operator for federal capture, DOE budgets, CapEx, permitting, and financeable Navajo deployment.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-will',
  name: 'Will Wilhelm',
  company: 'Kimley-Horn',
  email: 'will.wilhelm@kimley-horn.com',
  status: 'active',
  notes: 'Southwest water-resources engineering partnership email sent August 3, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-rachel',
  name: 'Rachel Schnorr',
  company: 'Ad Net Zero',
  email: 'rachel.schnorr@adnetzero.com',
  status: 'active',
  notes: 'Zero-emission power and AWG partnership email sent August 3, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-lisa',
  name: 'Lisa Pekarsky',
  company: 'The Children\'s Place',
  email: 'lpekarsky@childrensplace.com',
  status: 'active',
  notes: 'Southwest water and energy resilience pilot email sent August 3, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-joseph',
  name: 'Joseph Dolce',
  company: 'Kyocera Document Solutions America',
  email: 'joseph.dolce@da.kyocera.com',
  status: 'active',
  notes: 'Water and energy sovereignty outreach sent August 3, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-carl',
  name: 'Carl Evers',
  company: 'AGIS Capital',
  email: 'cevers@agiscapital.com',
  status: 'active',
  notes: 'SWSA water-and-power sovereignty discovery-call outreach sent August 3, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-jai',
  name: 'Jai Thattil',
  company: 'Juniper Networks',
  email: 'jthattil@juniper.net',
  status: 'active',
  notes: 'Data-center water and power infrastructure outreach sent August 4, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-tom-green',
  name: 'Tom',
  company: 'GreenEasy Global',
  email: 'tom@greeneasy.global',
  status: 'active',
  notes: 'Southwest water-and-power partnership outreach sent August 4, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-vineeth',
  name: 'Vineeth Jacob',
  company: 'Frontier Communications',
  email: 'vineeth.jacob@ftr.com',
  status: 'active',
  notes: 'Reliable power and water infrastructure outreach sent August 4, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-courtney',
  name: 'Courtney Bachmann',
  company: 'Theory',
  email: 'courtney.bachmann@theory.com',
  status: 'active',
  notes: 'Southwest water-and-power sovereignty outreach sent August 4, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-jane',
  name: 'Jane Potter',
  company: 'Theory',
  email: 'jane.potter@theory.com',
  status: 'active',
  notes: 'Arid-Southwest water-and-power sovereignty outreach sent August 4, 2026; awaiting reply.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-chadette',
  name: 'Chadette Pfaff',
  company: 'New Mexico EMNRD',
  email: 'Chadette.Pfaff@emnrd.nm.gov',
  status: 'qualified',
  notes: 'Phone: (505) 469-6970 • New Mexico Grid Modernization Grant contact; application due August 15, 2026.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-nmfa-sws',
  name: 'Strategic Water Supply Team',
  company: 'New Mexico Finance Authority',
  email: 'SRodriguez@nmfa.net',
  status: 'qualified',
  notes: 'New Mexico Unit Fund Pilot Cycle II and Strategic Water Supply routing • Funding-cycle outreach.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-nmfa-wtb',
  name: 'Water Trust Board Administration',
  company: 'New Mexico Finance Authority',
  email: 'WTBAdmin@nmfa.net',
  status: 'new',
  notes: 'Southwest New Mexico Unit Fund and eligible-partner routing for Catron, Grant, Hidalgo, or Luna counties.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-usbr',
  name: 'Tribal Drought-Resilience Program',
  company: 'U.S. Bureau of Reclamation',
  email: 'dronofo@usbr.gov',
  status: 'qualified',
  notes: 'R26AS00021 Tribal drought-resilience funding • Up to $1 million/project • Navajo, Jicarilla Apache, Zuni, Southern Ute, and Ute Mountain Ute pathways.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-sjc-sbdc',
  name: 'Small Business Development Center',
  company: 'San Juan College',
  email: 'sbdc@sanjuancollege.edu',
  status: 'active',
  notes: 'Phone: (505) 566-3528 • Business planning, capital readiness, government contracting, and manufacturing support.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-sjc-enterprise',
  name: 'Enterprise Center',
  company: 'San Juan College',
  email: 'enterprisecenter@sanjuancollege.edu',
  status: 'qualified',
  notes: 'Phone: (505) 566-3700 • AWG-1000 prototyping, workforce training, and local production partnership.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-4ced',
  name: 'Four Corners Economic Development',
  company: '4CED',
  email: 'info@4cornersed.com',
  status: 'active',
  notes: 'Phone: (505) 566-3702 • Regional manufacturing, site selection, incentives, and partner introductions.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-carol',
  name: 'Carol Holden',
  company: 'University of Arizona Cooperative Extension — Cochise County',
  email: 'carolholden@arizona.edu',
  status: 'qualified',
  notes: 'Phone: (520) 766-3601 • Willcox pilot host and agricultural/community connection.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-sharon',
  name: 'Sharon Megdal',
  company: 'University of Arizona Water Resources Research Center',
  email: 'smegdal@arizona.edu',
  status: 'qualified',
  notes: 'Phone: (520) 621-9591 • Arizona water-policy, augmentation, and independent research pathway.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-cap',
  name: 'Central Arizona Project',
  company: 'CAP',
  email: 'info@cap-az.com',
  status: 'new',
  notes: 'Phone: (623) 869-2333 • Colorado River system, augmentation, and regional water-infrastructure coordination.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-gric',
  name: 'Public Works Department',
  company: 'Gila River Indian Community',
  email: '',
  status: 'new',
  notes: 'Phone: (520) 562-3343 • Tribal infrastructure and water-resilience pilot routing.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-srpmic',
  name: 'Water Resources Department',
  company: 'Salt River Pima-Maricopa Indian Community',
  email: 'PWWaterResources@SRPMIC-nsn.gov',
  status: 'new',
  notes: 'Phone: (480) 362-5600 • Tribal water resources, resilience, and pilot coordination.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-hopi',
  name: 'Water Resources Program',
  company: 'Hopi Tribe',
  email: '',
  status: 'new',
  notes: 'Phone: (928) 734-3712 • Tribal drought-resilience and AWG pilot routing.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-forest',
  name: 'Apache-Sitgreaves National Forests',
  company: 'U.S. Forest Service',
  email: '',
  status: 'new',
  notes: 'Phone: (928) 333-6280 • Secondary Arizona forest-resilience and emergency-water demonstration.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-boardy',
  name: 'Boardy Boardman',
  company: 'Boardy AI',
  email: 'boardy@boardy.ai',
  status: 'active',
  notes: 'Network and introduction partner supporting Aridon federal, Tribal, capital, and strategic relationships.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-nicole',
  name: 'Nicole Brady',
  company: 'TPG Rise Climate',
  email: '',
  status: 'qualified',
  notes: 'Climate investment outreach target • Lead with paid feasibility, verified production, avoided groundwater withdrawal, and scalable Southwest deployment.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-carmen',
  name: 'Carmen Martinez',
  company: 'San Juan College SBDC',
  email: '',
  status: 'qualified',
  notes: 'Local business-development and manufacturing-support contact; prior messages/calls noted.',
  created_at: SEEDED_AT,
},
{
  id: 'starter-tim',
  name: 'Dr. Tim Gibbs',
  company: 'Four Corners Economic Development',
  email: '',
  status: 'qualified',
  notes: 'Regional economic-development, manufacturing, incentives, and partnership contact.',
  created_at: SEEDED_AT,
}
];
