'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Inputs=Record<string,number|boolean>;
type Loaded={lead:any;underwriting:any;evidence:any[];takeover:any[]};
const card:React.CSSProperties={background:'#0D1728',border:'1px solid #263958',borderRadius:15,padding:16};
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#08111F',border:'1px solid #30435F',borderRadius:9,color:'#F8FAFC',padding:'9px 10px'};
const defaults:Inputs={thesis_fit:60,revenue_verified_pct:35,bank_reconciliation_pct:25,tax_return_reconciliation_pct:25,addbacks_verified_pct:30,recurring_revenue_pct:40,gross_margin_stability:55,owner_dependency_pct:70,sop_coverage_pct:20,seller_transition_months:0,key_relationship_transfer_pct:20,top_customer_pct:35,top_five_customer_pct:70,contract_coverage_pct:25,customer_correlation_risk:55,churn_risk:45,normalized_working_capital:0,closing_working_capital:0,ar_over_90_pct:25,inventory_obsolescence_pct:20,seasonality_risk:45,normalized_free_cash_flow:0,annual_debt_service:0,down_payment_pct:10,seller_note_pct:0,sba_prelim_eligible:false,asking_multiple:0,market_low_multiple:0,market_median_multiple:0,market_high_multiple:0,market_disruption_risk:50,government_regulatory_risk:50,cyber_risk:55,tech_transferability:40,critical_employees:0,key_employee_retention_pct:30,role_documentation_pct:25,replacement_difficulty:60,asset_purchase_preference:50,tax_records_readiness:35,purchase_price_allocation_readiness:20,escrow_holdback_pct:0,indemnity_cap_pct:0,reps_warranty_readiness:25,evidence_confidence:25};
const groups:[string,[string,string,string?][]][]=[
 ['Acquisition thesis',[['thesis_fit','Fit to acquisition thesis','%']]],
 ['Quality of Earnings',[['revenue_verified_pct','Revenue verified','%'],['bank_reconciliation_pct','Bank-to-P&L reconciliation','%'],['tax_return_reconciliation_pct','Tax-return reconciliation','%'],['addbacks_verified_pct','Add-backs verified','%'],['recurring_revenue_pct','Recurring revenue','%'],['gross_margin_stability','Gross-margin stability','%']]],
 ['Transferability / owner dependence',[['owner_dependency_pct','Owner dependency risk','%'],['sop_coverage_pct','SOP coverage','%'],['seller_transition_months','Seller transition months','months'],['key_relationship_transfer_pct','Key relationships transferable','%']]],
 ['Customers',[['top_customer_pct','Top customer share','%'],['top_five_customer_pct','Top five customer share','%'],['contract_coverage_pct','Revenue under contract','%'],['customer_correlation_risk','Customer correlation risk','%'],['churn_risk','Churn / renewal risk','%']]],
 ['Working capital',[['normalized_working_capital','Normalized working capital','$'],['closing_working_capital','Expected closing working capital','$'],['ar_over_90_pct','A/R over 90 days','%'],['inventory_obsolescence_pct','Obsolete inventory risk','%'],['seasonality_risk','Seasonality risk','%']]],
 ['Financing',[['normalized_free_cash_flow','Normalized free cash flow','$'],['annual_debt_service','Annual debt service','$'],['down_payment_pct','Down payment','%'],['seller_note_pct','Seller note','%']]],
 ['Market comps',[['asking_multiple','Asking multiple','x'],['market_low_multiple','Market low multiple','x'],['market_median_multiple','Market median multiple','x'],['market_high_multiple','Market high multiple','x']]],
 ['Disruption / regulatory / cyber',[['market_disruption_risk','Market disruption risk','%'],['government_regulatory_risk','Government / regulatory risk','%'],['cyber_risk','Cyber risk','%'],['tech_transferability','Technology transferability','%']]],
 ['People retention',[['critical_employees','Critical employees','count'],['key_employee_retention_pct','Key employee retention likelihood','%'],['role_documentation_pct','Role documentation','%'],['replacement_difficulty','Replacement difficulty','%']]],
 ['Tax & purchase structure readiness',[['asset_purchase_preference','Asset-purchase preference','%'],['tax_records_readiness','Tax records readiness','%'],['purchase_price_allocation_readiness','Purchase-price allocation readiness','%']]],
 ['Risk transfer',[['escrow_holdback_pct','Escrow / holdback','%'],['indemnity_cap_pct','Indemnity cap','%'],['reps_warranty_readiness','Reps & warranties / insurance readiness','%']]],
];
const scoreLabels:Record<string,string>={thesis_fit_score:'Thesis Fit',qoe_score:'Quality of Earnings',transferability_score:'Transferability',customer_risk_score:'Customer Safety',working_capital_score:'Working Capital',financing_score:'Financing',comps_score:'Market Comps',disruption_resilience_score:'Disruption Resilience',regulatory_resilience_score:'Regulatory Resilience',cyber_technology_score:'Cyber / Technology',people_retention_score:'People Retention',tax_structure_readiness_score:'Tax Structure Readiness',risk_transfer_score:'Risk Transfer',evidence_confidence_score:'Evidence Confidence',survivability_score:'Post-Acquisition Survivability',underwriting_score:'Overall Underwriting'};

export default function UnderwritingPage({params}:{params:{id:string}}){
 const [loaded,setLoaded]=useState<Loaded|null>(null);const [values,setValues]=useState<Inputs>(defaults);const [results,setResults]=useState<any>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const [evidence,setEvidence]=useState({category:'Financial',claim:'',source_type:'seller_claim',source_label:'',source_url:'',confidence:50,verified:false});
 async function load(){const r=await fetch(`/api/acquisitions/${params.id}/underwriting`,{cache:'no-store'});const p=await r.json();if(r.ok){setLoaded(p);const stored=p.underwriting?.inputs||{};const next={...defaults,...stored};if(!next.asking_multiple&&p.lead?.asking_price&&p.lead?.estimated_ebitda)next.asking_multiple=p.lead.asking_price/p.lead.estimated_ebitda;setValues(next);setResults(p.underwriting?.results||null);}else setMessage(p.error||'Unable to load underwriting.');}
 useEffect(()=>{load();},[params.id]);
 const set=(key:string,value:number|boolean)=>setValues(v=>({...v,[key]:value}));
 async function run(){setBusy(true);setMessage('Underwriting…');try{const r=await fetch(`/api/acquisitions/${params.id}/underwriting`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inputs:values,generate_takeover_plan:true})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Underwriting failed.');setResults(p.results);setMessage('Underwriting saved and 100-day plan refreshed.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Underwriting failed.');}finally{setBusy(false);}}
 async function addEvidence(){if(!evidence.claim.trim())return setMessage('Enter the claim or fact this evidence supports.');const r=await fetch(`/api/acquisitions/${params.id}/evidence`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(evidence)});const p=await r.json();if(!r.ok){setMessage(p.error||'Could not save evidence.');return;}setEvidence({...evidence,claim:'',source_label:'',source_url:'',confidence:50,verified:false});setMessage('Evidence saved. Re-run underwriting to refresh evidence confidence.');await load();}
 async function taskStatus(id:string,status:string){await fetch(`/api/acquisitions/${params.id}/takeover`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});await load();}
 const decision=results?.decision||loaded?.underwriting?.decision||'needs_data';
 const scoreEntries=useMemo(()=>results?Object.entries(scoreLabels).map(([k,l])=>[l,results[k]] as [string,number]).filter(([,v])=>typeof v==='number'):[],[results]);
 return <main style={{minHeight:'100vh',background:'#07101D',color:'#F8FAFC',fontFamily:'Arial,sans-serif',padding:'24px 18px 70px'}}><div style={{maxWidth:1250,margin:'0 auto'}}>
  <nav style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><strong>ARIDON 3 · UNDERWRITING LAB</strong><div style={{display:'flex',gap:14,flexWrap:'wrap'}}><Link href={`/acquisitions/${params.id}`} style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>Deal Workspace</Link><Link href="/acquisitions/pipeline" style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>Pipeline</Link></div></nav>
  <header style={{padding:'42px 0 20px'}}><div style={{color:'#9EF0CF',fontSize:12,fontWeight:950}}>TRY TO KILL THE BAD DEAL BEFORE IT KILLS THE CAPITAL</div><h1 style={{fontSize:'clamp(38px,6vw,66px)',lineHeight:1,margin:'8px 0 10px'}}>{loaded?.lead?.business_name||'Acquisition'} underwriting</h1><p style={{color:'#AEBBD0',fontSize:17,maxWidth:900,lineHeight:1.6}}>This layer tests sustainable earnings, transferability, customers, working capital, financing, market comps, disruption, government exposure, cyber/technology, people, tax readiness, risk transfer and evidence quality. Scores are decision support, not legal, accounting, lending or tax advice.</p></header>
  {results?<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(175px,1fr))',gap:9,marginBottom:15}}><div style={{...card,borderColor:decision==='buy'?'#55D6A4':decision==='pass'?'#8D3D4B':'#6C7FA0'}}><div style={{color:'#8193AC',fontSize:11,fontWeight:900}}>DECISION</div><div style={{fontSize:23,fontWeight:950,marginTop:5}}>{String(decision).replaceAll('_',' ').toUpperCase()}</div></div>{scoreEntries.map(([label,value])=><div key={label} style={card}><div style={{color:'#8193AC',fontSize:11,fontWeight:900}}>{label}</div><div style={{fontSize:27,fontWeight:950,marginTop:5}}>{Math.round(value)}/100</div></div>)}</section>:null}
  {results?<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:12,marginBottom:15}}><section style={card}><h2 style={{marginTop:0}}>Kill triggers</h2>{results.kill_triggers?.length?<ul>{results.kill_triggers.map((x:string)=><li key={x} style={{marginBottom:8,color:'#FFC0C0'}}>{x}</li>)}</ul>:<p style={{color:'#9EF0CF'}}>No automatic kill trigger is active from the entered data.</p>}</section><section style={card}><h2 style={{marginTop:0}}>Conditions before close</h2><ul>{(results.conditions||[]).map((x:string)=><li key={x} style={{marginBottom:8,color:'#C3CEDD'}}>{x}</li>)}</ul></section><section style={card}><h2 style={{marginTop:0}}>Advisor gates</h2><ul>{(results.advisor_flags||[]).map((x:string)=><li key={x} style={{marginBottom:8,color:'#C3CEDD'}}>{x}</li>)}</ul></section></div>:null}
  <section style={{display:'grid',gap:12}}>{groups.map(([title,fields])=><div key={title} style={card}><h2 style={{margin:'0 0 12px'}}>{title}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(205px,1fr))',gap:10}}>{fields.map(([key,label,unit])=><label key={key} style={{fontSize:13,color:'#C4D0E0'}}>{label}{unit?<span style={{color:'#788BA6'}}> · {unit}</span>:null}<input type="number" step={unit==='x'?0.1:1} style={{...input,marginTop:5}} value={Number(values[key])||''} onChange={e=>set(key,Number(e.target.value)||0)}/></label>)}</div>{title==='Financing'?<label style={{display:'flex',gap:8,alignItems:'center',marginTop:12,color:'#C4D0E0'}}><input type="checkbox" checked={Boolean(values.sba_prelim_eligible)} onChange={e=>set('sba_prelim_eligible',e.target.checked)}/> Preliminary SBA 7(a) eligibility appears plausible. This is not loan approval.</label>:null}</div>)}</section>
  <button onClick={run} disabled={busy} style={{margin:'15px 0',border:0,borderRadius:10,padding:'13px 18px',background:'#9EF0CF',color:'#07101D',fontWeight:950,cursor:'pointer'}}>{busy?'Running…':'Run Full Underwriting + Build 100-Day Plan'}</button>{message?<div style={{color:'#BFD0E5',marginBottom:15}}>{message}</div>:null}
  <section style={{...card,marginBottom:14}}><h2 style={{marginTop:0}}>Evidence confidence ledger</h2><p style={{color:'#AEBBD0'}}>Every important number should have a source. Bank statements, tax returns, contracts, payroll and audited records receive more weight than seller or broker claims.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:9}}><label>Category<input style={{...input,marginTop:5}} value={evidence.category} onChange={e=>setEvidence(v=>({...v,category:e.target.value}))}/></label><label>Claim / fact<input style={{...input,marginTop:5}} value={evidence.claim} onChange={e=>setEvidence(v=>({...v,claim:e.target.value}))}/></label><label>Source type<select style={{...input,marginTop:5}} value={evidence.source_type} onChange={e=>setEvidence(v=>({...v,source_type:e.target.value}))}><option value="seller_claim">Seller claim</option><option value="broker_cim">Broker / CIM</option><option value="accounting">Accounting system</option><option value="bank_statement">Bank statement</option><option value="tax_return">Tax return</option><option value="contract">Contract</option><option value="payroll">Payroll</option><option value="government">Government record</option><option value="lender">Lender record</option></select></label><label>Source label<input style={{...input,marginTop:5}} value={evidence.source_label} onChange={e=>setEvidence(v=>({...v,source_label:e.target.value}))}/></label><label>Confidence 0–100<input type="number" min={0} max={100} style={{...input,marginTop:5}} value={evidence.confidence} onChange={e=>setEvidence(v=>({...v,confidence:Number(e.target.value)||0}))}/></label></div><label style={{display:'flex',gap:8,marginTop:10}}><input type="checkbox" checked={evidence.verified} onChange={e=>setEvidence(v=>({...v,verified:e.target.checked}))}/> Independently verified</label><button onClick={addEvidence} style={{marginTop:10,border:'1px solid #405474',borderRadius:9,padding:'9px 12px',background:'#13223A',color:'#F8FAFC',fontWeight:900,cursor:'pointer'}}>Add Evidence</button><div style={{display:'grid',gap:8,marginTop:12}}>{(loaded?.evidence||[]).map((e:any)=><div key={e.id} style={{borderTop:'1px solid #233550',paddingTop:8}}><strong>{e.category}: {e.claim}</strong><div style={{color:'#8597B0',fontSize:12,marginTop:3}}>{e.source_type} · confidence {e.confidence}/100 · {e.verified?'verified':'not verified'}</div></div>)}</div></section>
  <section style={card}><h2 style={{marginTop:0}}>100-day takeover & value-creation plan</h2><p style={{color:'#AEBBD0'}}>Generated from the underwriting weaknesses, then tracked after closing. Stabilize the base business before accelerating change.</p><div style={{display:'grid',gap:9}}>{(loaded?.takeover||[]).map((t:any)=><div key={t.id} style={{border:'1px solid #2B3E5C',borderRadius:11,padding:11,display:'grid',gridTemplateColumns:'110px minmax(0,1fr) 150px',gap:10,alignItems:'center'}}><strong style={{color:'#9EF0CF'}}>{String(t.phase).replaceAll('_',' ')}</strong><div><strong>{t.task}</strong><div style={{color:'#8597B0',fontSize:12,marginTop:3}}>{t.rationale}</div></div><select value={t.status} onChange={e=>taskStatus(t.id,e.target.value)} style={{...input}}><option value="open">Open</option><option value="in_progress">In progress</option><option value="done">Done</option><option value="blocked">Blocked</option></select></div>)}</div></section>
 </div></main>;
}
