'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { getBrowserClient } from '../../../../lib/supabase';

type Campaign = { id:string; name:string; mode:string; status:string; max_calls_per_day:number };
type Target = { id:string; campaign_id?:string|null; company_name:string; contact_name?:string|null; phone:string; state?:string|null; compliance_status:string; compliance_reason?:string|null; call_status:string; do_not_call:boolean };
type Event = { id:string; status:string; mode:string; summary?:string|null; next_action?:string|null; created_at:string };
type Payload = { configured:boolean; campaigns:Campaign[]; targets:Target[]; events:Event[] };

export default function CallCommandPage({ params }: { params:{slug:string} }) {
  const router = useRouter();
  const [token,setToken]=useState(''); const [data,setData]=useState<Payload|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [name,setName]=useState('B2B Prospect Calls'); const [mode,setMode]=useState<'human_assisted'|'ai_opt_in'>('human_assisted');
  const [company,setCompany]=useState(''); const [phone,setPhone]=useState(''); const [state,setState]=useState('');

  async function load(access:string){ const r=await fetch(`/api/customer/call-command?slug=${encodeURIComponent(params.slug)}`,{headers:{Authorization:`Bearer ${access}`},cache:'no-store'}); const p=await r.json(); if(!r.ok) throw new Error(p.error||'Unable to load Call Command.'); setData(p); }
  useEffect(()=>{ const db=getBrowserClient(); db.auth.getSession().then(async({data:s})=>{ const access=s.session?.access_token||''; if(!access){router.replace(`/customer/login?next=${encodeURIComponent(`/workspace/${params.slug}/call-command`)}`);return;} setToken(access); try{await load(access)}catch(e){setError(e instanceof Error?e.message:'Unable to load.')}})},[params.slug,router]);
  const queued=useMemo(()=>data?.targets.filter(t=>t.call_status==='queued')||[],[data]); const approved=useMemo(()=>data?.targets.filter(t=>t.compliance_status.startsWith('allowed_'))||[],[data]);
  async function post(body:Record<string,unknown>){ setBusy(true);setError('');try{const r=await fetch('/api/customer/call-command',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({slug:params.slug,...body})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Call Command action failed.');await load(token);return p;}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false)}}
  if(!data)return <main style={page}><div style={shell}><h1 style={h1}>Call Command</h1><p>{error||'Loading outbound sales calling…'}</p></div></main>;
  return <main style={page}><div style={shell}>
    <header style={header}><div><div style={eyebrow}>ARIDON · OUTBOUND SALES CALLING</div><h1 style={h1}>Call Command</h1><p style={lead}>Eva coordinates the queue. Ledger scores value. Oracle prepares the opening. Ethos decides whether the call is allowed. Atlas runs telephony. Heather owns follow-through.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link href={`/workspace/${params.slug}/mission-control`} style={outline}>Mission Control</Link><Link href={`/workspace/${params.slug}/digital-humans`} style={mint}>Digital Humans</Link></div></header>

    <section style={stats}><article style={stat}><strong>{data.configured?'READY':'NEEDS TWILIO'}</strong><span>Phone provider</span></article><article style={stat}><strong>{queued.length}</strong><span>Queued targets</span></article><article style={stat}><strong>{approved.length}</strong><span>Ethos-approved</span></article><article style={stat}><strong>{data.events.length}</strong><span>Recorded call events</span></article></section>

    <section style={twoCol}><article style={panel}><div style={label}>CREATE CAMPAIGN</div><h2 style={h2}>Set the sales mission</h2><input value={name} onChange={e=>setName(e.target.value)} style={input}/><select value={mode} onChange={e=>setMode(e.target.value as any)} style={input}><option value="human_assisted">Human-assisted B2B</option><option value="ai_opt_in">AI voice, opt-in only</option></select><button disabled={busy} onClick={()=>void post({action:'create_campaign',name,mode,maxCallsPerDay:20})} style={button}>Create campaign</button><p style={muted}>Human-assisted B2B is the default. AI calling is only available when consent/relationship status supports it.</p></article>
    <article style={panel}><div style={label}>ADD TARGET</div><h2 style={h2}>Queue a public business number</h2><input placeholder="Company" value={company} onChange={e=>setCompany(e.target.value)} style={input}/><input placeholder="Public business phone" value={phone} onChange={e=>setPhone(e.target.value)} style={input}/><input placeholder="State" value={state} onChange={e=>setState(e.target.value)} style={input}/><button disabled={busy||!data.campaigns[0]} onClick={()=>void post({action:'add_target',campaignId:data.campaigns[0]?.id,companyName:company,phone,state,source:'public_business_contact'})} style={button}>Add to compliance queue</button></article></section>

    <section style={panel}><div style={label}>ETHOS PERMISSION GATE</div><h2 style={h2}>No call moves without a recorded reason</h2><div style={stack}>{data.targets.length?data.targets.map(t=><div key={t.id} style={row}><div><strong>{t.company_name}</strong><div style={muted}>{t.phone} {t.state?`· ${t.state}`:''}</div><div style={{fontSize:12,marginTop:4}}>Compliance: <b>{t.compliance_status}</b> · Call: {t.call_status}</div>{t.compliance_reason&&<div style={muted}>{t.compliance_reason}</div>}</div><div style={{display:'flex',gap:7,flexWrap:'wrap',justifyContent:'flex-end'}}>{t.compliance_status==='pending'&&<><button style={small} onClick={()=>void post({action:'set_compliance',targetId:t.id,status:'allowed_human_b2b',reason:'Public B2B business contact. Human-assisted calling only, subject to applicable federal/state rules and local calling-hour checks.'})}>Approve human B2B</button><button style={danger} onClick={()=>void post({action:'set_compliance',targetId:t.id,status:'blocked',reason:'Blocked by Ethos compliance review.'})}>Block</button></>} {t.compliance_status.startsWith('allowed_')&&<button style={small} onClick={async()=>{const p=await post({action:'prepare_call',targetId:t.id}); if(p?.message)setError(p.message)}}>Prepare call</button>} {!t.do_not_call&&<button style={danger} onClick={()=>void post({action:'suppress',phone:t.phone,reason:'Entity-specific do not call request or owner suppression.'})}>Do not call</button>}</div></div>):<p style={muted}>No targets yet.</p>}</div></section>

    <section style={{...panel,marginTop:14,background:'#0D1728',color:'#fff'}}><div style={{...label,color:'#9EF0CF'}}>CONTROLLED AUTONOMY</div><h2 style={h2}>What Aridon will and will not do</h2><p style={{lineHeight:1.7}}>Aridon can research, prioritize, prepare openings, queue calls, record dispositions, create follow-ups, and route human handoffs. It will not invent consent, bypass suppression, spoof caller ID, or autonomously make consequential pricing/legal commitments. If Twilio credentials are missing, the system says so instead of pretending a call happened.</p></section>
    {error&&<div style={errorBox}>{error}</div>}
  </div></main>
}

const page={minHeight:'100vh',background:'#07101D',color:'#F7FAFC',fontFamily:'Arial,sans-serif',padding:'28px 20px 72px'};const shell={maxWidth:1220,margin:'0 auto'};const header={display:'flex',justifyContent:'space-between',gap:20,alignItems:'start',flexWrap:'wrap' as const,marginBottom:22};const eyebrow={color:'#9EF0CF',fontSize:12,fontWeight:950,letterSpacing:1};const h1={fontSize:'clamp(44px,7vw,76px)',lineHeight:.96,letterSpacing:-3,margin:'10px 0 14px'};const h2={fontSize:27,margin:'8px 0 15px'};const lead={color:'#B9C5D6',fontSize:18,lineHeight:1.6,maxWidth:840,margin:0};const stats={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginBottom:14};const stat={background:'#111C2C',border:'1px solid #26364D',borderRadius:14,padding:16,display:'grid',gap:4};const twoCol={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(340px,1fr))',gap:14,marginBottom:14};const panel={background:'#F6F3EB',color:'#171717',borderRadius:18,padding:20,border:'1px solid #D7D0C3'};const label={fontSize:11,fontWeight:950,letterSpacing:1};const input={width:'100%',boxSizing:'border-box' as const,padding:'12px 13px',borderRadius:10,border:'1px solid #CFC6B8',margin:'0 0 9px',background:'#fff'};const button={background:'#0C5D49',color:'#fff',border:0,borderRadius:10,padding:'12px 15px',fontWeight:900,cursor:'pointer'};const small={background:'#E4F4ED',color:'#174D3E',border:'1px solid #A7D5C6',borderRadius:9,padding:'9px 10px',fontWeight:850,cursor:'pointer'};const danger={background:'#FBE9EC',color:'#81283B',border:'1px solid #E7B8C1',borderRadius:9,padding:'9px 10px',fontWeight:850,cursor:'pointer'};const muted={color:'#6A645D',fontSize:13,lineHeight:1.55};const stack={display:'grid',gap:9};const row={background:'#fff',border:'1px solid #D9D1C4',borderRadius:12,padding:13,display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap' as const};const errorBox={background:'#FCE5EA',color:'#7B233A',borderRadius:10,padding:12,marginTop:12};const mint={background:'#9EF0CF',color:'#07130F',padding:'12px 16px',borderRadius:11,textDecoration:'none',fontWeight:950};const outline={border:'1px solid #52627A',color:'#F7FAFC',padding:'11px 15px',borderRadius:11,textDecoration:'none',fontWeight:900};