'use client';
import Link from 'next/link';
import { FormEvent,useState } from 'react';
type Result={website:string;scores:{overall:number;clarity:number;conversion:number;trust:number};opportunities:string[];executiveReview:Array<{executive:string;finding:string}>};
export default function Page(){
 const [website,setWebsite]=useState('');const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function run(e:FormEvent){e.preventDefault();setBusy(true);setError('');setResult(null);try{const r=await fetch('/api/analyze-business',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({website})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Analysis unavailable.');setResult(d);}catch(x){setError(x instanceof Error?x.message:'Analysis unavailable.')}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',background:'#07101D',color:'#F8FAFC',fontFamily:'Arial,sans-serif'}}><section style={{maxWidth:720,margin:'0 auto',padding:'22px 18px 52px'}}><Link href="/mobile-app" style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>← Aridon</Link><h1 style={{fontSize:'clamp(42px,11vw,64px)',lineHeight:.96,letterSpacing:-2.5,margin:'38px 0 12px'}}>Free business scan.</h1><p style={{color:'#B7C4D7',fontSize:17,lineHeight:1.6}}>Paste a public business website and get an executive snapshot. No account or payment required.</p><form onSubmit={run} style={{display:'grid',gap:10,background:'#101B2D',border:'1px solid #2A3B58',borderRadius:18,padding:18,marginTop:20}}><input required inputMode="url" autoCapitalize="none" value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://yourbusiness.com" style={{background:'#081321',color:'#fff',border:'1px solid #3A4D69',borderRadius:12,padding:'14px 13px',fontSize:16}}/><button disabled={busy} style={{border:0,background:'#9EF0CF',color:'#07130F',padding:14,borderRadius:12,fontWeight:950,fontSize:16}}>{busy?'Analyzing…':'Run Free Scan'}</button></form>{error&&<div style={{marginTop:12,color:'#FFD7DF'}}>{error}</div>}{result&&<div style={{display:'grid',gap:12,marginTop:16}}><section style={card}><div style={{color:'#9EF0CF',fontSize:11,fontWeight:950}}>EXECUTIVE SNAPSHOT</div><h2 style={{margin:'8px 0'}}>{result.website}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:8}}><Score n="Overall" v={result.scores.overall}/><Score n="Conversion" v={result.scores.conversion}/><Score n="Trust" v={result.scores.trust}/><Score n="Clarity" v={result.scores.clarity}/></div></section><section style={card}><div style={{color:'#F4D06F',fontSize:11,fontWeight:950}}>TOP OPPORTUNITIES</div>{result.opportunities.slice(0,5).map((x,i)=><p key={i} style={{borderTop:'1px solid #293A55',paddingTop:10,lineHeight:1.55}}><b>{i+1}.</b> {x}</p>)}</section><section style={card}><div style={{color:'#B9CFFF',fontSize:11,fontWeight:950}}>EXECUTIVE READOUT</div>{result.executiveReview.slice(0,5).map((x,i)=><div key={i} style={{borderTop:'1px solid #293A55',padding:'10px 0'}}><b style={{color:'#9EF0CF'}}>{x.executive}</b><div style={{lineHeight:1.55,marginTop:4}}>{x.finding}</div></div>)}</section></div>}</section></main>}
const card={background:'#101B2D',border:'1px solid #2A3B58',borderRadius:18,padding:18} as const;
function Score({n,v}:{n:string;v:number}){return <div style={{background:'#081321',borderRadius:12,padding:13}}><small style={{color:'#91A0B7'}}>{n}</small><strong style={{display:'block',fontSize:30,marginTop:3}}>{v}</strong></div>}
