"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type FundingType = "Grant" | "Loan" | "Cost Share";
type FundingStatus = "Open" | "Watch" | "Planning";
type Opportunity = { name:string; provider:string; providerClass:string; type:FundingType; status:FundingStatus; fit:number; uses:string; missing:string; next:string };

const opportunities:Opportunity[]=[
 {name:"Farm ownership / operating financing",provider:"USDA Farm Service Agency",providerClass:"Public / institutional",type:"Loan",status:"Open",fit:92,uses:"Land, operating capital, equipment and eligible farm needs",missing:"Producer purpose, requested amount and repayment evidence",next:"Complete eligibility screen before any lender disclosure."},
 {name:"Conservation practice assistance",provider:"USDA NRCS",providerClass:"Public / conservation",type:"Cost Share",status:"Watch",fit:88,uses:"Eligible soil, water, grazing and conservation practices",missing:"Practice, location, conservation plan and current ranking period",next:"Map the proposed practice and confirm current official program rules."},
 {name:"Rural energy improvements",provider:"USDA Rural Development",providerClass:"Public / rural development",type:"Grant",status:"Watch",fit:81,uses:"Eligible renewable-energy and energy-efficiency projects",missing:"Energy baseline, scope, ownership and match",next:"Build evidence checklist before application preparation."},
 {name:"State and regional agriculture programs",provider:"State / local agencies",providerClass:"Local institutional",type:"Grant",status:"Planning",fit:74,uses:"Water, resilience, infrastructure, processing and producer-support projects",missing:"State, county, producer type, project objective and current opening",next:"Match geography and need to a verified official program."},
];
const pipeline=['Eligibility screen','Missing evidence','Likely program / lender','Owner approval','Application preparation','Submission approval','Status tracking'];
export default function AgFundingPage(){const[kind,setKind]=useState<"All"|FundingType>("All");const filtered=useMemo(()=>opportunities.filter(i=>kind==="All"||i.type===kind),[kind]);return <main style={{maxWidth:1180,margin:"0 auto",padding:"36px 22px 70px",fontFamily:"system-ui,sans-serif"}}><Link href="/ag/app" style={{color:"inherit"}}>← My 3 Priorities</Link><p style={{marginTop:30,textTransform:"uppercase",letterSpacing:2,fontSize:12}}>Aridon Ag</p><h1 style={{fontSize:46,margin:"6px 0 10px"}}>Money & Funding Workflow</h1><p style={{maxWidth:820,fontSize:19,lineHeight:1.55}}>Funding is not just a search result. Aridon moves a ranch project from eligibility through evidence, owner approval, preparation and status tracking while keeping financial disclosure tightly scoped.</p>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8,margin:"28px 0"}}>{pipeline.map((p,i)=><div key={p} style={{border:"1px solid #bbb",borderRadius:12,padding:13}}><small>STEP {i+1}</small><br/><strong>{p}</strong></div>)}</section>
<section style={{border:"1px solid #bbb",borderRadius:16,padding:22,marginBottom:24}}><h2 style={{marginTop:0}}>Producer funding profile</h2><p>Profile once: location, acreage, crops/livestock, ownership, water and energy needs, equipment, project goals, estimated project cost, available match and preferred financing structure.</p><p><strong>Permission rule:</strong> identifying a possible program does not authorize disclosure. Before a lender, grant writer or funding partner receives context, the owner sees the exact fields, recipient category, purpose and permission duration.</p><p><strong>Guardrail:</strong> Aridon may identify, organize, calculate and draft. It does not submit, borrow, certify facts, accept an award or agree to financial terms without producer approval.</p></section>
<div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:18}}>{(["All","Grant","Loan","Cost Share"] as const).map(item=><button key={item} onClick={()=>setKind(item)} style={{padding:"9px 13px",borderRadius:20,border:"1px solid #aaa",cursor:"pointer"}}>{item}</button>)}</div>
<section style={{display:"grid",gap:14}}>{filtered.map(item=><article key={item.name} style={{border:"1px solid #bbb",borderRadius:16,padding:20}}><div style={{display:"flex",justifyContent:"space-between",gap:18,flexWrap:"wrap"}}><div><small>{item.providerClass} · {item.provider} · {item.type} · {item.status}</small><h3 style={{margin:"6px 0"}}>{item.name}</h3></div><strong>Directional fit {item.fit}/100</strong></div><p><strong>Potential uses:</strong> {item.uses}</p><p><strong>Missing evidence:</strong> {item.missing}</p><p><strong>Next owner-approved step:</strong> {item.next}</p></article>)}</section>
<section style={{marginTop:30,padding:22,border:"1px solid #bbb",borderRadius:16}}><h2 style={{marginTop:0}}>Evidence and privacy rule</h2><p>Amounts, rates, deadlines, eligibility and terms must be verified against the current official source before an opportunity is labeled application-ready. Financial and operational facts stay private unless the producer approves a purpose-limited disclosure.</p></section></main>}
