'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, MapPinned, Scale, ShieldCheck, Search, TriangleAlert } from 'lucide-react';

type StateRule={code:string;name:string;closing:string;foreclosure:string;deed:string;tax:string;notes:string;status:'verified-priority'|'research'};

const priority:Record<string,StateRule>={
  NM:{code:'NM',name:'New Mexico',closing:'Escrow/title-company closing is common; attorney involvement varies by transaction.',foreclosure:'Primarily judicial foreclosure. Confirm current statutory process and timing before relying on it.',deed:'Warranty and special warranty deeds are commonly encountered. Confirm required form, recording and title requirements.',tax:'Property-tax timing, prorations and any transfer-related charges should be confirmed with the county treasurer/assessor and closing agent.',notes:'Use county-level verification for title, recording, tax status, liens, water rights and local requirements.',status:'verified-priority'},
  AZ:{code:'AZ',name:'Arizona',closing:'Escrow/title-company closing is common.',foreclosure:'Deeds of trust and nonjudicial trustee-sale procedures are common. Confirm current notice and cure requirements.',deed:'Warranty, special warranty and beneficiary-related deed forms may appear depending on the deal.',tax:'Confirm property-tax prorations, delinquency status and any local charges with county sources and escrow.',notes:'Verify HOA, special assessments, water/sewer obligations and county recording requirements.',status:'verified-priority'},
  TX:{code:'TX',name:'Texas',closing:'Title-company closing is common.',foreclosure:'Deeds of trust with nonjudicial foreclosure are common, subject to statutory notice and process.',deed:'General warranty, special warranty and other deed forms are used depending on the transaction.',tax:'Confirm county property taxes, prorations, rollback exposure where applicable and closing charges.',notes:'Check municipal utility districts, HOA/POA obligations, floodplain and title exceptions before contracting.',status:'verified-priority'},
  CO:{code:'CO',name:'Colorado',closing:'Title-company closing is common.',foreclosure:'Public-trustee foreclosure framework is distinctive; confirm current process and county procedures.',deed:'General warranty, special warranty and bargain-and-sale forms may be encountered.',tax:'Confirm county property-tax timing and prorations with county and title sources.',notes:'Verify metro-district obligations, water rights, HOA status, special assessments and recording requirements.',status:'verified-priority'}
};

const names=[['AL','Alabama'],['AK','Alaska'],['AZ','Arizona'],['AR','Arkansas'],['CA','California'],['CO','Colorado'],['CT','Connecticut'],['DE','Delaware'],['FL','Florida'],['GA','Georgia'],['HI','Hawaii'],['ID','Idaho'],['IL','Illinois'],['IN','Indiana'],['IA','Iowa'],['KS','Kansas'],['KY','Kentucky'],['LA','Louisiana'],['ME','Maine'],['MD','Maryland'],['MA','Massachusetts'],['MI','Michigan'],['MN','Minnesota'],['MS','Mississippi'],['MO','Missouri'],['MT','Montana'],['NE','Nebraska'],['NV','Nevada'],['NH','New Hampshire'],['NJ','New Jersey'],['NM','New Mexico'],['NY','New York'],['NC','North Carolina'],['ND','North Dakota'],['OH','Ohio'],['OK','Oklahoma'],['OR','Oregon'],['PA','Pennsylvania'],['RI','Rhode Island'],['SC','South Carolina'],['SD','South Dakota'],['TN','Tennessee'],['TX','Texas'],['UT','Utah'],['VT','Vermont'],['VA','Virginia'],['WA','Washington'],['WV','West Virginia'],['WI','Wisconsin'],['WY','Wyoming']];

const states:StateRule[]=names.map(([code,name])=>priority[code]||{code,name,closing:'Research current closing entity and customary practice before contracting.',foreclosure:'Research current judicial/nonjudicial framework and statutory timing.',deed:'Verify commonly used deed forms, execution, notarization and recording requirements.',tax:'Verify property-tax due dates, prorations, transfer taxes/fees and delinquency rules.',notes:'Aridon verification queue: state statute + county recorder/treasurer + licensed title/closing professional.',status:'research'});

const C={bg:'#06101B',panel:'#0B1725',line:'#20344A',text:'#F7FAFC',muted:'#8EA2B8',cyan:'#66D9EF',mint:'#9EF0CF',amber:'#FFC857',red:'#FF7A7A'};

export default function ClosingGuidePage(){
  const [q,setQ]=useState('');
  const [selected,setSelected]=useState('NM');
  const filtered=useMemo(()=>states.filter(s=>`${s.name} ${s.code}`.toLowerCase().includes(q.toLowerCase())),[q]);
  const current=states.find(s=>s.code===selected)||states[0];
  return <main style={{minHeight:'100vh',background:`radial-gradient(circle at 75% -10%,#12325A 0,${C.bg} 38%,#040A11 100%)`,color:C.text,fontFamily:'Arial,sans-serif'}}>
    <style>{`*{box-sizing:border-box}body{margin:0}button,input{font:inherit}@media(max-width:900px){.cg-grid{grid-template-columns:1fr!important}.state-list{max-height:360px!important}}`}</style>
    <header style={{borderBottom:`1px solid ${C.line}`,background:'rgba(4,12,20,.92)',position:'sticky',top:0,zIndex:10}}><div style={{maxWidth:1450,margin:'0 auto',padding:'14px 18px',display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><div style={{fontWeight:1000,letterSpacing:'.09em'}}>ARIDON 50-STATE CLOSING GUIDE</div><div style={{fontSize:10,color:C.muted,marginTop:3}}>MULTIFAMILY · ACQUISITIONS · WHOLESALE COMPLIANCE LAYER</div></div><Link href="/opportunity-map" style={{display:'flex',gap:7,alignItems:'center',color:C.text,textDecoration:'none',fontSize:12,fontWeight:900}}><ArrowLeft size={15}/> Opportunity Map</Link></div></header>

    <section style={{maxWidth:1450,margin:'0 auto',padding:'26px 18px 60px'}}>
      <div style={{maxWidth:950}}><div style={{color:C.cyan,fontSize:11,fontWeight:1000,letterSpacing:'.12em'}}>STATE-BY-STATE TRANSACTION INTELLIGENCE</div><h1 style={{fontSize:'clamp(34px,5vw,58px)',lineHeight:1,margin:'10px 0'}}>Know the closing rules before Eva moves the deal.</h1><p style={{color:C.muted,lineHeight:1.6}}>Aridon now carries a 50-state closing framework for closing entity, foreclosure system, deed/recording issues, tax timing and state-specific diligence. The four Southwest priority states have a practical first-pass reference. The other states stay in a verification queue until current official sources are checked.</p></div>

      <div style={{margin:'18px 0',padding:14,borderRadius:14,border:`1px solid ${C.amber}55`,background:'#2A220E',display:'flex',gap:10,alignItems:'flex-start'}}><TriangleAlert size={19} color={C.amber}/><div><strong style={{fontSize:12}}>LEGAL / CLOSING VERIFICATION GATE</strong><div style={{fontSize:11,color:'#E8DDB8',lineHeight:1.5,marginTop:3}}>This is an operational reference, not legal advice. Before Aridon recommends a binding contract, assignment, foreclosure-related strategy, deed form or closing instruction, the state/county details should be verified with current official sources and a licensed title, escrow or legal professional.</div></div></div>

      <div className="cg-grid" style={{display:'grid',gridTemplateColumns:'330px minmax(0,1fr)',gap:14,alignItems:'start'}}>
        <aside style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:18,padding:12,position:'sticky',top:82}}>
          <div style={{display:'flex',alignItems:'center',gap:8,border:`1px solid ${C.line}`,background:'#07111D',borderRadius:11,padding:'0 10px'}}><Search size={15} color={C.cyan}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search state…" style={{width:'100%',padding:'11px 0',background:'transparent',border:0,outline:0,color:C.text}}/></div>
          <div className="state-list" style={{display:'grid',gap:5,marginTop:10,maxHeight:'72vh',overflowY:'auto'}}>{filtered.map(s=><button key={s.code} onClick={()=>setSelected(s.code)} style={{cursor:'pointer',textAlign:'left',border:`1px solid ${selected===s.code?C.cyan:C.line}`,background:selected===s.code?'#10243A':'#091522',color:C.text,borderRadius:10,padding:'10px 11px',display:'flex',justifyContent:'space-between',gap:8}}><span><strong>{s.code}</strong> · {s.name}</span><span style={{fontSize:9,color:s.status==='verified-priority'?C.mint:C.muted}}>{s.status==='verified-priority'?'PRIORITY':'VERIFY'}</span></button>)}</div>
        </aside>

        <div style={{display:'grid',gap:12}}>
          <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:18,padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start',flexWrap:'wrap'}}><div><div style={{color:C.cyan,fontSize:10,fontWeight:1000}}>SELECTED STATE</div><h2 style={{fontSize:34,margin:'5px 0 0'}}>{current.name} <span style={{color:C.muted}}>({current.code})</span></h2></div><div style={{padding:'8px 10px',borderRadius:999,border:`1px solid ${current.status==='verified-priority'?C.mint:C.amber}66`,color:current.status==='verified-priority'?C.mint:C.amber,fontSize:10,fontWeight:1000}}>{current.status==='verified-priority'?'SOUTHWEST PRIORITY REFERENCE':'VERIFICATION QUEUE'}</div></div></section>

          <Info icon={MapPinned} title="Closing entity / customary close" text={current.closing}/><Info icon={Scale} title="Foreclosure framework" text={current.foreclosure}/><Info icon={ShieldCheck} title="Deed / recording" text={current.deed}/><Info icon={CheckCircle2} title="Tax / transfer timing" text={current.tax}/><Info icon={TriangleAlert} title="Aridon diligence notes" text={current.notes}/>

          <section style={{background:'#07111D',border:`1px solid ${C.line}`,borderRadius:18,padding:18}}><div style={{fontSize:10,color:C.mint,fontWeight:1000,letterSpacing:'.1em'}}>EVA DEAL GATE</div><h3 style={{fontSize:22,margin:'8px 0'}}>Before owner outreach becomes a binding transaction</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:8}}>{['Confirm title/escrow/attorney closing structure','Confirm assignability and wholesaling/licensing rules','Pull title, liens and delinquent taxes','Verify deed and recording requirements','Check foreclosure/pre-foreclosure restrictions','Check transfer taxes and county fees','Verify local HOA/POA/special district obligations','Send final structure through owner approval'].map((x,i)=><div key={x} style={{padding:10,border:`1px solid ${C.line}`,borderRadius:11,color:'#C6D3E0',fontSize:11,lineHeight:1.45}}><strong style={{color:C.cyan}}>{i+1}.</strong> {x}</div>)}</div></section>
        </div>
      </div>
    </section>
  </main>;
}

function Info({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:16,padding:16,display:'grid',gridTemplateColumns:'38px 1fr',gap:11,alignItems:'start'}}><div style={{width:38,height:38,borderRadius:10,display:'grid',placeItems:'center',background:'#102338',color:C.cyan}}><Icon size={18}/></div><div><div style={{fontSize:10,color:C.muted,fontWeight:1000,letterSpacing:'.08em'}}>{title.toUpperCase()}</div><div style={{marginTop:6,lineHeight:1.6,color:'#D6E0EA',fontSize:13}}>{text}</div></div></section>}
