"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Building2, CheckCircle2, Factory, HandCoins, Landmark, Network, Save, Sprout, TestTube2, Users, Waves } from "lucide-react";
import { getBrowserClient } from "../../../../lib/supabase";

const investors=[
  {organization:'Builders Vision',fit:95,role:'Strategic / catalytic anchor',capital:'Flexible capital, direct investment, grants, strategic support',ask:'Anchor the center platform and help shape the food-ag + energy + water investment case.',adds:['Potential direct or catalytic capital','Impact measurement and fundraising support','Food/ag, energy and infrastructure investor network','Technical and strategic assistance'],note:'Best fit for the center as a cross-sector platform. Their public strategy supports food & agriculture, energy, flexible capital, market-building grants and direct investment.'},
  {organization:'The Nest Family Office',fit:92,role:'Regenerative Ag + Water innovation anchor',capital:'Company investment, research, partnerships and catalytic support',ask:'Anchor Building B, the regenerative agriculture + water innovation program, and a producer pilot fund.',adds:['Food/ag technology investment perspective','Farmer resilience and transition-finance expertise','Research and partnership support','Storytelling, evidence and food-system network'],note:'Strong fit for the ag/water side. The center should be pitched as a technology + research + farmer-resilience platform, not simply real estate.'},
  {organization:'Alder Point Capital',fit:72,role:'Working-land / water stewardship partner',capital:'Real-assets capital for climate-resilient farmland and timberland',ask:'Participate if the campus includes investable demonstration farmland, water assets or a regional working-land portfolio.',adds:['Farmland acquisition and asset management','Water stewardship and soil-health operating discipline','Institutional real-assets underwriting','Rural-economy and impact measurement'],note:'Not a natural standalone R&D-building investor. Their public target deal size is larger, so the best fit is an investable land component around the center.'},
  {organization:'Farmland LP',fit:58,role:'Demonstration farm / regional land partner',capital:'Farmland fund capital and operating infrastructure',ask:'Help structure a regional demonstration-farm network and water/irrigation improvement program around the center.',adds:['Farmland portfolio strategy','Water rights and irrigation infrastructure perspective','Farm management and regenerative conversion experience','Real farm economics for field validation'],note:'The center by itself is not their core product. Their strategy seeks large regional farmland portfolios, so use them for the field network rather than the laboratory building.'},
  {organization:'The Conservation Fund',fit:68,role:'Land protection + farmer access partner',capital:'Conservation capital, philanthropy and partnership structures',ask:'Help protect working land around the center, create farmer-access pathways, and connect demonstration projects to long-term conservation.',adds:['Working-land conservation and easement expertise','Farmer land-access models','Corporate and philanthropic partnership structures','Regional food-system and rural-network credibility'],note:'Treat as a strategic conservation partner, not a conventional equity investor in the building.'},
];

const layers=[
  ['Qualifying outside capital','≥ $1M target','Private, philanthropic or federal capital can create the trigger for New Mexico leverage funding.'],
  ['NM Capital Leverage Grant','≥ $1M potential','Advanced-tech companies/research institutions with at least $1M qualifying outside funding can apply for at least $1M in state funds; award is not automatic.'],
  ['LEDA / local economic development','TBD','Potential reimbursement support for qualifying capital investment, jobs, manufacturing and economic-development projects.'],
  ['JTIP workforce support','50–90% wage reimbursement','For eligible new jobs and training. Useful for manufacturing, product testing, R&D scientists, engineers and technical staff; eligibility must be confirmed.'],
  ['Equipment / project finance','TBD','Fabrication, test equipment, AWG production equipment, lab systems, batteries, cooling rigs and other revenue-producing assets.'],
  ['Corporate / university pilots','TBD','Paid pilots, sponsored research, equipment contributions, technical review and third-party validation.'],
];

export default function CenterPage(){
  const [status,setStatus]=useState('');
  const [phaseOne,setPhaseOne]=useState(2500000);
  const [outside,setOutside]=useState(1000000);
  const [stateLeverage,setStateLeverage]=useState(1000000);
  const remaining=useMemo(()=>Math.max(0,phaseOne-outside-stateLeverage),[phaseOne,outside,stateLeverage]);

  async function saveTarget(item:(typeof investors)[number]){
    setStatus(`Saving ${item.organization}…`);
    try{
      const supabase=getBrowserClient();
      const {data:{user}}=await supabase.auth.getUser();
      if(!user){setStatus('Sign in to Aridon to save center capital targets.');return;}
      const {error}=await supabase.from('rd_center_capital_targets').insert({organization:item.organization,fit_score:item.fit,proposed_role:item.role,capital_type:item.capital,status:'target',next_step:item.ask,notes:item.note});
      if(error) throw error;
      setStatus(`${item.organization} added to the center capital pipeline.`);
    }catch(e:any){setStatus(`Save failed: ${e?.message||'unknown error'}`);}
  }

  const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
  const field=(label:string,value:number,setter:(n:number)=>void)=><label style={{display:'grid',gap:6,fontWeight:850,fontSize:13}}>{label}<input type="number" value={value} onChange={e=>setter(Number(e.target.value)||0)} style={{padding:'11px 12px',border:'1px solid #bcc8bd',borderRadius:10,fontSize:16}}/></label>;

  return <main style={{minHeight:'100vh',background:'#f4f1e8',color:'#18251d',fontFamily:'Arial,sans-serif'}}>
    <header style={{background:'#102d25',color:'#fff',padding:'14px 18px'}}><div style={{maxWidth:1180,margin:'auto',display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><Link href="/ag/rd" style={{color:'#fff',textDecoration:'none',fontWeight:950}}>← ARIDON R&D PORTFOLIO</Link><Link href="/ag/regenerative/impact" style={{color:'#c8e2ac',textDecoration:'none',fontWeight:900}}>Impact + Readiness →</Link></div></header>

    <section style={{maxWidth:1180,margin:'auto',padding:'52px 18px 32px'}}><div style={{color:'#356943',fontSize:12,fontWeight:950,letterSpacing:1.2}}>SOUTHWEST R&D + MANUFACTURING CENTER</div><h1 style={{fontSize:'clamp(44px,7vw,76px)',lineHeight:.96,margin:'9px 0 16px'}}>Build the center as a capital stack, not one giant check.</h1><p style={{fontSize:20,lineHeight:1.6,color:'#58655d',maxWidth:930}}>The current planning model combines Aridon’s AI-infrastructure R&D, water systems, AWG prototyping, regenerative agriculture, field validation and workforce development in New Mexico. Final site, square footage and building design remain subject to programming and engineering.</p></section>

    <section style={{maxWidth:1180,margin:'auto',padding:'0 18px 44px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,340px),1fr))',gap:16}}>
      <article style={{background:'#163d2a',color:'#fff',borderRadius:21,padding:22}}><Building2 size={30} color="#c8e2ac"/><div style={{fontSize:12,fontWeight:950,color:'#c8e2ac',marginTop:10}}>BUILDING A</div><h2 style={{fontSize:33,margin:'7px 0 10px'}}>AI Infrastructure + Water Systems Lab</h2><p style={{color:'#dbe8df',lineHeight:1.55}}>Liquid/component cooling, rack electrical resilience, water efficiency, AI controls and digital twins, prototype fabrication, test rigs, supplier qualification and U.S.-manufacturing readiness.</p><div style={{display:'grid',gap:7,marginTop:13}}>{['Cooling and thermal test cells','Electrical / rack resilience lab','Prototype fabrication and metrology','Water-energy integration test loop','Corporate-sponsored validation bays'].map(x=><div key={x} style={{display:'flex',gap:8}}><CheckCircle2 size={17} color="#c8e2ac"/>{x}</div>)}</div></article>
      <article style={{background:'#fff',border:'1px solid #d7e0d5',borderRadius:21,padding:22}}><Sprout size={30} color="#356943"/><div style={{fontSize:12,fontWeight:950,color:'#356943',marginTop:10}}>BUILDING B</div><h2 style={{fontSize:33,margin:'7px 0 10px'}}>Regenerative Agriculture + Water Innovation Center</h2><p style={{color:'#5b675f',lineHeight:1.55}}>AWG-1000 prototyping, precision irrigation, water treatment/storage, farm-energy microgrids, regenerative finance, impact measurement, farmer training, field-trial coordination and investor/lender readiness.</p><div style={{display:'grid',gap:7,marginTop:13}}>{['AWG assembly and sanitary water lab','Regenerative finance + underwriting lab','Farmer / rancher learning studio','Field-trial and sensor command center','University / Extension collaboration space'].map(x=><div key={x} style={{display:'flex',gap:8}}><CheckCircle2 size={17} color="#356943"/>{x}</div>)}</div></article>
    </section>

    <section style={{background:'#fff',borderTop:'1px solid #d7e0d5',borderBottom:'1px solid #d7e0d5',padding:'48px 18px'}}><div style={{maxWidth:1180,margin:'auto'}}><div style={{display:'flex',gap:9,alignItems:'center'}}><HandCoins color="#356943"/><strong style={{color:'#356943'}}>PHASE I CAPITAL MIXER</strong></div><h2 style={{fontSize:40,margin:'8px 0 10px'}}>Use the first private dollar to pull other dollars into the room.</h2><p style={{color:'#5b675f',lineHeight:1.55,maxWidth:900}}>Illustrative planning model only. The current Phase I target is up to $2.5M over roughly 12 months for commissioning, controlled testing, prototype capability and manufacturing readiness.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginTop:20}}>{field('Phase I target',phaseOne,setPhaseOne)}{field('Qualifying outside capital',outside,setOutside)}{field('Illustrative state leverage',stateLeverage,setStateLeverage)}</div><div style={{marginTop:18,padding:19,borderRadius:16,background:'#e6ecdf'}}><div style={{fontSize:12,fontWeight:950,color:'#356943'}}>REMAINING TO FILL</div><div style={{fontSize:38,fontWeight:950}}>{money(remaining)}</div><p style={{marginBottom:0,lineHeight:1.5}}>Fill with strategic corporate pilot capital, founder equity, sponsored research, equipment finance, LEDA/local support, university/federal awards or additional private/philanthropic commitments.</p></div></div></section>

    <section style={{maxWidth:1180,margin:'auto',padding:'50px 18px'}}><div style={{display:'flex',gap:9,alignItems:'center'}}><Landmark color="#356943"/><strong style={{color:'#356943'}}>PUBLIC + PROJECT CAPITAL LAYERS</strong></div><h2 style={{fontSize:38,margin:'8px 0 18px'}}>Do not make the impact investors pay for everything.</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:11}}>{layers.map(([name,amount,why])=><article key={name} style={{background:'#fff',border:'1px solid #d7e0d5',borderRadius:15,padding:17}}><div style={{fontSize:11,fontWeight:950,color:'#356943'}}>{amount}</div><h3 style={{margin:'6px 0 7px'}}>{name}</h3><p style={{margin:0,color:'#5b675f',lineHeight:1.5}}>{why}</p></article>)}</div></section>

    <section style={{background:'#e6ecdf',padding:'50px 18px'}}><div style={{maxWidth:1180,margin:'auto'}}><div style={{display:'flex',gap:9,alignItems:'center'}}><Network color="#356943"/><strong style={{color:'#356943'}}>WHO ADDS WHAT</strong></div><h2 style={{fontSize:40,margin:'8px 0 8px'}}>Five organizations, five different jobs.</h2><p style={{maxWidth:900,color:'#58655d',lineHeight:1.55}}>The mistake would be sending all five the same “fund our building” pitch. The center becomes more financeable when each organization is asked to fund or shape the piece closest to its mandate.</p><div style={{display:'grid',gap:13,marginTop:20}}>{investors.map(item=><article key={item.organization} style={{background:'#fff',border:'1px solid #d2dccf',borderRadius:18,padding:19}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><div style={{fontSize:11,fontWeight:950,color:'#356943'}}>{item.role.toUpperCase()}</div><h3 style={{fontSize:26,margin:'5px 0'}}>{item.organization}</h3></div><div style={{fontSize:30,fontWeight:950,color:'#163d2a'}}>Fit {item.fit}/100</div></div><p><strong>Capital / support:</strong> {item.capital}</p><p><strong>Best first ask:</strong> {item.ask}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:7}}>{item.adds.map(x=><div key={x} style={{display:'flex',gap:7,alignItems:'flex-start'}}><CheckCircle2 size={17} color="#356943"/>{x}</div>)}</div><p style={{color:'#657169',fontSize:13,lineHeight:1.5,marginTop:13}}>{item.note}</p><button onClick={()=>saveTarget(item)} style={{border:0,borderRadius:10,background:'#163d2a',color:'#fff',padding:'11px 13px',fontWeight:900,cursor:'pointer',display:'inline-flex',gap:7,alignItems:'center'}}><Save size={16}/> Add to center pipeline</button></article>)}</div>{status&&<div style={{marginTop:16,padding:13,borderRadius:12,background:'#fff',fontWeight:850}}>{status}</div>}</div></section>

    <section style={{maxWidth:1180,margin:'auto',padding:'50px 18px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:14}}><article style={{background:'#fff',border:'1px solid #d7e0d5',borderRadius:17,padding:19}}><Factory color="#356943"/><h3 style={{fontSize:26,margin:'9px 0'}}>Real estate + manufacturing</h3><p style={{color:'#5b675f',lineHeight:1.55}}>Use industrial/site finance, LEDA/local economic development, equipment finance and strategic corporate capital for the physical shell, test equipment and manufacturing systems.</p></article><article style={{background:'#fff',border:'1px solid #d7e0d5',borderRadius:17,padding:19}}><TestTube2 color="#356943"/><h3 style={{fontSize:26,margin:'9px 0'}}>Research + validation</h3><p style={{color:'#5b675f',lineHeight:1.55}}>Use sponsored research, university collaboration, federal awards and philanthropic capital for trials, instrumentation, independent validation and research staff.</p></article><article style={{background:'#fff',border:'1px solid #d7e0d5',borderRadius:17,padding:19}}><Users color="#356943"/><h3 style={{fontSize:26,margin:'9px 0'}}>Workforce + producer network</h3><p style={{color:'#5b675f',lineHeight:1.55}}>Use JTIP, public educational partners, producer organizations and impact partners for training, apprenticeships, farmer participation and field deployment.</p></article><article style={{background:'#163d2a',color:'#fff',borderRadius:17,padding:19}}><Waves color="#c8e2ac"/><h3 style={{fontSize:26,margin:'9px 0'}}>Water + land demonstration</h3><p style={{color:'#dbe8df',lineHeight:1.55}}>If the center controls adjacent farmland or ranchland, create a separate investable working-land component. That is where Alder Point, Farmland LP and conservation partners become materially more relevant.</p></article></section>
  </main>;
}
