import Link from 'next/link';
import { ArrowLeft, CheckCircle2, QrCode, ShieldCheck, Sprout, Store, Wheat } from 'lucide-react';

const story = [
  ['Farm identity','Who grew it, where it came from and the people behind the operation.'],
  ['Crop & seed','Crop, variety or seed information the producer chooses to publish.'],
  ['Growing practices','Plain-language explanation of soil, crop protection, livestock or regenerative practices.'],
  ['Water & stewardship','Verified or producer-entered water, conservation and resource-management information.'],
  ['Harvest & handling','Harvest timing, handling, certifications and other provenance details when available.'],
  ['Local impact','Optional jobs, local purchasing, community or conservation impact.'],
];

export default function AgTrustPage(){return <main style={{minHeight:'100vh',background:'#f4f1e8',color:'#18251d',fontFamily:'Arial,sans-serif'}}>
<header style={{background:'#163d2a',color:'#fff',padding:'15px 18px'}}><div style={{maxWidth:1120,margin:'auto',display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><Link href="/ag" style={{color:'#fff',textDecoration:'none',display:'inline-flex',alignItems:'center',gap:7,fontWeight:900}}><ArrowLeft size={18}/> Aridon Ag</Link><strong style={{letterSpacing:1.2}}>FARM-TO-CONSUMER TRUST</strong></div></header>
<section style={{maxWidth:1120,margin:'auto',padding:'58px 18px 38px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:26,alignItems:'center'}}><div><div style={{color:'#356943',fontSize:12,fontWeight:950}}>TURN FARM RECORDS INTO A STORY PEOPLE CAN UNDERSTAND</div><h1 style={{fontSize:'clamp(45px,7vw,76px)',lineHeight:.97,letterSpacing:-2.5,margin:'10px 0 18px'}}>Scan the code. Meet the farm.</h1><p style={{fontSize:20,lineHeight:1.6,color:'#536159'}}>Producers already collect records for operations, compliance and management. Aridon can turn the information they choose to share into a simple consumer-facing provenance page without exposing private farm data.</p></div><aside style={{background:'#fff',border:'1px solid #d8e1d5',borderRadius:20,padding:24,textAlign:'center'}}><QrCode size={92} color="#163d2a"/><h2 style={{fontSize:28,margin:'13px 0 7px'}}>One QR code, one verified story.</h2><p style={{color:'#59665f',lineHeight:1.55}}>Use it on packaging, a farm stand, farmers-market sign, restaurant menu, shipment, CSA box or wholesale material.</p></aside></section>
<section style={{maxWidth:1120,margin:'auto',padding:'0 18px 50px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:13}}>{story.map(([title,text],i)=><article key={title} style={{background:'#fff',border:'1px solid #d8e1d5',borderRadius:16,padding:18}}><div style={{width:34,height:34,borderRadius:99,display:'grid',placeItems:'center',background:'#e4eddf',color:'#356943',fontWeight:950}}>{i+1}</div><h2 style={{fontSize:22,margin:'11px 0 6px'}}>{title}</h2><p style={{margin:0,color:'#59665f',lineHeight:1.5}}>{text}</p></article>)}</section>
<section style={{background:'#fff',borderTop:'1px solid #d8e1d5',borderBottom:'1px solid #d8e1d5',padding:'50px 18px'}}><div style={{maxWidth:1000,margin:'auto'}}><div style={{display:'flex',gap:10,alignItems:'center'}}><ShieldCheck size={30} color="#356943"/><h2 style={{fontSize:37,margin:0}}>Trust needs proof and boundaries.</h2></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12,marginTop:20}}>{[
['Producer controlled','Nothing private becomes public unless the owner explicitly chooses to publish it.'],
['Evidence labeled','Verified records, certifications and producer-entered claims are labeled differently instead of being blurred together.'],
['Plain language','Aridon translates agronomic and operational information for consumers without pretending complex farming choices are simple.'],
].map(([title,text])=><div key={title} style={{background:'#faf9f4',border:'1px solid #d8e1d5',borderRadius:14,padding:17}}><CheckCircle2 size={22} color="#356943"/><h3 style={{margin:'10px 0 6px'}}>{title}</h3><p style={{margin:0,color:'#59665f',lineHeight:1.5}}>{text}</p></div>)}</div></div></section>
<section style={{maxWidth:1000,margin:'auto',padding:'52px 18px'}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:14}}><div style={{background:'#163d2a',color:'#fff',borderRadius:18,padding:22}}><Sprout size={28} color="#c8e2ac"/><h2 style={{fontSize:29}}>For producers</h2><p style={{color:'#dbe8df',lineHeight:1.6}}>Show the work behind the product, strengthen direct-market relationships and reuse records already gathered for the operation.</p></div><div style={{background:'#fff',border:'1px solid #d8e1d5',borderRadius:18,padding:22}}><Store size={28} color="#356943"/><h2 style={{fontSize:29}}>For buyers</h2><p style={{color:'#59665f',lineHeight:1.6}}>Retailers, restaurants and consumers get a clearer line of sight into provenance, practices and stewardship without drowning in farm-management data.</p></div><div style={{background:'#fff',border:'1px solid #d8e1d5',borderRadius:18,padding:22}}><Wheat size={28} color="#356943"/><h2 style={{fontSize:29}}>For agriculture</h2><p style={{color:'#59665f',lineHeight:1.6}}>Move the conversation from abstract claims toward specific farms, specific choices and evidence people can explore.</p></div></div></section>
</main>}
