import Link from 'next/link';
import { ArrowRight, BadgeDollarSign, BarChart3, Bot, CheckCircle2, Droplets, Package, Phone, ShieldCheck, Smartphone, Sprout, Tractor, Users } from 'lucide-react';
import AgProfitCheck from './AgProfitCheck';
import AgAcreCalculator from './AgAcreCalculator';

const PHONE='505-360-9529';
const cards=[
  {title:'Sales & Buyers',text:'Track buyers, contracts, repeat orders, quotes and follow-up.',icon:BarChart3},
  {title:'Crop Profitability',text:'See field, crop and per-acre economics so weak margins do not hide.',icon:Sprout},
  {title:'Payroll & Labor',text:'Monitor labor %, overtime, scheduling pressure and crew efficiency.',icon:Users},
  {title:'Inputs & Inventory',text:'Track feed, seed, fertilizer, fuel, parts and working capital.',icon:Package},
  {title:'Water Intelligence',text:'Bring irrigation cost, drought exposure and resilience into the same operating view.',icon:Droplets},
  {title:'Equipment',text:'Stay ahead of maintenance, work orders, downtime and repair-cost patterns.',icon:Tractor},
];

export default function AridonAgPage(){return <main style={{minHeight:'100vh',background:'#f4f7f4',color:'#183b4e',fontFamily:'Arial,sans-serif'}}>
<section style={{background:'linear-gradient(135deg,#062a46,#0a533e 70%,#2d6b43)',color:'#fff',padding:'28px 7% 76px'}}><div style={{maxWidth:1180,margin:'auto'}}>
<nav style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><strong style={{letterSpacing:2,color:'#b9ee91'}}>ARIDON AG</strong><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><a href="#profit-check" style={{color:'#fff',textDecoration:'none',fontWeight:850}}>Free Profit Check</a><a href="#acre-calculator" style={{color:'#fff',textDecoration:'none',fontWeight:850}}>Planting Calculator</a><Link href="/ag/funding" style={{color:'#b9ee91',textDecoration:'none',fontWeight:950}}>Grant & Loan Hunter</Link><Link href="/ag/verified-data" style={{color:'#b9ee91',textDecoration:'none',fontWeight:950}}>Verified Data</Link><a href="tel:+15053609529" style={{color:'#b9ee91',textDecoration:'none',fontWeight:950}}>Call Jim: {PHONE}</a><Link href="/ag/app" style={{color:'#fff',textDecoration:'none',fontWeight:850}}>Farm App</Link><Link href="/ag/install" style={{background:'#b9ee91',color:'#153427',textDecoration:'none',padding:'10px 13px',borderRadius:10,fontWeight:950}}>Install on Phone</Link></div></nav>
<div style={{paddingTop:64,maxWidth:930}}><div style={{fontWeight:950,letterSpacing:1,color:'#b9ee91',fontSize:12}}>THE AI OPERATING SYSTEM FOR THE BUSINESS OF AGRICULTURE</div><h1 style={{fontSize:'clamp(48px,8vw,86px)',lineHeight:.95,letterSpacing:-3,margin:'15px 0 20px'}}>Boost Sales.<br/>Improve Crops.<br/>Control Payroll.<br/><span style={{color:'#b9ee91'}}>Protect Your Water.</span></h1><p style={{fontSize:21,maxWidth:850,lineHeight:1.6,color:'#d8ebe4'}}>Aridon Ag helps farmers and ranchers see where money is being made, where margin is leaking and what to do next across buyers, crops, labor, inputs, equipment, water, funding and verified program data.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:28}}><a href="#profit-check" style={{background:'#b9ee91',color:'#123428',padding:'14px 18px',borderRadius:11,fontWeight:950,textDecoration:'none'}}>Run My Free Farm Profit Check <ArrowRight size={16} style={{verticalAlign:'middle'}}/></a><Link href="/ag/funding" style={{background:'#fff',color:'#0a533e',padding:'14px 18px',borderRadius:11,fontWeight:950,textDecoration:'none'}}><BadgeDollarSign size={16} style={{verticalAlign:'middle',marginRight:6}}/>Find Grants & Loans</Link><a href="tel:+15053609529" style={{border:'1px solid #a9d8c7',color:'#fff',padding:'14px 18px',borderRadius:11,fontWeight:950,textDecoration:'none'}}><Phone size={16} style={{verticalAlign:'middle',marginRight:6}}/>Call Jim: {PHONE}</a><a href="#acre-calculator" style={{border:'1px solid #a9d8c7',color:'#fff',padding:'14px 18px',borderRadius:11,fontWeight:900,textDecoration:'none'}}>Calculate Seeds & Profit / Acre</a><Link href="/ag/app" style={{border:'1px solid #a9d8c7',color:'#fff',padding:'14px 18px',borderRadius:11,fontWeight:900,textDecoration:'none'}}>See the Farm Command Center</Link></div></div>
</div></section>

<section style={{maxWidth:1180,margin:'-34px auto 0',padding:'0 20px'}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{cards.map(({title,text,icon:Icon})=><div key={title} style={{background:'#fff',padding:20,borderRadius:17,border:'1px solid #dce8df',boxShadow:'0 10px 35px #173b2a12'}}><Icon size={25} color="#2e7d32"/><h3 style={{margin:'10px 0 6px'}}>{title}</h3><p style={{margin:0,color:'#607284',lineHeight:1.5,fontSize:14}}>{text}</p></div>)}</div></section>

<section style={{maxWidth:1180,margin:'24px auto 0',padding:'0 20px'}}><Link href="/ag/funding" style={{display:'block',textDecoration:'none',color:'inherit'}}><div style={{background:'linear-gradient(135deg,#143f2d,#0a533e)',color:'#fff',borderRadius:22,padding:28,border:'1px solid #295e51'}}><div style={{display:'grid',gridTemplateColumns:'auto 1fr auto',gap:16,alignItems:'center'}}><div style={{width:54,height:54,borderRadius:15,background:'#b9ee91',display:'grid',placeItems:'center'}}><BadgeDollarSign size={31} color="#153427"/></div><div><div style={{fontSize:12,fontWeight:950,color:'#b9ee91'}}>NEW • DAILY GRANT & LOAN HUNTER</div><h2 style={{fontSize:'clamp(28px,4vw,42px)',margin:'5px 0 8px'}}>Find funding by producer + place + exact need.</h2><p style={{margin:0,color:'#d8ebe4',lineHeight:1.6,maxWidth:900}}>Search county conservation districts, USDA programs, state agriculture and water agencies, Tribal programs, utilities, rural electric cooperatives, lenders and local incentives. Aridon can organize grants, loans, cost share and rebates into a project funding stack.</p></div><ArrowRight size={28} color="#b9ee91"/></div></div></Link></section>

<section style={{maxWidth:1180,margin:'24px auto 0',padding:'0 20px'}}><Link href="/ag/verified-data" style={{display:'block',textDecoration:'none',color:'inherit'}}><div style={{background:'linear-gradient(135deg,#0d314c,#0a533e)',color:'#fff',borderRadius:22,padding:28,border:'1px solid #295e51'}}><div style={{display:'grid',gridTemplateColumns:'auto 1fr auto',gap:16,alignItems:'center'}}><div style={{width:54,height:54,borderRadius:15,background:'#b9ee91',display:'grid',placeItems:'center'}}><ShieldCheck size={30} color="#153427"/></div><div><div style={{fontSize:12,fontWeight:950,color:'#b9ee91'}}>VERIFIED FARM DATA & INCENTIVES</div><h2 style={{fontSize:'clamp(28px,4vw,42px)',margin:'5px 0 8px'}}>Enter farm data once. Put it to work everywhere.</h2><p style={{margin:0,color:'#d8ebe4',lineHeight:1.6,maxWidth:900}}>Turn field, input, fuel, yield and conservation records into reusable evidence for Scope 3 buyer reporting, 45Z supply-chain requests, conservation/cost-share screening, lender packets and audits. Aridon ties the result back to actual farm economics.</p></div><ArrowRight size={28} color="#b9ee91"/></div></div></Link></section>

<section style={{maxWidth:1180,margin:'58px auto',padding:'0 20px'}}><AgProfitCheck/></section>
<section style={{maxWidth:1180,margin:'58px auto',padding:'0 20px'}}><AgAcreCalculator/></section>

<section style={{maxWidth:1180,margin:'64px auto',padding:'0 20px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:14}}>
<div style={{background:'#0d314c',color:'#fff',borderRadius:20,padding:28}}><Bot size={34} color="#b9ee91"/><div style={{fontSize:12,fontWeight:950,color:'#b9ee91',marginTop:12}}>ARIDON AI FARM ADVISOR</div><h2 style={{fontSize:34,margin:'7px 0 10px'}}>What should I do Monday morning?</h2><p style={{lineHeight:1.65,color:'#d7e5ee'}}>Aridon turns operating data into a short priority list: buyers to call, fields to review, overtime to fix, inventory to watch, equipment to service, water risks to address, funding to pursue and program evidence to finish.</p><Link href="/ag/app" style={{display:'inline-block',background:'#b9ee91',color:'#153427',textDecoration:'none',padding:'12px 14px',borderRadius:10,fontWeight:950}}>Open Demo Dashboard</Link></div>
<div style={{background:'#fff',border:'1px solid #dce8df',borderRadius:20,padding:28}}><Smartphone size={34} color="#2e7d32"/><div style={{fontSize:12,fontWeight:950,color:'#2e7d32',marginTop:12}}>FARM APP</div><h2 style={{fontSize:34,margin:'7px 0 10px'}}>Aridon Ag goes to the field.</h2><p style={{lineHeight:1.65,color:'#607284'}}>Install Aridon Ag on supported phones, tablets and computers as a Progressive Web App. Farmers get a dedicated home-screen app while keeping the same account available in a browser.</p><Link href="/ag/install" style={{display:'inline-block',background:'#0a533e',color:'#fff',textDecoration:'none',padding:'12px 14px',borderRadius:10,fontWeight:950}}>Install Aridon Ag</Link></div>
</section>

<section style={{background:'#e5f0e3',padding:'64px 20px'}}><div style={{maxWidth:1080,margin:'auto'}}><div style={{fontSize:12,fontWeight:950,color:'#2e7d32'}}>FOUNDING FARM PROGRAM</div><h2 style={{fontSize:'clamp(38px,5vw,58px)',margin:'8px 0 14px'}}>Prove the value before asking a farmer to commit.</h2><p style={{fontSize:18,lineHeight:1.65,maxWidth:900,color:'#52677a'}}>The launch model is a controlled 90-day founding-farm cohort. Participating farms use Aridon Ag, establish baseline metrics and document useful opportunities in sales, crop economics, labor, inputs, equipment, water, funding and verified program data. Results are reported only where supported by farm data and permission.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10,marginTop:22}}>{['Free Farm Profit Check','Seeds & profit-per-acre calculator','Grant & loan hunter','Verified data & incentive screening','Guided onboarding','30-day action priorities','Mobile farm command center','AI Farm Advisor','ROI and opportunity tracking'].map(x=><div key={x} style={{background:'#fff',padding:15,borderRadius:12,fontWeight:850,display:'flex',gap:8,alignItems:'center'}}><CheckCircle2 size={18} color="#2e7d32"/>{x}</div>)}</div></div></section>

<section style={{maxWidth:1080,margin:'64px auto',padding:'0 20px'}}><div style={{background:'#fff',border:'1px solid #dce8df',borderRadius:22,padding:28}}><div style={{fontSize:12,fontWeight:950,color:'#2e7d32'}}>PRICING DIRECTION</div><h2 style={{fontSize:38,margin:'7px 0 12px'}}>Simple enough to understand. Valuable enough to pay for.</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:12}}><Price title="Farm Profit Check" price="Free" text="Directional scan and opportunity map."/><Price title="Aridon Ag" price="$497/mo" text="Full farm operating system, AI advisor, planning calculators, grant & loan hunter, verified-data workspace and mobile access."/><Price title="Association / Enterprise" price="Custom" text="Farm Bureau, cooperatives, lenders and producer groups."/></div><p style={{fontSize:12,color:'#607284',marginTop:14}}>No revenue, savings, tax-credit, funding or program-eligibility guarantee. Financial and program opportunity estimates are directional until validated against actual records and current program rules.</p></div></section>

<section id="farm-bureau" style={{background:'#0a533e',color:'#fff',padding:'62px 20px'}}><div style={{maxWidth:1000,margin:'auto'}}><div style={{fontWeight:950,color:'#b9ee91',fontSize:12}}>PROPOSED PRODUCER ORGANIZATION PROGRAM</div><h2 style={{fontSize:'clamp(36px,5vw,56px)',margin:'8px 0 12px'}}>One agreement can put Aridon Ag in front of an entire producer community.</h2><p style={{fontSize:18,lineHeight:1.65,color:'#dcebe3'}}>Farm Bureau, commodity groups, co-ops, agricultural lenders and public agriculture organizations can sponsor or negotiate preferred access for member producers, with aggregate pilot reporting and no individual farm data shared without permission.</p><div style={{background:'#fff',color:'#183b4e',borderRadius:15,padding:18,marginTop:20,maxWidth:650}}><div style={{fontSize:12,fontWeight:950,color:'#2e7d32'}}>FARMER SUPPORT & ENROLLMENT</div><div style={{fontSize:24,fontWeight:950,margin:'5px 0'}}>Call Jim Rusk directly: <a href="tel:+15053609529" style={{color:'#0a533e',textDecoration:'none'}}>{PHONE}</a></div><div style={{color:'#607284'}}>Questions about Aridon Ag, the pilot, setup or enrollment come directly to Aridon, not the sponsoring organization.</div></div><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:20}}><a href="tel:+15053609529" style={{background:'#b9ee91',color:'#153427',textDecoration:'none',fontWeight:950,padding:'13px 16px',borderRadius:10}}>Call Jim: {PHONE}</a><Link href="/ag/funding" style={{border:'1px solid #9ccab6',color:'#fff',textDecoration:'none',fontWeight:950,padding:'13px 16px',borderRadius:10}}>View Grant & Loan Hunter</Link><Link href="/ag/app" style={{border:'1px solid #9ccab6',color:'#fff',textDecoration:'none',fontWeight:950,padding:'13px 16px',borderRadius:10}}>View Farmer Experience</Link><Link href="/ag/verified-data" style={{border:'1px solid #9ccab6',color:'#fff',textDecoration:'none',fontWeight:950,padding:'13px 16px',borderRadius:10}}>View Verified Data</Link><Link href="/ag/install" style={{border:'1px solid #9ccab6',color:'#fff',textDecoration:'none',fontWeight:900,padding:'13px 16px',borderRadius:10}}>See Mobile Install</Link></div></div></section>
</main>}

function Price({title,price,text}:{title:string,price:string,text:string}){return <div style={{background:'#f5f8f5',borderRadius:15,padding:19}}><div style={{fontWeight:900}}>{title}</div><div style={{fontSize:31,fontWeight:950,color:'#0a533e',margin:'5px 0'}}>{price}</div><div style={{color:'#607284',lineHeight:1.5,fontSize:14}}>{text}</div></div>}
