import Link from 'next/link';
import { ArrowRight, BarChart3, Bot, CheckCircle2, Droplets, Package, Smartphone, Sprout, Tractor, Users, Landmark } from 'lucide-react';
import AgProfitCheck from './AgProfitCheck';
import AgAcreCalculator from './AgAcreCalculator';

const PHONE='505-360-9529';
const cards=[
  {title:'Sales & Buyers',text:'Track buyers, contracts, repeat orders, quotes and follow-up.',icon:BarChart3},
  {title:'Crop Profitability',text:'See field, crop and per-acre economics so weak margins do not hide.',icon:Sprout},
  {title:'Greenhouse Growing',text:'Track climate, root zone, irrigation, crop work, scouting, harvest and yield by bay or growing zone.',icon:Sprout},
  {title:'Payroll & Labor',text:'Monitor labor %, overtime, scheduling pressure and crew efficiency.',icon:Users},
  {title:'Inputs & Inventory',text:'Track feed, seed, fertilizer, fuel, parts and working capital.',icon:Package},
  {title:'Water Intelligence',text:'Bring irrigation cost, drought exposure and resilience into the same operating view.',icon:Droplets},
  {title:'Equipment',text:'Stay ahead of maintenance, work orders, downtime and repair-cost patterns.',icon:Tractor},
  {title:'Ag Funding',text:'Match farm and ranch projects to grants, loans and cost-share programs, then build the evidence and application plan.',icon:Landmark},
];

export default function AridonAgPage(){return <main style={{minHeight:'100vh',background:'#f4f7f4',color:'#183b4e',fontFamily:'Arial,sans-serif'}}>
<section style={{background:'linear-gradient(135deg,#062a46,#0a533e 70%,#2d6b43)',color:'#fff',padding:'28px 7% 76px'}}><div style={{maxWidth:1180,margin:'auto'}}>
<nav style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><strong style={{letterSpacing:2,color:'#b9ee91'}}>ARIDON AG</strong><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><a href="#profit-check" style={{color:'#fff',textDecoration:'none',fontWeight:850}}>Free Profit Check</a><a href="#acre-calculator" style={{color:'#fff',textDecoration:'none',fontWeight:850}}>Planting Calculator</a><Link href="/ag/funding" style={{color:'#b9ee91',textDecoration:'none',fontWeight:950}}>Loans & Grants</Link><Link href="/ag/greenhouse" style={{color:'#b9ee91',textDecoration:'none',fontWeight:950}}>Greenhouse OS</Link><a href="tel:+15053609529" style={{color:'#b9ee91',textDecoration:'none',fontWeight:950}}>Call Jim: {PHONE}</a><Link href="/ag/app" style={{color:'#fff',textDecoration:'none',fontWeight:850}}>Farm App</Link><Link href="/ag/install" style={{background:'#b9ee91',color:'#153427',textDecoration:'none',padding:'10px 13px',borderRadius:10,fontWeight:950}}>Install on Phone</Link></div></nav>
<div style={{paddingTop:64,maxWidth:930}}><div style={{fontWeight:950,letterSpacing:1,color:'#b9ee91',fontSize:12}}>THE AI OPERATING SYSTEM FOR THE BUSINESS OF AGRICULTURE</div><h1 style={{fontSize:'clamp(48px,8vw,86px)',lineHeight:.95,letterSpacing:-3,margin:'15px 0 20px'}}>Boost Sales.<br/>Improve Crops.<br/>Control Payroll.<br/><span style={{color:'#b9ee91'}}>Protect Your Water.</span></h1><p style={{fontSize:21,maxWidth:850,lineHeight:1.6,color:'#d8ebe4'}}>Aridon Ag helps farmers, ranchers and controlled-environment growers see where money is being made, where margin is leaking and what to do next across buyers, crops, labor, inputs, equipment, water and funding.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:28}}><a href="#profit-check" style={{background:'#b9ee91',color:'#123428',padding:'14px 18px',borderRadius:11,fontWeight:950,textDecoration:'none'}}>Run My Free Farm Profit Check <ArrowRight size={16} style={{verticalAlign:'middle'}}/></a><Link href="/ag/funding" style={{background:'#fff',color:'#0a533e',padding:'14px 18px',borderRadius:11,fontWeight:950,textDecoration:'none'}}>Find Loans & Grants</Link><Link href="/ag/app" style={{border:'1px solid #a9d8c7',color:'#fff',padding:'14px 18px',borderRadius:11,fontWeight:900,textDecoration:'none'}}>See the Farm Command Center</Link></div></div>
</div></section>
<section style={{maxWidth:1180,margin:'-34px auto 0',padding:'0 20px'}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{cards.map(({title,text,icon:Icon})=><div key={title} style={{background:'#fff',padding:20,borderRadius:17,border:'1px solid #dce8df',boxShadow:'0 10px 35px #173b2a12'}}><Icon size={25} color="#2e7d32"/><h3 style={{margin:'10px 0 6px'}}>{title}</h3><p style={{margin:0,color:'#607284',lineHeight:1.5,fontSize:14}}>{text}</p>{title==='Greenhouse Growing'&&<Link href="/ag/greenhouse" style={{display:'inline-block',marginTop:10,color:'#0a533e',fontWeight:950,textDecoration:'none'}}>Open greenhouse →</Link>}{title==='Ag Funding'&&<Link href="/ag/funding" style={{display:'inline-block',marginTop:10,color:'#0a533e',fontWeight:950,textDecoration:'none'}}>Open funding →</Link>}</div>)}</div></section>
<section style={{maxWidth:1180,margin:'58px auto',padding:'0 20px'}}><AgProfitCheck/></section>
<section style={{maxWidth:1180,margin:'58px auto',padding:'0 20px'}}><AgAcreCalculator/></section>
<section style={{maxWidth:1180,margin:'64px auto',padding:'0 20px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:14}}><div style={{background:'#0d314c',color:'#fff',borderRadius:20,padding:28}}><Bot size={34} color="#b9ee91"/><div style={{fontSize:12,fontWeight:950,color:'#b9ee91',marginTop:12}}>ARIDON AI FARM ADVISOR</div><h2 style={{fontSize:34,margin:'7px 0 10px'}}>What should I do Monday morning?</h2><p style={{lineHeight:1.65,color:'#d7e5ee'}}>Aridon turns operating data into a short priority list: buyers to call, fields to review, overtime to fix, inventory to watch, equipment to service, water risks to address and funding opportunities worth checking.</p><Link href="/ag/app" style={{display:'inline-block',background:'#b9ee91',color:'#153427',textDecoration:'none',padding:'12px 14px',borderRadius:10,fontWeight:950}}>Open Demo Dashboard</Link></div><div style={{background:'#fff',border:'1px solid #dce8df',borderRadius:20,padding:28}}><Smartphone size={34} color="#2e7d32"/><div style={{fontSize:12,fontWeight:950,color:'#2e7d32',marginTop:12}}>FARM APP</div><h2 style={{fontSize:34,margin:'7px 0 10px'}}>Aridon Ag goes to the field.</h2><p style={{lineHeight:1.65,color:'#607284'}}>Install Aridon Ag on supported phones, tablets and computers as a Progressive Web App while keeping the same account available in a browser.</p><Link href="/ag/install" style={{display:'inline-block',background:'#0a533e',color:'#fff',textDecoration:'none',padding:'12px 14px',borderRadius:10,fontWeight:950}}>Install Aridon Ag</Link></div></section>
<section style={{background:'#e5f0e3',padding:'64px 20px'}}><div style={{maxWidth:1080,margin:'auto'}}><div style={{fontSize:12,fontWeight:950,color:'#2e7d32'}}>FOUNDING FARM PROGRAM</div><h2 style={{fontSize:'clamp(38px,5vw,58px)',margin:'8px 0 14px'}}>Prove the value before asking a grower to commit.</h2><p style={{fontSize:18,lineHeight:1.65,maxWidth:900,color:'#52677a'}}>Participating farms establish baseline metrics and document useful opportunities in sales, crop economics, labor, inputs, equipment, water and funding. Results are reported only where supported by farm data and permission.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10,marginTop:22}}>{['Free Farm Profit Check','Seeds & profit-per-acre calculator','Loans, grants & cost-share matching','Guided onboarding','30-day action priorities','Mobile farm command center','AI Farm Advisor','ROI and opportunity tracking'].map(x=><div key={x} style={{background:'#fff',padding:15,borderRadius:12,fontWeight:850,display:'flex',gap:8,alignItems:'center'}}><CheckCircle2 size={18} color="#2e7d32"/>{x}</div>)}</div></div></section>
</main>}
