'use client';

import { FormEvent, useMemo, useState } from 'react';
import Link from 'next/link';
import { CheckCircle2, Truck } from 'lucide-react';
import { getBrowserClient } from '../../../../../lib/supabase';

export default function S3CompanyIntake(){
 const db=useMemo(()=>getBrowserClient(),[]); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [message,setMessage]=useState('');
 const [form,setForm]=useState({company_name:'',contact_name:'',contact_email:'',contact_phone:'',grain:'',quantity:'',unit:'bushels',pickup_address:'',ready_date:'',notes:''});
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');const {error}=await db.rpc('submit_s3_grain_offer',{company_name:form.company_name.trim(),contact_name:form.contact_name.trim(),contact_email:form.contact_email.trim(),contact_phone:form.contact_phone.trim(),grain:form.grain.trim(),quantity:Number(form.quantity)||0,unit:form.unit.trim()||'bushels',pickup_address:form.pickup_address.trim(),ready_date:form.ready_date||null,notes:form.notes.trim()});setBusy(false);if(error){setMessage('We could not submit the pickup notice. Please check the required fields and try again.');return;}setDone(true);}
 if(done)return <main style={center}><div style={card}><CheckCircle2 size={42}/><h1> S3 has been notified.</h1><p style={muted}>Your grain-ready notice is now in the private S3 dispatch queue. S3 will decide and coordinate the pickup. Submitting this form does not create a shipping, purchase or pricing commitment.</p><button onClick={()=>{setDone(false);setForm({company_name:'',contact_name:'',contact_email:'',contact_phone:'',grain:'',quantity:'',unit:'bushels',pickup_address:'',ready_date:'',notes:''})}} style={btn}>Submit another notice</button></div></main>;
 return <main style={center}><div style={{width:'100%',maxWidth:720}}><Link href="/ag/pilot/s3" style={{color:'#356943',fontWeight:900,textDecoration:'none'}}>← S3 pilot</Link><div style={{...card,marginTop:12}}><div style={eyebrow}>S3 LEGACY RANCH · GRAIN PICKUP INTAKE</div><div style={{display:'flex',gap:10,alignItems:'center'}}><Truck size={34}/><h1 style={{fontSize:38,margin:'12px 0'}}>Tell S3 your grain is ready.</h1></div><p style={muted}>This page is for companies and organizations that have grain available for S3 to collect. S3 receives the information privately and coordinates the pickup. You cannot see S3 inventory, routes, financials or other company submissions.</p><form onSubmit={submit} style={{display:'grid',gap:10}}><div style={grid}><label style={label}>Company *<input required value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})} style={input}/></label><label style={label}>Contact name<input value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})} style={input}/></label><label style={label}>Email<input type="email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})} style={input}/></label><label style={label}>Phone<input value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})} style={input}/></label><label style={label}>Grain *<input required value={form.grain} onChange={e=>setForm({...form,grain:e.target.value})} placeholder="Corn, wheat, barley…" style={input}/></label><label style={label}>Quantity<input type="number" min="0" step="any" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} style={input}/></label><label style={label}>Unit<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} style={input}/></label><label style={label}>Ready date<input type="date" value={form.ready_date} onChange={e=>setForm({...form,ready_date:e.target.value})} style={input}/></label></div><label style={label}>Pickup address *<input required value={form.pickup_address} onChange={e=>setForm({...form,pickup_address:e.target.value})} style={input}/></label><label style={label}>Pickup notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} style={{...input,minHeight:90}} placeholder="Hours, dock instructions, loading equipment, special access…"/></label>{message&&<div style={notice}>{message}</div>}<button disabled={busy} style={btn}>{busy?'Sending to S3…':'Notify S3 grain is ready'}</button></form><p style={{...muted,fontSize:12,marginTop:14}}>This form is an operational pickup notice only. It does not establish price, ownership, exclusivity, transportation terms or any other binding commercial agreement.</p></div></div></main>;
}

const center:React.CSSProperties={minHeight:'100vh',background:'#f4f1e8',display:'grid',placeItems:'center',padding:20,fontFamily:'Arial,sans-serif',color:'#17241c'}; const card:React.CSSProperties={background:'#fff',border:'1px solid #d7dfd4',borderRadius:20,padding:22}; const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}; const label:React.CSSProperties={display:'grid',gap:5,fontSize:12,fontWeight:900}; const input:React.CSSProperties={border:'1px solid #cfd8cc',borderRadius:9,padding:'11px',fontSize:15,fontFamily:'inherit'}; const btn:React.CSSProperties={border:0,borderRadius:10,padding:'12px 14px',background:'#163d2a',color:'#fff',fontWeight:900,cursor:'pointer'}; const muted:React.CSSProperties={color:'#667169',lineHeight:1.6}; const eyebrow:React.CSSProperties={color:'#356943',fontSize:12,fontWeight:950,letterSpacing:.7}; const notice:React.CSSProperties={background:'#fff5d8',border:'1px solid #e2ca78',padding:11,borderRadius:10};
