import Link from 'next/link';
import { ArrowLeft, ArrowRight, Droplets, Leaf, Newspaper, PiggyBank, Radar, Tractor, Wheat } from 'lucide-react';

const lanes = [
  {title:'Technology & AI', icon:Radar, detail:'Turn new tools, automation, sensors and AI into a practical fit check for your operation.'},
  {title:'Water', icon:Droplets, detail:'Watch irrigation, drought, water policy and conservation signals, then connect them to field-level decisions.'},
  {title:'Soil & Regenerative', icon:Leaf, detail:'Compare practices using soil, input-cost, resilience and profitability outcomes instead of slogans.'},
  {title:'Seeds & Crops', icon:Wheat, detail:'Track varieties, crop protection, disease pressure, seed partners and crop-management changes.'},
  {title:'Equipment', icon:Tractor, detail:'Filter machinery and precision-tech news by acreage, labor, payback period and operational fit.'},
  {title:'Money & Funding', icon:PiggyBank, detail:'Connect farm-economy news, grants, lending and cost pressure to the funding workflow already inside Aridon.'},
];

const sources = [
  ['Farm Progress','Target editorial/content partner','Agricultural technology, water, soil health, farm business, equipment and farmer adoption signals.'],
  ['Public agencies','Source lane','USDA, NRCS, Extension, state water/ag agencies and public funding notices.'],
  ['Partner network','Opt-in lane','Seed, equipment, agronomy, finance, water and research partners approved for the operation.'],
];

export default function AgIntelligencePage(){return <main style={{minHeight:'100vh',background:'#f4f1e8',color:'#18251d',fontFamily:'Arial,sans-serif'}}>
<header style={{background:'#163d2a',color:'#fff',padding:'15px 18px'}}><div style={{maxWidth:1120,margin:'auto',display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><Link href="/ag" style={{color:'#fff',textDecoration:'none',display:'inline-flex',alignItems:'center',gap:7,fontWeight:900}}><ArrowLeft size={18}/> Aridon Ag</Link><strong style={{letterSpacing:1.3}}>FARM INTELLIGENCE</strong></div></header>
<section style={{maxWidth:1120,margin:'auto',padding:'56px 18px 36px'}}><div style={{maxWidth:860}}><div style={{color:'#356943',fontSize:12,fontWeight:950,letterSpacing:.9}}>RAW RADAR → OWNER DECISION</div><h1 style={{fontSize:'clamp(44px,7vw,74px)',lineHeight:.98,letterSpacing:-2.4,margin:'10px 0 18px'}}>News is useful only when it changes what you do next.</h1><p style={{fontSize:20,lineHeight:1.6,color:'#536159'}}>Aridon filters agriculture information by operation, geography, season, economics and urgency. The result is not another news feed. It is a short list of signals that may deserve a decision.</p></div></section>
<section style={{maxWidth:1120,margin:'auto',padding:'0 18px 48px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:13}}>{lanes.map(({title,icon:Icon,detail})=><article key={title} style={{background:'#fff',border:'1px solid #d8e1d5',borderRadius:17,padding:19}}><Icon size={27} color="#356943"/><h2 style={{fontSize:23,margin:'12px 0 7px'}}>{title}</h2><p style={{margin:0,color:'#59665f',lineHeight:1.55}}>{detail}</p></article>)}</section>
<section style={{background:'#fff',borderTop:'1px solid #d8e1d5',borderBottom:'1px solid #d8e1d5',padding:'50px 18px'}}><div style={{maxWidth:1120,margin:'auto'}}><div style={{display:'flex',gap:10,alignItems:'center'}}><Newspaper size={28} color="#356943"/><div><div style={{color:'#356943',fontSize:12,fontWeight:950}}>SOURCE REGISTRY</div><h2 style={{fontSize:36,margin:'3px 0'}}>Transparent sources, permission-aware use.</h2></div></div><p style={{maxWidth:820,color:'#59665f',lineHeight:1.6}}>Aridon should cite the original publisher, link farmers back to the source and use licensed feeds or partnership terms when full-text content is involved. We want the intelligence, not someone else’s newspaper copied into our product.</p><div style={{display:'grid',gap:10,marginTop:18}}>{sources.map(([name,status,detail])=><div key={name} style={{border:'1px solid #d8e1d5',borderRadius:14,padding:16,display:'grid',gridTemplateColumns:'minmax(150px,.7fr) minmax(170px,.8fr) 2fr',gap:12,alignItems:'start'}}><strong>{name}</strong><span style={{color:'#356943',fontWeight:850}}>{status}</span><span style={{color:'#59665f'}}>{detail}</span></div>)}</div></div></section>
<section style={{maxWidth:980,margin:'auto',padding:'54px 18px'}}><div style={{background:'#163d2a',color:'#fff',borderRadius:20,padding:26}}><div style={{color:'#c8e2ac',fontSize:12,fontWeight:950}}>EXAMPLE OUTPUT</div><h2 style={{fontSize:34,margin:'8px 0 12px'}}>“This irrigation story may matter to your north field.”</h2><p style={{color:'#dbe8df',fontSize:18,lineHeight:1.6}}>Aridon can explain why it matters, estimate the economics, identify funding or vendors, show confidence and ask whether you want to investigate further. The owner stays in control of every outside action.</p><Link href="/ag/trust" style={{display:'inline-flex',alignItems:'center',gap:8,marginTop:14,color:'#163d2a',background:'#fff',padding:'13px 16px',borderRadius:11,textDecoration:'none',fontWeight:950}}>See the Farm-to-Consumer Trust Layer <ArrowRight size={18}/></Link></div></section>
</main>}
