import { NextRequest, NextResponse } from 'next/server';
import { base64UrlMessage, decryptToken, refreshGoogleAccessToken, safeHeader } from '../../../../lib/gmail';
import { upcomingCalendarEvents } from '../../../../lib/googleWorkspace';
import { scoreAttention, type AttentionLead } from '../../../../lib/relationshipBrain';
import { STARTER_LEADS } from '../../../../lib/starterLeads';
import { getServerClient } from '../../../../lib/supabase';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const NO_STORE = { 'Cache-Control': 'no-store' };

function authorizedCron(request: NextRequest) {
  const secret = process.env.CRON_SECRET?.trim();
  if (!secret) return true;
  return request.headers.get('authorization') === `Bearer ${secret}`;
}

function startValue(event: any) {
  return event?.start?.dateTime || event?.start?.date || '';
}

function leadKey(lead: { name?: string | null; company?: string | null; email?: string | null }) {
  const email = String(lead.email || '').trim().toLowerCase();
  if (email) return `email:${email}`;
  return `name:${String(lead.name || '').trim().toLowerCase()}|company:${String(lead.company || '').trim().toLowerCase()}`;
}

function starterRelationship(lead: (typeof STARTER_LEADS)[number]): AttentionLead {
  return {
    ...lead,
    phone: null,
    title: null,
    priority: lead.status === 'qualified' ? 'high' : 'medium',
    next_action: null,
    last_contact_at: lead.created_at,
    next_follow_up_at: null,
    relationship_score: lead.status === 'qualified' ? 35 : lead.status === 'active' ? 28 : 12,
    social_handle: null,
    social_url: null,
  };
}

function combineRelationships(live: AttentionLead[]) {
  const liveKeys = new Set(live.map(leadKey));
  const restored = STARTER_LEADS
    .filter((lead) => lead.status !== 'closed' && !liveKeys.has(leadKey(lead)))
    .map(starterRelationship);
  return [...live, ...restored];
}

function formatBrief(attention: any[], opportunities: any[], calendar: any[]) {
  const lines: string[] = [];
  lines.push('ARIDON · EVA MORNING RELATIONSHIP BRIEF');
  lines.push(new Date().toLocaleString('en-US', { timeZone: 'America/Denver', dateStyle: 'full', timeStyle: 'short' }));
  lines.push('');

  lines.push(`NEEDS ATTENTION · ${attention.length}`);
  if (!attention.length) lines.push('No urgent relationship follow-ups surfaced this morning.');
  for (const item of attention.slice(0, 8)) {
    const who = [item.name, item.company].filter(Boolean).join(' · ');
    const why = item.reasons?.slice(0, 2).join(', ') || 'relationship review';
    lines.push(`• ${who} — ${item.recommendedNextAction} (${why})`);
  }
  lines.push('');

  lines.push(`ACTIVE OPPORTUNITIES · ${opportunities.length}`);
  if (!opportunities.length) lines.push('No qualified or active opportunities are currently in the relationship queue.');
  for (const item of opportunities.slice(0, 6)) {
    lines.push(`• ${[item.name, item.company].filter(Boolean).join(' · ')} — ${item.next_action || item.recommendedNextAction}`);
  }
  lines.push('');

  lines.push(`NEXT 48 HOURS · ${calendar.length} CALENDAR ITEM${calendar.length === 1 ? '' : 'S'}`);
  if (!calendar.length) lines.push('No upcoming Google Calendar events found.');
  for (const event of calendar.slice(0, 8)) {
    const when = startValue(event);
    const formatted = when ? new Date(when).toLocaleString('en-US', { timeZone: 'America/Denver', dateStyle: 'short', timeStyle: 'short' }) : 'Time not set';
    lines.push(`• ${formatted} — ${event.summary || 'Calendar event'}`);
  }
  lines.push('');
  lines.push('Eva recommendation: clear the first three relationship actions before opening a new outbound lane.');
  lines.push('Generated by Aridon Relationship Brain.');
  return lines.join('\n');
}

async function run(request: NextRequest, manual: boolean) {
  try {
    if (!manual && !authorizedCron(request)) {
      return NextResponse.json({ error: 'Unauthorized cron request.' }, { status: 401, headers: NO_STORE });
    }

    const db = getServerClient();
    const [{ data: settings }, { data: integration, error: tokenError }, { data: dbLeads, error: leadError }] = await Promise.all([
      db.from('relationship_settings').select('*').eq('id', 1).maybeSingle(),
      db.from('executive_integration_tokens').select('account_label,encrypted_refresh_token').eq('provider', 'google-workspace').maybeSingle(),
      db.from('leads').select('id,name,company,email,status,priority,notes,next_action,last_contact_at,next_follow_up_at,relationship_score').neq('status', 'closed').limit(1000),
    ]);
    if (tokenError) throw tokenError;
    if (leadError) throw leadError;
    if (!manual && settings?.daily_brief_enabled === false) {
      return NextResponse.json({ sent: false, reason: 'Daily Relationship Brain brief is turned off.' }, { headers: NO_STORE });
    }
    if (!integration?.encrypted_refresh_token) {
      return NextResponse.json({ sent: false, error: 'Reconnect Google Workspace once to enable scheduled brief delivery.' }, { status: 409, headers: NO_STORE });
    }

    const recipient = safeHeader(settings?.brief_recipient || integration.account_label || '', 254);
    if (!recipient || !/^\S+@\S+\.\S+$/.test(recipient)) {
      return NextResponse.json({ sent: false, error: 'Set a valid briefing recipient in Relationship Brain.' }, { status: 400, headers: NO_STORE });
    }

    const leads = combineRelationships((dbLeads || []) as AttentionLead[]);
    const ranked = leads.map((lead: any) => ({
      ...lead,
      ...scoreAttention(lead),
    })).map((item: any) => ({
      ...item,
      attentionScore: item.score,
      recommendedNextAction: item.nextAction,
    })).sort((a: any, b: any) => b.attentionScore - a.attentionScore);
    const attention = ranked.filter((item: any) => item.attentionScore >= 35).slice(0, 20);
    const opportunities = ranked.filter((item: any) => ['qualified', 'active'].includes(String(item.status || '').toLowerCase())).slice(0, 20);

    const accessToken = await refreshGoogleAccessToken(decryptToken(integration.encrypted_refresh_token));
    let calendar: any[] = [];
    try { calendar = await upcomingCalendarEvents(accessToken, 48); } catch (calendarError) { console.error('Relationship brief calendar read failed', calendarError); }
    const body = formatBrief(attention, opportunities, calendar);
    const subject = safeHeader(`Aridon Relationship Brief · ${new Date().toLocaleDateString('en-US', { timeZone: settings?.daily_brief_timezone || 'America/Denver' })}`, 180);
    const raw = [
      `To: ${recipient}`,
      `Subject: ${subject}`,
      'MIME-Version: 1.0',
      'Content-Type: text/plain; charset=UTF-8',
      'Content-Transfer-Encoding: 8bit',
      '',
      body,
    ].join('\r\n');

    const response = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
      method: 'POST',
      headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ raw: base64UrlMessage(raw) }),
      cache: 'no-store',
    });
    const result = await response.json() as { id?: string; error?: { message?: string } };
    if (!response.ok) throw new Error(result.error?.message || 'Gmail did not send the Relationship Brain brief.');

    return NextResponse.json({ sent: true, recipient, messageId: result.id || null, needsAttention: attention.length, activeOpportunities: opportunities.length, calendarItems: calendar.length }, { headers: NO_STORE });
  } catch (error) {
    console.error('Relationship Brain daily brief error', error);
    return NextResponse.json({ sent: false, error: error instanceof Error ? error.message : 'Unable to send the Relationship Brain brief.' }, { status: 500, headers: NO_STORE });
  }
}

export async function GET(request: NextRequest) { return run(request, false); }
export async function POST(request: NextRequest) { return run(request, true); }
