'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Lead={id:string;business_name:string;industry:string;city:string;state:string;stage:string;asking_price:number;estimated_ebitda:number;thesis_fit_score:number;next_follow_up_at:string|null;score?:{overall_score:number;recommendation:string}|null};
type Payload={leads:Lead[];metrics:{total:number;hot:number;negotiating:number;loiPending:number;diligence:number;closeReady:number;followUpsDue:number};thesis?:{id:string;name:string;criteria:any}|null};
const stages=[['lead_captured','Lead Captured'],['reviewing','Reviewing'],['qualified','Qualified'],['contact_strategy_ready','Contact Ready'],['negotiating','Negotiating'],['loi_drafted','LOI Drafted'],['loi_sent','LOI Sent'],['diligence','Diligence'],['final_approval','Final Approval'],['closed','Closed'],['lost','Lost / Pass']] as const;
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)||0);
const card:React.CSSProperties={background:'#0D1728',border:'1px solid #263958',borderRadius:15,padding:15};
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#08111F',border:'1px solid #2C3F5E',borderRadius:9,color:'#F8FAFC',padding:'10px 11px'};
const blank={business_name:'',website:'',source_url:'',industry:'',city:'',state:'',asking_price:0,estimated_revenue:0,estimated_ebitda:0,seller_finance_willingness:50,reason_for_sale:'',notes:''};

export default function PipelinePage(){
 const [data,setData]=useState<Payload|null>(null); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const [inspecting,setInspecting]=useState(false); const [pendingEvidence,setPendingEvidence]=useState<string[]>([]);
 const [form,setForm]=useState({...blank});
 async function load(){try{const r=await fetch('/api/acquisitions/pipeline',{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load.');setData(p);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load.');}}
 useEffect(()=>{load();},[]);
 async function inspect(){if(!form.source_url.trim())return setError('Paste a public business or listing URL first.');setInspecting(true);setError('');try{const r=await fetch('/api/acquisitions/discover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:form.source_url})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to inspect URL.');const x=p.extracted||{};setForm(f=>({...f,business_name:x.business_name||f.business_name,website:x.website||f.website,source_url:x.source_url||f.source_url,industry:x.industry||f.industry,city:x.city||f.city,state:x.state||f.state,asking_price:Number(x.asking_price)||f.asking_price,estimated_revenue:Number(x.estimated_revenue)||f.estimated_revenue,estimated_ebitda:Number(x.estimated_ebitda)||f.estimated_ebitda,reason_for_sale:x.reason_for_sale||f.reason_for_sale,notes:[f.notes,x.notes].filter(Boolean).join(' ')}));setPendingEvidence(Array.isArray(x.evidence)?x.evidence.filter((v:any)=>typeof v==='string').slice(0,12):[]);setError('Listing inspected. Review every field before saving.');}catch(e){setError(e instanceof Error?e.message:'Unable to inspect.');}finally{setInspecting(false);}}
 async function create(){if(!form.business_name.trim())return setError('Business name is required.');setSaving(true);setError('');try{const r=await fetch('/api/acquisitions/pipeline',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to create lead.');if(pendingEvidence.length&&p.lead?.id){await Promise.all(pendingEvidence.map(claim=>fetch(`/api/acquisitions/${p.lead.id}/evidence`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category:'Source Intake',claim,source_type:'public_url',source_label:'Imported public listing',source_url:form.source_url,confidence:60,verified:false})})));}setForm({...blank});setPendingEvidence([]);setError(`Added to pipeline${p.thesis?.fit?.score!=null?` · thesis fit ${p.thesis.fit.score}/100`:''}.`);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to create lead.');}finally{setSaving(false);}}
 const byStage=useMemo(()=>Object.fromEntries(stages.map(([key])=>[key,(data?.leads||[]).filter(l=>l.stage===key)])),[data]);
 const metrics=data?.metrics;
 return <main style={{minHeight:'100vh',background:'#07101D',color:'#F8FAFC',fontFamily:'Arial,sans-serif',padding:'24px 18px 70px'}}><div style={{maxWidth:1500,margin:'0 auto'}}>
  <nav style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><strong>ARIDON 3 · ACQUISITION PIPELINE</strong><div style={{display:'flex',gap:14,flexWrap:'wrap'}}><Link href="/acquisitions/thesis" style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>Acquisition Thesis</Link><Link href="/acquisitions/playbook" style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>90-Day Playbook</Link><Link href="/acquisitions" style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>Deal Engine</Link><Link href="/dashboard" style={{color:'#9EF0CF',textDecoration:'none',fontWeight:900}}>Dashboard</Link></div></nav>
  <header style={{padding:'42px 0 20px'}}><div style={{color:'#9EF0CF',fontSize:12,fontWeight:950}}>FIND → VERIFY → UNDERWRITE → NEGOTIATE → CLOSE → OPERATE</div><h1 style={{fontSize:'clamp(40px,6vw,68px)',lineHeight:1,margin:'8px 0 12px'}}>One board for every acquisition.</h1><p style={{color:'#AEBBD0',fontSize:17,maxWidth:900,lineHeight:1.6}}>Import a public listing or enter a lead manually. Aridon screens it against the active acquisition thesis, preserves source evidence, then carries the record through underwriting, financing, negotiation, LOI, diligence, approval and the first 100 days.</p>{data?.thesis?<div style={{color:'#8EA0B8',fontSize:13}}>Active thesis: <strong style={{color:'#DCE7F5'}}>{data.thesis.name}</strong></div>:<div style={{color:'#FFD39D',fontSize:13}}>No active acquisition thesis yet. Create one before relying on fit scores.</div>}</header>
  {metrics?<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:9,marginBottom:16}}>{([['Total',metrics.total],['Hot',metrics.hot],['Negotiating',metrics.negotiating],['LOI Pending',metrics.loiPending],['Diligence',metrics.diligence],['Close Ready',metrics.closeReady],['Follow-ups Due',metrics.followUpsDue]] as const).map(([l,v])=><div key={l} style={card}><div style={{color:'#8092AC',fontSize:11,fontWeight:900}}>{l}</div><div style={{fontSize:28,fontWeight:950,marginTop:4}}>{v}</div></div>)}</section>:null}
  <section style={{...card,marginBottom:18}}><h2 style={{margin:'0 0 12px'}}>Capture or inspect a business</h2><div style={{display:'grid',gridTemplateColumns:'minmax(260px,1fr) auto',gap:9,alignItems:'end',marginBottom:11}}><label>Public business / listing URL<input style={{...input,marginTop:5}} value={form.source_url} onChange={e=>setForm(f=>({...f,source_url:e.target.value}))} placeholder="https://…"/></label><button onClick={inspect} disabled={inspecting} style={{border:'1px solid #405677',borderRadius:9,padding:'10px 13px',background:'#13223A',color:'#F8FAFC',fontWeight:900,cursor:'pointer'}}>{inspecting?'Inspecting…':'Inspect URL'}</button></div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10}}>{([['business_name','Business name'],['website','Website'],['industry','Industry'],['city','City'],['state','State']] as const).map(([k,l])=><label key={k}>{l}<input style={{...input,marginTop:5}} value={form[k]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></label>)}{([['asking_price','Asking price'],['estimated_revenue','Revenue'],['estimated_ebitda','EBITDA / SDE'],['seller_finance_willingness','Seller-finance willingness %']] as const).map(([k,l])=><label key={k}>{l}<input type="number" style={{...input,marginTop:5}} value={form[k]||''} onChange={e=>setForm(f=>({...f,[k]:Number(e.target.value)||0}))}/></label>)}</div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:10,marginTop:10}}><label>Reason for sale<input style={{...input,marginTop:5}} value={form.reason_for_sale} onChange={e=>setForm(f=>({...f,reason_for_sale:e.target.value}))}/></label><label>Notes<input style={{...input,marginTop:5}} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></label></div>{pendingEvidence.length?<div style={{color:'#8EA0B8',fontSize:12,marginTop:9}}>{pendingEvidence.length} source facts are queued for the evidence ledger. They remain unverified until corroborated.</div>:null}<button onClick={create} disabled={saving} style={{marginTop:12,border:0,borderRadius:9,padding:'11px 15px',background:'#9EF0CF',color:'#07101D',fontWeight:950,cursor:'pointer'}}>{saving?'Saving…':'Add to Pipeline'}</button>{error?<div style={{color:error.startsWith('Added')||error.startsWith('Listing')?'#BFEAD7':'#FFB4B4',marginTop:9}}>{error}</div>:null}</section>
  <section style={{overflowX:'auto',paddingBottom:10}}><div style={{display:'grid',gridTemplateColumns:`repeat(${stages.length},minmax(245px,1fr))`,gap:10,minWidth:2700}}>{stages.map(([key,label])=><div key={key} style={{background:'#0A1423',border:'1px solid #243653',borderRadius:14,padding:11,minHeight:220}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:9}}><strong>{label}</strong><span style={{color:'#7F91AA'}}>{(byStage[key]||[]).length}</span></div><div style={{display:'grid',gap:9}}>{(byStage[key]||[]).map((lead:Lead)=><Link key={lead.id} href={`/acquisitions/${lead.id}`} style={{...card,textDecoration:'none',color:'#F8FAFC',display:'block'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong>{lead.business_name}</strong><span style={{color:'#9EF0CF',fontWeight:900}}>{lead.score?.overall_score??'—'}</span></div><div style={{color:'#8FA0B8',fontSize:12,marginTop:5}}>{[lead.industry,lead.city,lead.state].filter(Boolean).join(' · ')||'Unclassified'}</div><div style={{display:'flex',justifyContent:'space-between',gap:8,marginTop:8,fontSize:12,color:'#B6C2D3'}}><span>{lead.asking_price?money(lead.asking_price):'No ask yet'}</span><span>thesis {lead.thesis_fit_score||0}/100</span></div><div style={{fontSize:12,color:'#8496AF',marginTop:5}}>{lead.score?.recommendation||'unscored'}</div></Link>)}</div></div>)}</div></section>
 </div></main>;
}
