import Link from 'next/link';
import { ArrowRight, BadgeDollarSign, CheckCircle2, Database, Handshake, Leaf, Network, ShieldCheck, Users } from 'lucide-react';

const flow = [
  ['1. Rancher intake', 'Capture goals, constraints, geography, enterprise type, water / grazing needs, preferred communication and data-sharing permissions.'],
  ['2. Advisor match', 'Match the producer to trusted advisors, peer networks and technical-service providers by problem, geography, expertise and relationship fit.'],
  ['3. Action plan', 'Turn the relationship into a practical plan with milestones, responsibilities, estimated economics and farmer-approved next steps.'],
  ['4. Capital match', 'Surface public cost share, grants, conservation finance, supply-chain support and other capital that can make adoption feasible.'],
  ['5. Evidence trail', 'Track visits, actions, agreed outcomes, grant deliverables, maintenance and field observations without forcing every partner into the same workflow.'],
  ['6. Network learning', 'Aggregate what is working across regions while protecting private ranch data, so the advisor network gets smarter without flattening local judgment.'],
];

export default function RangeProposalPage() {
  return <main style={{ minHeight:'100vh', background:'#f4f1e8', color:'#18251d', fontFamily:'Arial,sans-serif' }}>
    <section style={{ background:'#102d25', color:'#fff', padding:'16px 18px' }}><div style={{ maxWidth:1120, margin:'auto', display:'flex', justifyContent:'space-between', gap:12, flexWrap:'wrap' }}><strong>ARIDON AG · PROJECT RANGE FIT</strong><Link href="/ag/rancher-network" style={{ color:'#c8e2ac', textDecoration:'none', fontWeight:900 }}>Open Rancher Network OS →</Link></div></section>

    <section style={{ maxWidth:1120, margin:'auto', padding:'64px 18px 48px', display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,350px),1fr))', gap:26, alignItems:'center' }}>
      <div><div style={{ color:'#356943', fontSize:12, fontWeight:950, letterSpacing:1 }}>ARIDON × TNC PROJECT RANGE · CONCEPT FOR DISCUSSION</div><h1 style={{ fontSize:'clamp(48px,7vw,78px)', lineHeight:.96, letterSpacing:-2.5, margin:'12px 0 19px' }}>Make Aridon the digital operating layer behind a trusted ranching-advisor network.</h1><p style={{ color:'#556159', fontSize:20, lineHeight:1.65 }}>The Nature Conservancy is launching Project RANGE, the Ranching Advisor Network for Grazing Enterprises, and is publicly seeking partners and funders for Phase 1. Aridon’s Rancher Network OS can support the part that gets difficult at scale: intake, matching, funding, follow-up, evidence and cross-network learning.</p></div>
      <aside style={{ background:'#163d2a', color:'#fff', padding:23, borderRadius:22, boxShadow:'0 18px 55px rgba(22,61,42,.18)' }}><Network size={34} color="#c8e2ac"/><div style={{ color:'#c8e2ac', fontSize:11, fontWeight:950, marginTop:10 }}>POSITIONING</div><h2 style={{ fontSize:34, lineHeight:1.08, margin:'7px 0 11px' }}>Do not pitch a competing network.</h2><p style={{ color:'#dce8e0', lineHeight:1.65, margin:0 }}>Pitch Aridon as infrastructure that helps Project RANGE and existing rancher-led organizations coordinate trusted advisors, producer needs and outcomes. TNC keeps the conservation strategy. Local groups keep the relationships. Aridon helps the machinery between them run.</p></aside>
    </section>

    <section style={{ background:'#fff', borderTop:'1px solid #d7dfd4', borderBottom:'1px solid #d7dfd4', padding:'50px 18px' }}><div style={{ maxWidth:1120, margin:'auto' }}><div style={{ color:'#356943', fontSize:12, fontWeight:950 }}>WHY THIS IS TIMELY</div><h2 style={{ fontSize:'clamp(36px,5vw,54px)', margin:'8px 0 15px' }}>TNC has already validated the network idea. We can help operationalize it.</h2><p style={{ color:'#5d6861', lineHeight:1.65, fontSize:17 }}>TNC says it used an Entrepreneur in Residence process to develop Project RANGE and is now seeking partners and funders for Phase 1. Its Project RANGE materials call for a market-driven network of trained and trusted advisors that can support ranchers adopting sustainable practices. That means our best opening is not “we invented a rancher network.” It is “we built software that can help your advisor network work at field scale.”</p><div style={{ display:'flex', gap:12, flexWrap:'wrap', marginTop:14 }}><a href="https://www.nature.org/en-us/what-we-do/our-priorities/provide-food-and-water-sustainably/food-and-water-stories/ag-innovation-pilot-projects/" target="_blank" rel="noreferrer" style={{ color:'#356943', fontWeight:900 }}>TNC Project RANGE overview ↗</a><a href="https://www.nature.org/content/dam/tnc/nature/en/documents/FactSheet_RANGE_2025_2.0.pdf" target="_blank" rel="noreferrer" style={{ color:'#356943', fontWeight:900 }}>Project RANGE fact sheet ↗</a></div></div></section>

    <section style={{ maxWidth:1120, margin:'auto', padding:'56px 18px' }}><div style={{ color:'#356943', fontSize:12, fontWeight:950 }}>THE DIGITAL BACKBONE</div><h2 style={{ fontSize:'clamp(36px,5vw,54px)', margin:'8px 0 20px' }}>Six steps from “I need help” to a measurable outcome.</h2><div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))', gap:10 }}>{flow.map(([title,text], i) => <article key={title} style={{ background:'#fff', border:'1px solid #d7dfd4', borderRadius:16, padding:17 }}><div style={{ width:34, height:34, borderRadius:99, display:'grid', placeItems:'center', background:'#e5eee0', color:'#356943', fontWeight:950 }}>{i+1}</div><h3 style={{ fontSize:21, margin:'9px 0 5px' }}>{title}</h3><p style={{ color:'#5f6962', lineHeight:1.52, margin:0 }}>{text}</p></article>)}</div></section>

    <section style={{ background:'#102d25', color:'#fff', padding:'56px 18px' }}><div style={{ maxWidth:1120, margin:'auto' }}><div style={{ color:'#c8e2ac', fontSize:12, fontWeight:950 }}>WHAT EACH PARTY KEEPS</div><h2 style={{ fontSize:'clamp(38px,5vw,56px)', margin:'8px 0 20px' }}>Partnership without swallowing the ecosystem.</h2><div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))', gap:10 }}>{[
      [Leaf,'TNC','Conservation strategy, science, program design, funding relationships and outcome standards.'],
      [Users,'Rancher-led groups','Local trust, producer relationships, peer learning, cultural context and field judgment.'],
      [Handshake,'Trusted advisors','Technical assistance, implementation support and long-term producer relationships.'],
      [Database,'Aridon','Intake, matching, workflow, funding intelligence, evidence, grant tracking and aggregate network learning.'],
    ].map(([Icon,title,text]) => { const C=Icon as typeof Leaf; return <article key={String(title)} style={{ background:'#173a30', border:'1px solid #2a5243', borderRadius:16, padding:17 }}><C size={26} color="#c8e2ac"/><h3 style={{ fontSize:22, margin:'9px 0 5px' }}>{String(title)}</h3><p style={{ color:'#dce8e0', lineHeight:1.5, margin:0 }}>{String(text)}</p></article>; })}</div></div></section>

    <section style={{ maxWidth:1120, margin:'auto', padding:'56px 18px' }}><div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(310px,1fr))', gap:14 }}>
      <article style={{ background:'#fff', border:'1px solid #d7dfd4', borderRadius:20, padding:21 }}><BadgeDollarSign size={29} color="#356943"/><div style={{ color:'#356943', fontSize:11, fontWeight:950, marginTop:9 }}>PHASE 1 PILOT OFFER</div><h2 style={{ fontSize:31, margin:'6px 0 10px' }}>$50,000 · 90 days</h2><p style={{ color:'#59645c', lineHeight:1.6 }}>Configure Aridon for one Project RANGE / RGL use case with 25–50 ranchers, 6–12 staff or partner users and two to three regions. Includes workflow co-design, onboarding, advisor / producer matching, funding and grant tracking, dashboard and closeout evaluation.</p><p style={{ color:'#59645c', lineHeight:1.6, marginBottom:0 }}>Travel, field hardware, third-party datasets and custom integrations remain separately scoped.</p></article>
      <article style={{ background:'#e6ecdf', border:'1px solid #d2dccf', borderRadius:20, padding:21 }}><ShieldCheck size={29} color="#356943"/><div style={{ color:'#356943', fontSize:11, fontWeight:950, marginTop:9 }}>DATA PRINCIPLE</div><h2 style={{ fontSize:31, margin:'6px 0 10px' }}>The rancher is not the product.</h2><p style={{ color:'#59645c', lineHeight:1.6 }}>Private ranch records remain permissioned. Network learning defaults to aggregate information. Local organizations keep their relationship role. Tribal participants require governance aligned with the participating Nation’s data-sovereignty requirements.</p></article>
    </div></section>

    <section style={{ background:'#fff', borderTop:'1px solid #d7dfd4', borderBottom:'1px solid #d7dfd4', padding:'54px 18px' }}><div style={{ maxWidth:1000, margin:'auto' }}><div style={{ color:'#356943', fontSize:12, fontWeight:950 }}>THE MEETING</div><h2 style={{ fontSize:'clamp(38px,5vw,56px)', margin:'8px 0 16px' }}>Ask to plug into Phase 1, not to redesign it.</h2><div style={{ display:'grid', gap:9 }}>{[
      ['Opening', '“We saw that TNC is seeking partners for Project RANGE. We are not proposing another advisor network. We built an operating system that can help your network intake ranchers, match trusted advisors, find capital and preserve the evidence trail.”'],
      ['Live demo', 'Walk one fictional ranch through intake, water risk, advisor match, funding opportunity, action plan and grant deliverable. Keep this under seven minutes.'],
      ['Proof question', 'Ask which part of Phase 1 is hardest today: partner coordination, rancher intake, advisor matching, funding, data governance, field evidence or reporting. Configure the pilot around their answer.'],
      ['Close', 'Ask for one 90-day pilot, one internal champion and one or two partner organizations. Do not ask for national rollout until the pilot earns it.'],
    ].map(([title,text]) => <div key={title} style={{ background:'#faf9f4', border:'1px solid #dde3d8', borderRadius:14, padding:15 }}><strong style={{ fontSize:18 }}>{title}</strong><div style={{ color:'#5e6861', lineHeight:1.55, marginTop:5 }}>{text}</div></div>)}</div></div></section>

    <section style={{ maxWidth:900, margin:'auto', padding:'56px 18px 72px', textAlign:'center' }}><CheckCircle2 size={34} color="#356943"/><div style={{ color:'#356943', fontSize:12, fontWeight:950, marginTop:9 }}>CONTACT PATH</div><h2 style={{ fontSize:'clamp(38px,5vw,56px)', margin:'8px 0 13px' }}>Start with the people leading the grazing strategy and Project RANGE.</h2><p style={{ color:'#5d6861', lineHeight:1.65, fontSize:17 }}>Public TNC materials list Nancy Labbe, Co-Director of the Regenerative Grazing Lands Strategy, at <a href="mailto:nancy.labbe@tnc.org" style={{ color:'#356943', fontWeight:900 }}>nancy.labbe@tnc.org</a>, and Project RANGE materials also list Kayla Sainato at <a href="mailto:kayla.sainato@tnc.org" style={{ color:'#356943', fontWeight:900 }}>kayla.sainato@tnc.org</a>. The broader RGL fact sheet lists co-director Rob Manes at <a href="mailto:rmanes@tnc.org" style={{ color:'#356943', fontWeight:900 }}>rmanes@tnc.org</a>.</p><Link href="/ag/rancher-network" style={{ display:'inline-flex', alignItems:'center', gap:8, marginTop:12, background:'#163d2a', color:'#fff', padding:'14px 17px', borderRadius:11, textDecoration:'none', fontWeight:950 }}>Open the working network <ArrowRight size={18}/></Link><div style={{ color:'#7a827c', fontSize:11, lineHeight:1.5, marginTop:18 }}>Concept for discussion only. No TNC or Project RANGE endorsement, partnership or procurement is implied. Pilot price and scope are an Aridon planning offer subject to contracting.</div></section>
  </main>;
}
